### ISSUE TITLE
Page Daftar Sample WGS

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#1000]
## Protoype Page Daftar Sample WGS
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?node-id=2269%3A750&scaling=scale-down&page-id=2160%3A351&starting-point-node-id=2251%3A14579

## Acceptance Criteria
- [x] Terdapat fungsi untuk memfilter data berdasarkan Nomor Sample, Tanggal Swab, dan Instansi Pengirim
- [x] Terdapat button import data dari SIM Lab (Import Pikobar) untuk direct ke page Form Import Pikobar
- [x]  Terdapat Reset Filter (Clear Filter)
- [x] Terdapat list daftar sample pasien, order by Tanggal Input DESC
- [x] Terdapat button detail untuk direct ke page Detail Data
- [x] Perubahan kategori jadi kriteria

**Comment by maruf12** [comment]
Guys ada beberapa yang perlu dikonfirmasi dong:
-Pagination yang Instansi pengirim dari endpoint (list-fasyankes-jabar) bukan? @firmanJS 
- lab_pcr_nama itu fasyankes_nama bukan? @firmanJS 
- tanggalnya range atau single date @erlangganugraha

**Comment by maruf12** [comment]
![image](https://user-images.githubusercontent.com/9880869/148153505-6a97431c-b6cd-4032-92db-693f3ea9c17a.png)
Ini bedanya `kode sampel` sama `nomor sampel` apa ya guys @erlangganugraha @sandisunandar99

**Comment by maruf12** [comment]
![image](https://user-images.githubusercontent.com/9880869/148155829-49b3f56c-d652-4827-ad37-36e4572d01f0.png)
@sandisunandar99 response yang ini kurang kategori eng kang

**Comment by maruf12** [comment]
![image](https://user-images.githubusercontent.com/9880869/148158469-0600af88-5638-44b5-9b8f-22a3a9e66243.png)
@sandisunandar99 yang filter fasyankes juga dibikin kyk di gambar aja kang. namenya `fasyankes` terus valuenya `id` nya aja jangan name. Ini biar seragam sama list yang lain

**Comment by sandisunandar99** [comment]
oke @maruf12 aku coba cek2 dlu ya..

**Comment by shintadewiaw** [comment]
Feedback 05/01/2021

- [ ] Perlu menambahkan Instansi Pengiriman pada list daftar sampel
- [ ] Hide waktu pada kolom tanggal swab
- [ ] Hide waktu pada kolom tanggal sampel masuk

@maruf12

**Comment by shintadewiaw** [comment]
@sandisunandar99 mas sandi kalau filter instansi pengirim udah kabarin yaa

**Comment by shintadewiaw** [comment]
@sandisunandar99 link preview: https://deploy-preview-779--staging-pikobar-lab.netlify.app/wgs/index

**Comment by sandisunandar99** [comment]
saya belum bsa konek2 ke ke db staging langusng oy buat pairing data. hrap bersabar ya unutk dev yg ini wkwk cc ; @shintadewiaw @maruf12 

<img width="1287" alt="Screen Shot 2022-01-06 at 16 35 51" src="https://user-images.githubusercontent.com/6767399/148362029-dc7fd1b0-6953-45f0-a9e3-5a62741bc2ec.png">

**Comment by shintadewiaw** [comment]
@sandisunandar99 mas db staging cuma bisa diakses dikantor cenah sekarang pake wifi  PLD_Gedung Selatan, karna tadi aku juga gabisa connect yang desa digital wkwk

**Comment by sandisunandar99** [comment]
@shintadewiaw atuh kalo gitu mah masa saya harus ke kantor wae,, wkwkwk

**Comment by shintadewiaw** [comment]
Feedback List Daftar Sampel Pasien 19/01 @maruf12 

- [ ] Redaksi kategori di list daftar sampel pasien diubah menjadi kriteria
- [ ] Kategori diubah menjadi kriteria, valuenya mengikuti inputan user
