### ISSUE TITLE
Page Detail Sample

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#1001]
## Prototype Page Detail Daftar Sample
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?node-id=2269%3A750&scaling=scale-down&page-id=2160%3A351&starting-point-node-id=2251%3A14579

## Acceptance Criteria
- [x] Terdapat informasi data daftar sample secara detail, dengan 2 sub group :
   - [x] 1. Detail Informasi Sample
   - [x] 2. Detail Kriteria WGS
- [x] Terdapat button Perbarui Data untuk direct ke Page Edit Daftar Sample WGS

**Comment by firmanJS** [comment]
endpoint /api/v1/kriteria-wgs/:kode_sampel @maruf12

**Comment by maruf12** [comment]
Untuk fitur `Detail Import Pikobar` belum ada cardnya dan tidak ada di figma. Apakah `Detail Import Pikobar` akan tetap dieksekusi?
Jika dieksekusi data yang akan ditampilkan ke user apa saja?
Data yang ada di API sbb:

`counter_print_hasil: null
created_at: "2021-03-04T07:02:17.000000Z"
deskripsi: "Sampel Valid"
fasyankes_nama: "Klinik Tongfeng 2"
fasyankes_pengirim: "dinkes_kota"
hasil_deteksi: [{ct_value: "231", target_gen: "apa?"}]
id: 93954
jenis_kelamin: "L"
jenis_registrasi: "rujukan"
jenis_sampel_nama: "Usap Nasofaring & Orofaring"
kecamatan: "PURWAKARTA"
kelurahan: "NAGRIKIDUL"
kesimpulan_pemeriksaan: "positif"
kunjungan_ke: "5"
nama_kota: "PURWAKARTA"
nama_lengkap: "Rujukan Import"
nik: "1301031672226123"
no_hp: "0812312321321"
no_rt: "2"
no_rw: "3"
nomor_register: "R202103040001"
nomor_sampel: "R4032021"
petugas_pengambilan_sampel: "Baik"
provinsi: "JAWA BARAT"
sampel_status: "sample_valid"
status: 3
sumber_pasien: "Umum"
tanggal_input_hasil: "2021-03-04"
tanggal_lahir: "1989-12-17"
tanggal_mulai_ekstraksi: "2021-03-04T17:00:00.000000Z"
tempat_lahir: "Kota Bandung"
usia_bulan: 2
usia_tahun: 23
validator_id: 1
waktu_sample_print: null
waktu_sample_taken: "2021-03-04T06:54:00.000000Z"
waktu_sample_valid: "2021-03-04T07:56:23.000000Z"
waktu_sample_verified: "2021-03-04T07:54:03.000000Z"`

**Comment by maruf12** [comment]
![image](https://user-images.githubusercontent.com/9880869/148189134-ea802a76-6b6a-4629-b99b-5fe17aaec892.png)
@erlangganugraha Ini kriterianya bisa lebih dari 1 nilainya, apa betul ya?

**Comment by maruf12** [comment]
- ada perbedaan response di setiap detailnya

**Comment by maruf12** [comment]
@shintadewiaw ini bisa ditesting di link yang kemaren ya

**Comment by shintadewiaw** [comment]
**Notes Daily 10/01** @maruf12 @sandisunandar99 

- Tampilan Kriteria dibuat kebawah (Target Khusus dan Representatif) --> Frontend @maruf12 
- Kode Sampel: Kode sampel wgs (ketika sudah terdaftar sebagai kode sampel wgs) generate otomatis --> di Backend kode_sampel di rename menjadi kode_sampel_wgs @sandisunandar99 
- Nomor Sampel: Bawaan dari kode sampel yang registrasi

**Comment by shintadewiaw** [comment]
mas mas ada 1 ac yang ketinggalan @maruf12 
Terdapat button Perbarui Data untuk direct ke Page Edit Daftar Sample WGS

**Comment by sandisunandar99** [comment]
> @sandisunandar99 kang yang detail wgs (enpoint: `{{host}}/api/v1/kriteria-wgs/:kode_sampel`) perlu diupdate idnya jadi `kode_sampel_wgs` soalnya tadi dari FE diubah ke endpoint `kode_sampel_wgs` responsenya masih error.
> 
> <img alt="Screen Shot 2022-01-20 at 09 42 29" width="1440" src="https://user-images.githubusercontent.com/9880869/150262820-4a4a08f5-a151-465f-9729-524bb0109e16.png">

oh ,, oke,, saya cek dlu nya

**Comment by sandisunandar99** [comment]
@shintadewiaw udah ku perbaiki ya, tinggal di test aja ..
