### ISSUE TITLE
Page Import Dari Pikobar 

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#1003]
## Prototype Page Import Dari Pikobar
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?node-id=2284%3A2058&scaling=scale-down&page-id=2160%3A351&starting-point-node-id=2251%3A14579

## Acceptance Critreria
- [x] Terdapat List Daftar Pasien Positif yang sudah tervalidasi
- [x] Terdapat fungsi untuk memfilter data
- [x] Terdapat fungsi Reset Filter (Clear Filter)
- [x] Terdapat button Detail Data untuk direct ke Page Detail Daftar Pasien
- [x] Terdapat button Pilih Kriteria WGS untuk direct ke Page Pilih Kriteria WGS

**Comment by maruf12** [comment]
https://deploy-preview-771--staging-pikobar-lab.netlify.app/wgs/import-pikobar
@shintadewiaw ready to test di preview sin

**Comment by shintadewiaw** [comment]
Feedback 24/12/2021
- [ ] Instansi pengirim ketika di reset tidak terhapus valuenya

**Comment by maruf12** [comment]
![image](https://user-images.githubusercontent.com/9880869/147310263-2ec3196a-3d2f-4de1-a74e-519a3c94332d.png)
Untuk data `Tanggal Sampel Masuk` pake data yang mana ya guys, gambar di atas response dari BE data tanggal ada banyak soalnya wkwk
cc @firmanJS @erlangganugraha @shintadewiaw

**Comment by maruf12** [comment]
@shintadewiaw dah di solved issuenya sin. bisa di cek di previewnya

**Comment by shintadewiaw** [comment]
@maruf12 mas gantian nomor sampelnya ga kereset ya, minta tolong cek lagii
