### ISSUE TITLE
[List Hasil Test] Total hasil test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#104]
## User Story
Sebagai dinkes kota/kab saya ingin melihat total data hasil test agar saya tahu data kesuluruhan yang sudah saya inputkan

## Wireframe
<img width="798" alt="Screen Shot 2020-03-30 at 16 20 36" src="https://user-images.githubusercontent.com/11548871/77899764-3b680880-72a7-11ea-8281-80477918db11.png">

## Acceptance Criteria :
* [x] Terdapat section total data dilist hasil test

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by alifianif** [comment]
ini saya cek udah done ya. Punten gabisa nyeklis To Do-nya 
cc @aliyaqara
