### ISSUE TITLE
[Dashboard] Penambahan label box "POSITIF AKTIF"

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#110]
## Wireframe
![Group 849](https://user-images.githubusercontent.com/11548871/78218728-75741d00-74e8-11ea-8ba5-1324455069fa.png)

## Acceptance Criteria :
* [x] Penambahan label box "POSITIF AKTIF" untuk mengetahui pasien yang masih aktif terjangkit corona, rumusnya : (Terkonfirmasi) - (sembuh + meninggal)

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by alifianif** [comment]
Mau nanya dong, ini statusnya udah sampai mana ya? sampai perhitungannya benar atau baru penambahan label box "Positif Aktif" saja?
cc @erlangganugraha @Arif9878

**Comment by Arif9878** [comment]
sampai perhitungannya benar juga lif

**Comment by alifianif** [comment]
sekarang label positif-aktifnya lagi ditakedown dulu apa gimana ya? @Arif9878

**Comment by Arif9878** [comment]
@alifianif 
iya lagi di takedown lif sampek hitungannya bener

**Comment by saktiperdana** [comment]
kayanya balikin aja dulu ga cardnya?
