### ISSUE TITLE
[Pendaftaran] Get Data Pendaftaran dari App Pendaftaran

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#111]
## User Story
Sebagai dinkes kota/kab saya ingin mencari data peserta yang akan inputkan hasil testnya, yang dimana data peserta sudah didaftarkan melalui aplikasi pendaftaran

## Acceptance Criteria :
* [x] Data yang diget hanya peserta yang mengikuti test berdasarkan :
   * [x] Dinkes Kota/kab nya
   * [x] Belum punya hasil test
   * [x] Peserta yang hadir dalam melakukan test
* [x] Terdapat input pencarian daftar peserta
* [x] Jika daftar peserta ditemukan maka otomatis data peserta tersebut tampil disection :
  * [ ] Mekanisme Tes   
  * [x] Data diri peserta
* [x] Jika data peserta tidak ditemukan maka input manual

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
1. Mekanisme tes tidak otomatis terisi
2. Tolong diperjelas acceptance criterianya, maksud dari belum punya hasil tes itu apa. Apakah benar-benar belum punya hasil tes atau yang hasil tesnya negatif dan invalid juga muncul?

@erlangganugraha

**Comment by saktiperdana** [comment]
Sorry, ini ketika kita mau input hasil testnya, list peserta yang muncul ini data inputan se Jawa Barat kah ? atau mungkin baiknya di filter berdasarkan kab/kota saja ? (misal, dinkesmajalengka hanya dapat input hasil test dari daerahnya saja)

**Comment by erlangganugraha** [comment]
aku jawab :
1. Mekanisme ini tidak terisi karena didatabse pendaftaran memang tidak ada data mekanisme
2. Belum punya hasil test itu belum terisi hasil test RDT baik itu positif, negatif ataupun invalid
@alifianif 

FYI kita ada perubahan signifikan utk fitur RDT ini

**Comment by saktiperdana** [comment]
ini acceptance kriterianya  ada yang diubah, atau cardnya balikin dulu aja mang ke to do kalau memang ada perubahan di fitur RDT nya ?
@erlangganugraha
