### ISSUE TITLE
Detail Hasil Test untuk Dinkes Provinsi

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#115]
## User Story
Sebagai dinkes provinsi saya ingin melihat detail peserta agar saya bisa lihat secara lengkap profil peserta maupun hasil testnya

## Wireframe
![Screenshot_2020-04-04 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/78422948-316e4d00-768d-11ea-9664-55d1e48ea7f0.png)

## Acceptance Criteria :
* [x] Terdapat button kembali ke list
* [x] Terdapat detail peserta
* [x] Terdapat hasil test

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by maruf12** [comment]
@alifianif @aliyaqara udah bisa ditest ya
