### ISSUE TITLE
Export To Excel List Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#127]
## User Story
Sebagai dinkes kota/kab/provinsi saya ingin mengexport data list kasus sehingga saya bisa menganalisa data kasus

## Acceptance Criteria :
* [x] Dinkes provinsi bisa export data
* [x] Dinkes kota/kab bisa export data
* [x] Export data to excel berformat .xlsx
* [x] Kolom yang diexport sebagai berikut :
1. Kode kasus => COVID-1011200016
2. Kode Kasus pusat => K0001
3. Tgl lapor => 12/04/2020
4. Sumber lapor => Rumah Sakit
5. NIK => 111093278323
6. Nama => Erlangga Nugraha
7. Tgl Lahir => 17/03/2020
8. Usia => 24
9. JK => L
10. Alamat Tempat Tinggal (Detail alamat, Kelurahan Kecamatan. Kota, Jawa Barat) => Jl. Maulana Yusuf No. 3 Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat
11. No Telepon => 089638625153
12. Kewarganegaraan => WNI
13. Negara => Indonesia
14. Pekerjaan => Product Manager
15. Gejala => Suhu tubuh >= 38 °C, Sakit Tenggorokan
16. Riwayat => Kontak Dengan Pasien Positif
17. Status => ODP
18. Stage => Proses
19. Hasil
20. Lokasi saat ini => Jl. Maulana Yusuf No. 3 Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat
21. Tanggal Input => 12/04/2020
22. Author => Dinkes Kota Cimahi
* [x] Jika data yang di filter/sorting maka data yang diexport sesuai hasil filter & sorting

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by firmanJS** [comment]
@Arif9878 api/cases-export

tinggal filter nya lanjut besok
