### ISSUE TITLE
Detail kasus untuk Dinkes Provinsi

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#128]
## User Story
Sebagai dinkes provinsi saya ingin melihat detail profil kasus agar saya bisa lihat secara lengkap profil maupun riwayat

## Wireframe
![Screenshot_2020-04-07 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/78631914-c0ff4000-78c7-11ea-91f4-dde6929b3f63.png)

## Acceptance Criteria :
* [x] Terdapat button kembali ke list
* [x] Terdapat detail profil pasien
* [x] Terdapat list riwayat

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by firmanJS** [comment]
@maruf12 ini bisa pakai api yang ada

**Comment by maruf12** [comment]
@alifianif @aliyaqara udah bisa ditest ya

**Comment by alifianif** [comment]
1. Pagination di list masih tidak berfungsi. Di halaman 1 datanya 1-10 tapi di halaman 2 datanya 31-40
2. Tidak terdapat list riwayat

@maruf12 @firmanJS

**Comment by firmanJS** [comment]
@maruf12 

no 1 api udah ok tinggal pagination di frontend nya ruf
no 2 pake api ini api/cases/5e8c2f5d6190c70012a1e7b2/history

**Comment by firmanJS** [comment]
@maruf12 

no 1 api udah ok tinggal pagination di frontend nya ruf
no 2 pake api ini api/cases/5e8c2f5d6190c70012a1e7b2/history
