### ISSUE TITLE
[Revisi] Perhitungan sembuh

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#130]
## User Story
Sebagai dinkes kota/kab/provinsi saya ingin mengexport data list kasus sehingga saya bisa menganalisa data kasus

### Page Dashboard
* [x] Perhitungan sembuh hanya dihitung yang statusnya Positif

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by alifianif** [comment]
er @erlangganugraha ini kalau pasiennya sembuh jumlah di POSITIF ga berkurang ya? Soalnya di data berikut saya nambahin 3 positif dan tiga-tiganya sembuh tapi jumlah yang statusnya POSITIF tidak berkurang, sementara jumlah yang statusnya SEMBUH bertambah.
