### ISSUE TITLE
[Enhancement] Penyesuaian field Rumah Sakit pada Input Hasil Test

### ISSUE THREAD

**Issue by maruf12** [jabardigitalservice/pikobar-pelaporan-frontend#135]
Penyesuaian filed Tempat Test (Rumah Sakit) pada Input Hasil Test. Menyesuaikan dengan kebutuhan aplikasi logistik.

**Comment by alifianif** [comment]
Ini maksudnya rumah sakit yang muncul adalah rumah sakit sesuai lokasi dinkesnya kan ya? Kalo iya, udah bener ya ini saya close.
