### ISSUE TITLE
Filter & Sorting List Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#157]
## User Story
Sebagai dinkes saya ingin memfilter & mengurutkan list kasus sehingga saya bisa untuk memilih data sesuai data yang disaring & disorting yang diinginkan

## Mockup
link figma 

## Acceptance Criteria :
* [x] Terdapat dilfilter berdasarkan :
  * [x] Kriteria
  * [x] Hasil
  * [x] Range Tanggal Input
  * [x] Kab/Kota *jika login sebagai dinkes prov
  * [x] Kelurahan
  * [x] Kecamatan
* [x] Terdapat sorting berdasarkan :
  * [x] Kode Kasus
  * [x] Nama
  * [x] Usia
  * [x] Jenis Kelamin
  * [x] Status
  * [x] Tahapan
  * [x] Hasil
* [x] Terdapat reset filter/sorting

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by diaseka** [comment]
![filter Detail Kasus](https://user-images.githubusercontent.com/62875227/79095302-43827680-7d84-11ea-928a-38c020e60b27.png)

**Comment by naufalihsank** [comment]
kang @firmanJS punten kalo parameter terkait filter sama sorting list kasus apa aja ya ?

**Comment by naufalihsank** [comment]
kang @diaseka punten kalo tombol exportnya dimana ya ?

**Comment by firmanJS** [comment]
@naufalihsank fitur ini udah beres kayanya sama @Arif9878 coba di konfirmasi lagi

**Comment by Arif9878** [comment]
@firmanJS iya mang kurang yang filter per wilayah untuk dinkes provinsi, sma filter by kecamatan, kelurahan untuk dinkes kota

**Comment by firmanJS** [comment]
@Arif9878 kecamatan = address_subdistrict_code kelurahan = address_village_code

**Comment by Arif9878** [comment]
@firmanJS itu kurang untuk yang kabupaten mang

**Comment by firmanJS** [comment]
@Arif9878 pake yang ini mang address_district_code

**Comment by saktiperdana** [comment]
Mang @Arif9878 @firmanJS ini AC nya untuk yang di list kasus atau list hasil test ya?
Kalau list kasus :
1. Tanggal mulai dan tanggal selesai ga muncul di field ketika sudah dipilih (secara fungsi bisa)
2. Di list kasus masih belum ada sort by kabupaten/kota login pakai dinkesprov

Mintol dicek yak
