### ISSUE TITLE
[Revisi] Export to excel List Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#159]
## User Story
Sebagai dinkes kota/kab/provinsi saya ingin mengexport data list kasus sehingga saya bisa menganalisa data kasus

## Acceptance Criteria :
* [x] Penamaan file "Data Kasus [Nama Dinkes] - [Tanggal Time Sekarang], Contoh : **Data Kasus Dinkes Kota Cimahi -  12/04/202 19:45 WIB**
* [x] Perubahan kolom & contoh isian data yang diexport sebagai berikut :
1. Kode kasus => COVID-1011200016
2. Kode Kasus pusat => K0001
3. Tgl lapor => 12/04/2020
4. Sumber lapor => Rumah Sakit
5. NIK => 111093278323
6. Nama => Erlangga Nugraha
7. Tgl Lahir => 17/03/2020
8. Usia => 24
9. JK => L
10. Alamat Tempat Tinggal (Detail alamat, Kelurahan Kecamatan. Kota, Jawa Barat) => Jl. Maulana Yusuf No. 3 Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat
11. No Telepon => 089638625153
12. Kewarganegaraan => WNI
13. Negara => Indonesia
14. Pekerjaan => Product Manager
15. Gejala => Suhu tubuh >= 38 °C, Sakit Tenggorokan
16. Riwayat => Kontak Dengan Pasien Positif
17. Status => ODP
18. Stage => Proses
19. Hasil
20. Lokasi saat ini => Jl. Maulana Yusuf No. 3 Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat
21. Tanggal Input => 12/04/2020
22. Author => Dinkes Kota Cimahi

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by firmanJS** [comment]
@erlangganugraha ini udah fix kesepakatan nya gak bakalan ada perubahan lagi kah ?

**Comment by firmanJS** [comment]
@Arif9878 @alifianif @erlangganugraha 

penamaan file tidak bisa ada spasi ya sama tanda ":"

jadi nya pake strip pemisah nya

**Comment by alifianif** [comment]
1. Pada acceptance criteria, nama file terdapat jam export data tapi sekarang masih belum ada jamnya
2. Data pada excel belum sesuai dengan aplikasi. Berikut data-data kolom yang tidak sesuai:
   - NIK sama dengan ID Kasus Pusat, padahal NIK pasien terisi pada aplikasi
   - No telp yang merupakan field mandatory di aplikasi pada data excel kosong
   - Pekerjaan malah diisi dengan data alamat kantor

Testing ini dilakukan pada user dinkeskotabandung
@firmanJS @Arif9878

**Comment by firmanJS** [comment]
@alifianif done ya 
penamaan ga bisa pake tanda `:` ya sama spasi

**Comment by saktiperdana** [comment]
OK, karena tidak bisa pake karakter simbol "/",":" dan spasi, berarti format tanggal dan jam pada reportnya menggunakan "_"

**Comment by saktiperdana** [comment]
Kolom Riwayat ga sesuai isiannya, seharusnya terisi dengan riwayat misal "Kontak dengan pasien positif" tetapi terisi dengan Hasil (contoh meninggal)

**Comment by firmanJS** [comment]
@saktiperdana done mang

**Comment by alifianif** [comment]
@saktiperdana kayanya riwayat di sini itu masuknya ke riwayat kasus deh mas bukan riwayat perjalanan. Coba boleh dipastikan dulu @erlangganugraha @firmanJS ???

**Comment by firmanJS** [comment]
@alifianif sesuai ac nya ya lif pakai yang ini kayanya 
![Screenshot from 2020-04-14 11-55-59](https://user-images.githubusercontent.com/5679509/79187704-37abb880-7e47-11ea-9dd5-f82b120bd115.png)

**Comment by saktiperdana** [comment]
Nyesuaiin sama AC nya mba @alifianif hehe

**Comment by saktiperdana** [comment]
Yang muncul di Riwayat baru yang "Kontak dengan Pasien", kalau ada riwayat "perjalanan luar negeri" atau "perjalanan luar kota" belum muncul ya @firmanJS

**Comment by alifianif** [comment]
@saktiperdana @firmanJS wkwkwk sori sori krg fokus. Oke kalo gitu masih masuk revisi ya ini wkwk

**Comment by shintadewiaw** [comment]
mas @firmanJS @Arif9878 , ini yang kelurahan/desa masuknya jadi kecamatan 
![image](https://user-images.githubusercontent.com/63390998/79215177-748ea400-7e75-11ea-9db6-8b7537cfc76f.png)
![image](https://user-images.githubusercontent.com/63390998/79215350-95ef9000-7e75-11ea-936f-7094d43bf867.png)
