### ISSUE TITLE
Pembuatan API Send hasil test via SMS/WA

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#160]
yang ini hanya backend aja mreun er

**Comment by alifianif** [comment]
Ini kan bagian backend ya dan udah dites juga dan hasilnya SMS+WA sudah diterima. Jadi boleh langsung dipindahin ke Done ga ya? @sandisunandar99 @erlangganugraha

**Comment by sandisunandar99** [comment]
@alifianif manga,,
