### ISSUE TITLE
[Input Hasil Test] Single Input Hasil Test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#161]
![Screen Shot 2020-04-17 at 19 16 37](https://user-images.githubusercontent.com/20775950/79568538-347f2980-80e0-11ea-9345-0f08e768b093.png)

**Comment by azophy** [comment]
## backend
- [x] create model & service for RdtHistory class
- [x] implement RdtHistory creation on `POST /api/rdt` endpoint
- [ ] implement listing RdtHistory for Rdt detail page

**Comment by alifianif** [comment]
![image](https://user-images.githubusercontent.com/17422311/79835295-aacda580-83d8-11ea-88d3-8464f8a7bcaf.png)

punten mau nanya, kalo metode pengetesan emang diset defaultnya PCR atau seharusnya kosong ya? @erlangganugraha @Arif9878

**Comment by alifianif** [comment]
katanya sementara gapapa diset default aja. Jadi ini udah oke ya 
cc @erlangganugraha
