### ISSUE TITLE
Import Data Excel Ke Laporan Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#172]
## Prototypenya
https://www.figma.com/proto/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=5464%3A14331&viewport=842%2C295%2C0.10734158009290695&scaling=scale-down-width

## Desain
https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=5800%3A14699

### Page List Kasus
- [ ] Terdapat button "import"

### Pop Up Fom Upload File Excel + Panduan
Terdapat 2 tab menu sbb :
1. Import
   - [x] Section untuk mendownload template excel
   - [x] Kolom Add File
   - [ ] Button Import Data berfungsi sebagai :
      - [x] Mengextract data dari excel kedalam database
      - [x] Mengenerate kode kasus
      - [x] Memvalidasi data
      - [x] Jika terdapat salah satu kesalahan baris data maka muncul alert bahwa data harus diperbaiki
      - [ ] Jika import data berhasil maka muncul alert "Import file terlah berhasil" 
2. Panduan
   - [x] Isiannya cara mengunakan fitur import

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by firmanJS** [comment]
di schema kasus ada tambahan kolom name_case_related jadi selain id kasus terkait menyimpan juga nama kasus terkaitnya
@khihadysucahyo  nanti ketika import excell jangan lupa tambahin
untuk template excell nya disatuin dalam satu kolom contoh kolom id kasus terkait value = idkasus - nama kasus
id kasus di simpen di kolom id_case_related
nama kasus di simpen di kolom name_case_related
tanda pemisah disesuaiin ajah

**Comment by khihadysucahyo** [comment]
@firmanJS Oke siap kang firman, sudah disesuikan ya kang.

**Comment by firmanJS** [comment]
@khihadysucahyo di japri aja ke erlangga atau mas rizal takutnya ga baca github

**Comment by alifianif** [comment]
@erlangganugraha ini juga kayanya perlu AC untuk gambaran sebelum ada desainnya

**Comment by alifianif** [comment]
1. Sedikit saran, untuk link download template langsung saja ke link downloadnya, jangan ke link google drivenya agar tidak membingungkan user
2. Fungsi drag file ke Add File tidak berfungsi, muncul validasi "File Gagal Diupload! Sistem hanya menerima file dengan format .xlsx" padahal format file sudah sesuai.
3. Alert berhasil import kurang pas karena ada kata yang terpotong
![validasi import success](https://user-images.githubusercontent.com/17422311/79936922-d907bf80-8482-11ea-8fe9-3e8875be1817.PNG)
4. Ketika data sudah exist, muncul error 400 bersamaan dengan Alert data sudah exist. Sebaiknya tidak ada warning error 400
![error 400](https://user-images.githubusercontent.com/17422311/79936988-f8065180-8482-11ea-9324-292275f35962.PNG)

**Comment by khihadysucahyo** [comment]
Ini template yang terakhir ya, kalau mau edit/nambah pakai yang ini aja, nuhun.
[Template Data Pelaporan Kasus.xlsx](https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/files/4520116/Template.Data.Pelaporan.Kasus.xlsx)
cc: @erlangganugraha @naufalihsank

**Comment by khihadysucahyo** [comment]
Untuk kolom kasus terkait, pemisahnya abis aku edit dari tanda "-" ke  "|"
soalnya id kasus terkait udah contain tanda "-" (covid-3423424)
![image](https://user-images.githubusercontent.com/31666194/80073539-2020ae00-8572-11ea-9708-8bf56967d769.png)
