### ISSUE TITLE
[Management User] Create User Faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#174]
## Desain
link figma : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=5902%3A0

## Acceptance Criteria :
- [x] Terdapat kolom penginputan, sbb :
- [x] username
- [x] fullname
- [x] email
- [x] no telepon
- [x] alamat
- [x] password
- [x] ketik ulang password
- [x] roles

- [x] Terdapat button "Buat Akun" yg berfungsi menyimpan data akun yang dibuat
- [x] Username tidak bisa menggunakan spasi, hanya bisa huruf dan angka
- [x] Terdapat validasi username, Jika username sudah digunakan maka muncul alert "Username telah digunakan"

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by alifianif** [comment]
@erlangganugraha sama yg ini minta AC er

**Comment by erlangganugraha** [comment]
kang @firmanJS ada penambahan AC, field roles dimasukin form input

**Comment by shintadewiaw** [comment]
paginationnya belum ya mas?aku tambah data ga muncul @Arif9878

**Comment by Arif9878** [comment]
paginationnya ada di card list sin

**Comment by shintadewiaw** [comment]
**Feedback** @Arif9878 

1. Ubah redaksi:
	- Alamat Tempat Tinggal ---> Alamat
	- Alamat Lengkap Tempat Tinggal ---> Alamat Lengkap

2. Data yang baru dibuat muncul paling atas (nomor 1)

**Comment by alifianif** [comment]
Mau nambahin, ada cara ga ya kenapa di saya listnya jadi kepotong gini?

![kepotong](https://user-images.githubusercontent.com/17422311/79960939-39612600-84b0-11ea-8791-da18353614b7.PNG)

@Arif9878

**Comment by alifianif** [comment]
mas @Arif9878 kenapa validasi konfirmasi password tetap muncul meskipun isinya sudah benar ya? Saya jadi gabisa create user.

![image](https://user-images.githubusercontent.com/17422311/80055189-4a12aa00-854b-11ea-9585-36be7b72e9bb.png)

**Comment by Arif9878** [comment]
ok done lif

**Comment by shintadewiaw** [comment]
Tiap simpan muncul toast itu mas + feedback aku yang diatas belum ya @Arif9878 
![image](https://user-images.githubusercontent.com/63390998/80057689-6c0f2b00-8551-11ea-9249-dd66f3a76382.png)

**Comment by Arif9878** [comment]
@shintadewiaw Validasi username dan email udah di formnya bukan saat save, klu error itu aku tanyain dulu sama kang firman

**Comment by shintadewiaw** [comment]
mas firman yang toast udah di cek? @firmanJS

**Comment by firmanJS** [comment]
@shintadewiaw sudah aman ko

**Comment by shintadewiaw** [comment]
belum mas masih euy aku test di dinkeskotabanjar, udah pake incognito

**Comment by alifianif** [comment]
![image](https://user-images.githubusercontent.com/17422311/80072247-2c0b7080-8570-11ea-88cf-0eda7c16173e.png)
 belum mas, masih ada @firmanJS
