### ISSUE TITLE
[Tambahan] Input Kasus untuk Id Kasus Terkait & List Negara WNA

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#177]

**Comment by firmanJS** [comment]
@naufalihsank untuk api negara bisa ambil pake yang ini aja dari luar 
https://restcountries.eu/rest/v2/all

yang dikirim ketika simpan di menu kasus name negara nya

**Comment by naufalihsank** [comment]
@firmanJS siap kang

**Comment by firmanJS** [comment]
@naufalihsank ini untuk list id terkait api/cases-listid

**Comment by firmanJS** [comment]
@naufalihsank tambahin nama kasus terkait ya ketika post save jadi yang dikirim frontend id kasus terkait sama nama kasus terkait nya name_case_related

**Comment by saktiperdana** [comment]
Mang @JDS Erlangga ini id kasus yang di hide cuma ID Kasus + ID Kasus terkait ?
ID kasus Pusat kalau kita ga isi kan dia ttp muncul otomatis? ga sekalian di hide juga?

**Comment by alifianif** [comment]
Ini tentang API List Negara WNA kan ya di form input? kalo iya, mau saya pindahin ke done. cc @firmanJS 

btw mas @saktiperdana kayanya salah komen hrsnya di card sebelah kalo yg ngehide ID kasus hehe

**Comment by firmanJS** [comment]
@alifianif iya lif
