### ISSUE TITLE
[Tambahan] ID kasus dihide diform inputan & list kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#180]

**Comment by alifianif** [comment]
Ini ada saran untuk ngehide ID Kasus Pusat juga diform inputan karena terisi otomatis. Kira-kira bisa di acc ga ya? Kalau iya, mau dilanjut di card ini atau bikin card baru? @erlangganugraha

**Comment by shintadewiaw** [comment]
Ini ID kasus yang di detail sama di edit ga sekalian di hide? @erlangganugraha

**Comment by saktiperdana** [comment]
up up
ID Kasus Pusat, ga sekalian di hide aja ?

@erlangganugraha
