### ISSUE TITLE
[Dashboard] Penambahan Status OTG

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#187]
**Expected Result**: Penambahan Status OTG pada Page List Kasus & Dashboard Laporan Kasus

**Checklist**
- [x] Penambahan total jumlah OTG pada Dashboard

- [x] Penambahan total jumlah OTG pada Dashboard List Kasus

- [x] Perhitungan OTG benar

**Comment by shintadewiaw** [comment]
mas, ini yang di kerjain yang di list kasus doang bukan? @Arif9878 @firmanJS

**Comment by Arif9878** [comment]
ada nanti di dashboard sin, ku pindah ke in progress aja
