### ISSUE TITLE
[Management User] List User

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#194]
## Desain
link figma : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=5902%3A0

## Acceptance Criteria :
- [x] Terdapat button "Tambah User" yg berfungsi direct ke form create user
- [ ] Terdapat pencarian berdasarkan nama, username, no telepon
Terdapat kolom, sbb :
- [x] username
- [x] fullname
- [x] email
- [x] no telepon
- [x] alamat
- [ ] Aksi 
  - [x] Lihat Detail
  - [ ] Reset Password
  - [x] Edit User
  - [x] Hapus User
- [ ] Terdapat sorting disetiap kolom
- [x] Terdapat pagination

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas pagination belum? @Arif9878

**Comment by Arif9878** [comment]
![Screen Shot 2020-04-23 at 12 31 07](https://user-images.githubusercontent.com/20775950/80062601-56ecc900-855e-11ea-98cf-f5b4c0930b22.png)
ada sin

**Comment by Arif9878** [comment]
owh sama tambahan satu lagi Reset Password itu untuk superadmin kyaknya

**Comment by alifianif** [comment]
superadmin tuh sama kaya dinkesprov ga mas? @Arif9878

**Comment by shintadewiaw** [comment]
eh btw, dinkeskotakab kok bisa ngebikin user dinkesprov? @erlangganugraha @Arif9878

**Comment by alifianif** [comment]
oiya sama ini AC-nya sampe ada filter dan search ya? berarti ini masih blm selesai ya

@Arif9878 @erlangganugraha

**Comment by Arif9878** [comment]
@alifianif  filter dan search buat card baru aja lif, di desain juga belum ada
