### ISSUE TITLE
[Input Kasus] Validasi format NIK

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#195]
Validasi format by :
- [x] 16 digit
- [x] Karakter awal dan akhir tidak 0
- [x] 2 karakter awal ada kode prov resmi
- [x] Only Number

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/79944176-1117fe00-8495-11ea-9442-8a3b88ad72d0.png)
kang @erlangganugraha yang 2 karakter awal harus kode provinsi berarti pilihan 2 karakter awalnya yang ini ya ?

**Comment by erlangganugraha** [comment]
iya betul 32 @naufalihsank

**Comment by naufalihsank** [comment]
@erlangganugraha kalo yg ktp selain 32 tapi diinput di sistem kita gmn kang ?
