### ISSUE TITLE
[Input Kasus] Validasi NIK yg diinputkan sama

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#196]
## Acceptance Criteria
**Functional :**
- [x] Mengecek NIK yang sudah terdata dilaporan kasus

**Output :**
- [x] Menampilkan Pesan : "NIK [value NIK] atas nama [value nama kasus] sudah terdata dikasus oleh [value author]"

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
@erlangganugraha  kalau nik sudah terdata dan statusnya deleted, tetap dianggap belum terdata kan? tetap input baru?

**Comment by khihadysucahyo** [comment]
@erlangganugraha sama untuk validasi nik,
ada pertimbangan setiap kota/kabupaten boleh punya nik yang sama ga?

**Comment by erlangganugraha** [comment]
betul mas, tetap belum terdata jika sudah statusnya deleted,
ga boleh ada nik yg sama, jadi ga ada pertimbangan setiap kota/kabupaten boleh punya nik yang sama

**Comment by naufalihsank** [comment]
@erlangganugraha kang untuk yg ini validasinya pas submit berarti ato pas ketik di field NIK nya ? ato pas lanjutkan ?

**Comment by erlangganugraha** [comment]
flownya samakan dgn yg require, jadi saat klik lanjutkan @naufalihsank
