### ISSUE TITLE
Merubah kata "import" & "export" menjadi "impor" & "ekspor"

### ISSUE THREAD

**Issue by ganjarsetia** [jabardigitalservice/pikobar-pelaporan-frontend#198]
Saya udah diskusi dengan Erlangga mengenak kamus kata export & import. Hasilnya diubah menjadi menjadi "impor" & "ekspor". Ganti teksnya di dictionary

**Comment by shintadewiaw** [comment]
@ganjarsetia @Arif9878 i

**Comment by ganjarsetia** [comment]
Setelah diskusi dengan @shintadewiaw katanya udah berubah. Saya close
