### ISSUE TITLE
[Approval] List Verifikasi Kasus Baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#220]
## Desain
![Daftar Kasus Verifikasi](https://user-images.githubusercontent.com/11548871/80359245-bec94980-88a7-11ea-94a6-ec32c5d01e76.png)

Link Figma : 
https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=6178%3A279

Flow :
![Screenshot_2020-04-27 Rekomendasi Alur Verifikasi List Kasus dari Faskes](https://user-images.githubusercontent.com/11548871/80355130-e3222780-88a1-11ea-8ea7-dc3f0bb931ff.png)

## Acceptance Criteria :
- [x] Terdapat section info "Data akan otomatis terverifikasi jika 24 jam tidak ada aksi"
- [x] Terdapat sorting setiap kolom
- [x] Terdapat filter berdasarkan :
   - [x] Sumber Pelapor -> isinya list faskes berdasarkan dinkesnya
   - [x] Kriteria -> isinya status ODP,dll
   - [x] Alamat pasien -> kota, kec, kelurahan 
- [ ] Pencarian berdasarkan NIK, Nama, Sumber Pelapor
- [x] Terdapat list table verifikasi baru
- [x] List Verifikasi kasus diurutkan berdasarkan batas verifikasi
- [x] Terdapat pagination
- [x] Rows by default 30 rows

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
existing verified_status [pending, declined, verified]

list kasus baru (filter disesuiakn untuk di list kasus verified)
GET {{host}}/api/cases?verified_status=pending

export juga minta tolong disesuikan untuk ditambahkan filter verified
GET {{host}}/api/cases-export?verified_status=verified

approvals
GET  {{host}}/api/cases/{id_case}/verifications
POST {{host}}/api/cases/{id_case}/verifications
request payload: 
{
  "verified_status": "verified", /* [verified, declined] */
  "note": "string optional" 
}

untuk auto approval 24hours udah jalan, tapi perlu diskusi untuk reactivity di fe nya.

**Comment by alifianif** [comment]
1. Kolom search tidak bisa digunakan untuk mencari sumber pelapor
2. Ini dinkes tidak bisa melihat detail? Kalau demikian, bagaimana caranya dinkes dapat mengetahui ada data yang tidak lengkap seperti di alur verifikasi data di atas?

@erlangganugraha @Arif9878

**Comment by khihadysucahyo** [comment]
@erlangganugraha pada  kolom search untuk mencari sumber pelapor, itu berdsarkan kolom sumber laporan atau author username? , di table list field pelapor itu diambil dari author username.

**Comment by erlangganugraha** [comment]
berdasarkan author mas @khihadysucahyo
