### ISSUE TITLE
[Management User] Filter dan Search di List User

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#222]
## User Story
Sebagai dinkes saya ingin memfilter & mengurutkan list user sehingga saya bisa untuk memilih data sesuai data yang disaring & disorting yang diinginkan

## Mockup
link figma 

## Acceptance Criteria :

- [x] Terdapat pencarian berdasarkan username, nama, email, no telepon, alamat
- [x] Terdapat dilfilter berdasarkan :
     - [x] Alamat
     - [x] Hak akses (hanya untuk dinkesprov)
- [x] Terdapat sorting disetiap kolom kecuali kolom No & Aksi

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by alifianif** [comment]
udah dibikin cardnya ya mas arip @Arif9878 , sekalian @erlangganugraha minta desain untuk filter dan search di list user management

**Comment by firmanJS** [comment]
@alifianif mau tanya maksud nya alamat tuh alamat aja contoh `jalan maulana yusuf ` aja tidak bersama kecamatan dan kelurahan kan ?

**Comment by alifianif** [comment]
@firmanJS kayanya alamat kaya kota/kab, kecamatan, kelurahan deh mas. Kaya di form tambah pengguna
![image](https://user-images.githubusercontent.com/17422311/80565932-ee00c780-8a1b-11ea-8e41-5e830a898b03.png)

**Comment by alifianif** [comment]
ini tinggal filter berdasarkan hak aksesnya ya mas yang belum @Arif9878 @firmanJS

**Comment by Arif9878** [comment]
@alifianif hak akses skrang masih untuk dinkes provinsi lif

**Comment by alifianif** [comment]
oh gitu... okedeh sip @Arif9878
