### ISSUE TITLE
[Kelola Pengguna] Format Alamat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#228]
**Perubahan Format Alamat**: [Alamat Lengkap] [Kecamatan] [Kelurahan] [Kota]

Contoh: Jl. Riung Utara Blok A-3 No. 595, Langensari, Banjaran, Kota Banjar

**Comment by shintadewiaw** [comment]
mas @Arif9878 kalau alamat lengkap ga diisi gausah tampilin (,) nya

![image](https://user-images.githubusercontent.com/63390998/80449813-4a93b200-894a-11ea-8013-e278e7a98a3e.png)

**Comment by Arif9878** [comment]
@shintadewiaw coba test lagi sin itu
