### ISSUE TITLE
[Management User] Field Mandatory Telepon dan Alamat tidak berfungsi

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#237]
Step to reproduce:
1. Menambahkan Pengguna tanpa menginputkan nomor telepon dan alamat hanya dengan default KOTA BANDUNG (kedua field tersebut bertanda bintang)
2. Halaman dialihkan ke list management user
3. Muncul alert 
![image](https://user-images.githubusercontent.com/17422311/80566625-9bc0a600-8a1d-11ea-9477-2b5a7efae680.png)
4. Data tidak masuk ke dalam list

**Comment by alifianif** [comment]
mas @Arif9878 kejadian lagi ini ketahan di kolom ulangi password jadi gabisa disimpan datanya padahal udah diisi dan sesuai dengan kolom password :(
![image](https://user-images.githubusercontent.com/17422311/80593964-510a5280-8a4c-11ea-9451-808d8e284973.png)

**Comment by Arif9878** [comment]
![Screen Shot 2020-04-29 at 20 01 43](https://user-images.githubusercontent.com/20775950/80598942-4fdd2380-8a54-11ea-929e-dfc393ab4dba.png)
![Screen Shot 2020-04-29 at 20 01 55](https://user-images.githubusercontent.com/20775950/80598956-5370aa80-8a54-11ea-8e1b-65ff950bcf31.png)


di aku normal lif @alifianif

**Comment by shintadewiaw** [comment]
mas @Arif9878 username pake underscore belum di handle ya?
Step to Reproduce:
1. Tambah data tanpa mengisikan nomor telepon & alamat
2. Username tidak mengandung spasi tetapi underscore

![image](https://user-images.githubusercontent.com/63390998/80676193-7183ec80-8ae0-11ea-8ab6-08a199cbb629.png)

**Comment by Arif9878** [comment]
@erlangganugraha ke ini orang sin @shintadewiaw

**Comment by erlangganugraha** [comment]
untuk username boleh pake underscore tetapi kalo space itu ga boleh @alifianif @shintadewiaw @Arif9878

**Comment by shintadewiaw** [comment]
masih error mas @Arif9878 

Ini data yang aku masukin:
![image](https://user-images.githubusercontent.com/63390998/80685784-e6abed80-8af1-11ea-81d3-a1c7d8f77573.png)


Ini errornya:
![image](https://user-images.githubusercontent.com/63390998/80685602-a3ea1580-8af1-11ea-9809-b42e7eb9d1af.png)
