### ISSUE TITLE
[Approval] Penyesuaian Input kasus baru dari faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#238]
## Acceptance Criteria :
Sama dengan input kasus seperti dinkes kota/kab, tetapi ada ketentuan sbb :
- [x] Field sumber pelaporan diisi otomatis dari nama lengkap faskesnya
- [x] ID kasus digenerate dgn kodifikasi sbb :
PRECOVID => Kode kasus yg berlum terverifikasi
10 => kode provinsi
01 => kode dinkes kota/kab
20 => tahun
00001 => no urut *5 digit

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by khihadysucahyo** [comment]
@erlangganugraha mau tanya, di db kalo collection namingnya dari approvals aku ganti jadi verifications gimana?
soalnya yg exixting sekarang itu pakai verified_status

**Comment by erlangganugraha** [comment]
ini mh perlu diskusi sama BE yg lain @khihadysucahyo , khususnya kang @sandisunandar99 
mangga disepakati bareng2, yang penting Field sumber pelaporan diisi dengan nama lengkap faskesnya

**Comment by sandisunandar99** [comment]
Tadi sudh diskusi sih.. slama sistem probisnya ga berubah mah ga masalah, cuman nanti @khihadysucahyo kasih komen di kodingan nya.. biar smua orng paham itu buat apa.. soalnya kan baru..

Sipsip..
