### ISSUE TITLE
[List Kasus] Sorting tidak berfungsi untuk keseluruhan data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#249]
- [x] Sorting seharusnya berlaku untuk seluruh data, bukan hanya per-page. Saat ini, sorting hanya berlaku di satu halaman saja, tidak menyortir keseluruhan data

**Comment by alifianif** [comment]
Seharusnya kalau sortingnya sudah berfungsi untuk keseluruhan data, nama "Zulkifli" seharusnya ada di halaman paling akhir (saya sort A-Z), tapi ini malah ada di halaman pertama.
![image](https://user-images.githubusercontent.com/17422311/81150728-7c3ff500-8faa-11ea-9ab2-423fba487222.png)
Dan di halaman terakhir data terakhirnya malah Yunny. Dan di setiap halaman selanjutnya diawali dari huruf 'A' lagi, padahal harusnya melanjutkan dari depan saja urutannya.
![image](https://user-images.githubusercontent.com/17422311/81150828-94177900-8faa-11ea-8407-1e75cc189939.png)
@Arif9878

**Comment by shintadewiaw** [comment]
Setelah A kok nyempil D, E, S, T ?

![sorting](https://user-images.githubusercontent.com/63390998/81382624-e38baf80-9138-11ea-9621-bce63228a518.png)

@Arif9878

**Comment by Arif9878** [comment]
@firmanJS mang sorting nama ascending ada yang nyempil

**Comment by Arif9878** [comment]
@shintadewiaw udah sin

**Comment by shintadewiaw** [comment]
@Arif9878  @firmanJS masih kaka

![image](https://user-images.githubusercontent.com/63390998/81527979-d6afcb80-9385-11ea-86ca-9b5fccc095bf.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 @firmanJS 
kan filter A-Z & Z-A, ini apaan ya?

![image](https://user-images.githubusercontent.com/63390998/81534915-0dd8a980-9393-11ea-8000-013797ad13ca.png)

**Comment by Arif9878** [comment]
sorting sin bukan filter @shintadewiaw

**Comment by shintadewiaw** [comment]
eh iya sorting maap

**Comment by shintadewiaw** [comment]
eh iya maksutnya sorting, cobain deh sortingnya ada 3 mas @Arif9878

**Comment by Arif9878** [comment]
sorting 3 gimana sin?
