### ISSUE TITLE
[Input Kasus] Penambahan pilihan dibagian kolom lokasi saat ini

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#250]
## Acceptance Criteria

- [x] Terdapat pilihan "Tempat Lainnya"
- [x] Terdapat dropdown list Tempat lainnya
- [x] Data yang ada list dropdown isinya RS diluar jawa barat maupun tempat yg belum terdata 

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by khihadysucahyo** [comment]
@sandisunandar99 @firmanJS @azophy di collection hospital untuk ngebedain RS ada di jabar atau luar jabar dari mana ya? kemendagri_kabupaten_code kah, saolnya ada yang ga ada prop kemendari_kabupaten_code nya
