### ISSUE TITLE
[Input Kasus] Penambahan Kolom Kondisi Penyerta

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#251]
## Referensi
![Screenshot_2020-05-01 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf](https://user-images.githubusercontent.com/11548871/80816834-72a93c80-8bfa-11ea-9a97-8a65851f6904.png)

## Desain
Menunggu kang @ReksaMohammad membuat desainnya

## Acceptance Criteria

- [x] Format isian dibuat checkbox seperti kolom gejala
Checklist kondisi penyerta sbb :

1. Hamil
2. Diabetes
3. Penyakit jantung
4. Hipertensi
5. Keganasan
6. Gangguan Imunologi
7. Gagal ginjal kronis
8. Gagal hati kronis
9. PPOK
10. Lainnya Jika ada (dibuat free text)

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by ReksaMohammad** [comment]
monggo di cek https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4423

**Comment by erlangganugraha** [comment]
sepertinya itu desain baru, tp biar mempercepat pengerjaan sementara kolom kondisi penyerta ditaro diatas catatan tambahan. Catatan tambahan dipaling bawah
![asasdfsdfsdf](https://user-images.githubusercontent.com/11548871/80908056-ccb71880-8d46-11ea-97c2-c7db27ccbf81.JPG)

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/80908178-fcb2eb80-8d47-11ea-9a3d-011344d94ea9.png)
@erlangganugraha sementara yg udah jadi kyk gini kang, mau dipindah ke atas Catatan Tambahan aja ?

**Comment by erlangganugraha** [comment]
dipindah kang @naufalihsank , karena yg grid kiri spacenya msh kosong

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/80908329-3506f980-8d49-11ea-84bd-019804f82679.png)
@erlangganugraha kayak gini ya kang

**Comment by erlangganugraha** [comment]
mantaap kang, gaskeun @naufalihsank

**Comment by alifianif** [comment]
punten er, kalo kondisi penyerta ini bakal tampil di list mana ya? Di ekspor kah? soalnya di excel ekspor blm ada kolom "Kondisi Penyerta" ini @erlangganugraha

**Comment by alifianif** [comment]
Update: Kondisi penyerta akan ditambahkan di detail dan ekspor, tapi dibuat di card terpisah. Jadi ini done ya
