### ISSUE TITLE
[Approval] Verifikasi laporan data kasus baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#255]
## Flow :
![Screenshot_2020-04-27 Rekomendasi Alur Verifikasi List Kasus dari Faskes](https://user-images.githubusercontent.com/11548871/80355130-e3222780-88a1-11ea-8ea7-dc3f0bb931ff.png)

## Roles User
1. Dinkes Kota/kab hanya bisa memverifikasi data kasus dari faskes diareanya (district)

> dihold 2. Dinkes Prov bisa memverifikasi data kasus dari faskes yang diluar kelola oleh dinkes kota/kab

## Acceptance Criteria :

- [x] Diverifikasi oleh dinkes daerah (kota/kab)
- [x] Pop up show page detail data kasus untuk validasi data
- [x] Terdapat 2 button dibagian footer, sbb :
   - [x] 1. Button Verifikasi -> utk memverifikasi
   - [x] 2. Button Tolak -> show input alasan

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by khihadysucahyo** [comment]
# API
* **verified_status [pending, declined, verified]**

* **To create verification logs and trigger changes `verified_status` in cases based on `id_case`**
**POST** `{{host}}/api/cases/{id_case}/verifications`
request payload: 
```
{
  "verified_status": "verified", /* [pending, verified, declined] */
  "note": "string optional" 
}
```

**Comment by erlangganugraha** [comment]
kang @ReksaMohammad untuk desain pop upnya ditunggu yah

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/80951608-669fc380-8e22-11ea-8f11-45768de90ea7.png)

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/81135588-fe1c2800-8f82-11ea-8d17-0eae25660e4f.png)

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/81139439-02027700-8f90-11ea-83f0-f1d99dbbce90.png)

**Comment by alifianif** [comment]
1. Jika tanggal lahir tidak diisi maka kolom tertulis "Invalid Date", seharusnya dikosongkan saja @naufalihsank 
![image](https://user-images.githubusercontent.com/17422311/81367406-57b55b80-9117-11ea-8dd6-a3b29c8f7af9.png)
2. Kolom Kondisi Penyerta juga tidak ditampilkan di detail ini ya? @erlangganugraha @naufalihsank 
![image](https://user-images.githubusercontent.com/17422311/81367435-70257600-9117-11ea-9c68-211f642a4d63.png)

**Comment by naufalihsank** [comment]
@alifianif yang nomer 1 udah dibenerin teh bisa dicoba lagi. Kalo yang nomer 2 aku kurang tau soalnya emg di desainnya gaada kolom itu
