### ISSUE TITLE
[Dashboard] Section disclaimer data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#256]

**Comment by ReksaMohammad** [comment]
Artboard: https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4423

Prototype: https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5%3A4427&viewport=581%2C-4484%2C0.5522271394729614&scaling=min-zoom
