### ISSUE TITLE
[Laporan Harian] Desain page laporan harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#257]

**Comment by ReksaMohammad** [comment]
link laporan harian figma : https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=249%3A3227

**Comment by ReksaMohammad** [comment]
<img width="839" alt="Screen Shot 2020-05-08 at 12 44 40" src="https://user-images.githubusercontent.com/42407562/81374556-b8e62a80-9129-11ea-934f-ca0d97c7a366.png">
