### ISSUE TITLE
[List Kasus] Filter tidak berfungsi saat berada pada halaman (selain 1)

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#283]

**Comment by shintadewiaw** [comment]
mas @Arif9878  kok balik gabisa lagi ya? apa kesenggol?

![image](https://user-images.githubusercontent.com/63390998/81383511-5b0e0e80-913a-11ea-8fc4-25d0e9ac3911.png)

**Comment by Arif9878** [comment]
![Screen Shot 2020-05-08 at 15 03 57](https://user-images.githubusercontent.com/20775950/81385252-39faed00-913d-11ea-8f5a-57034f343db7.png)
![Screen Shot 2020-05-08 at 15 04 06](https://user-images.githubusercontent.com/20775950/81385263-3e270a80-913d-11ea-9273-9c967d20aee2.png)

di list kasus bisa 
itu di verifikasi kasus sin?

**Comment by shintadewiaw** [comment]
di list kasus juga mas, ih naha ya kadang bisa kadang engga wkwkwk
sekarang udah bisaa

**Comment by shintadewiaw** [comment]
ku closed dulu aja ya mas @Arif9878

**Comment by shintadewiaw** [comment]
@alifianif lip bantuin coba lip, kalo bisa langsung close aja ya
