### ISSUE TITLE
[List Kasus Faskes] Perbaikan list kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#285]
## Desain
![Flow Pelaporan - daftar menunggu verifikasi di fasyankes](https://user-images.githubusercontent.com/11548871/81520562-e40d8b80-936e-11ea-8923-c5577d39ca45.png)

### Roles faskes :
- [x] Menu diganti menjadi "List Verifikasi Kasus"
- [x] Tambahkan section desclaimer "Data yang berhasil diverifikasi akan hilang otomatis setelah 24 jam. Anda dapat melihat data yang terverifikasi pada 'List Kasus'"
- [x] Terdapat tab filter sbb :
   - [x] 1. Semua
   - [x] 2. Menunggu diverifikasi
   - [x] 3. Data Kasus Ditolak
- [x] Tambahkan tanggal input
- [x] Dihilangkan kolom Batas Verifikasi Otomatis
- [x] Tambahkan button aksi Hapus *jika belum terverifikasi
- [x] Tambahkan button aksi Lihat Detail

**Comment by naufalihsank** [comment]
![image](https://user-images.githubusercontent.com/56071566/81393359-6e28da80-914a-11ea-8208-4a9290299d67.png)
Sementara jadi kayak gini, ada tambahan lagi kang ? @erlangganugraha

**Comment by ganjarsetia** [comment]
@erlangganugraha ini saya improve yah soal tampilan waktu **BATAS VERIFIKASI OTOMATIS** 
dengan library MomentJS, kalimat sisa jam, menit, & detik bakal muncul otomatis
Contoh seperti ini:

jika diatas 21 jam < 24
![image](https://user-images.githubusercontent.com/3258090/81476468-4a45c180-923c-11ea-8872-b5c127057023.png)

![image](https://user-images.githubusercontent.com/3258090/81476495-6b0e1700-923c-11ea-8bec-d2320c9a8fec.png)

![image](https://user-images.githubusercontent.com/3258090/81476507-7cefba00-923c-11ea-93dc-27adcb0556c1.png)

![image](https://user-images.githubusercontent.com/3258090/81476522-8d079980-923c-11ea-92e1-ec15779b20a7.png)
