### ISSUE TITLE
[List Verifikasi Kasus] Hapus Update Profil dan Update Riwayat dari list Verifikasi

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#301]

**Comment by Arif9878** [comment]
@alifianif ini task gimana ya lif?

**Comment by alifianif** [comment]
Eh ini kayanya udah deh, jadinya munculnya sesuai statusnya seperti yang dibilang erlangga kemarin. Langsung aku close aja ya mas @Arif9878
