### ISSUE TITLE
[Dashboard] Perbaikan skala sumbu X pada grafik umur dan jenis kelamin

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#302]
- [ ] skala sumbu x disesuaikan dengan total inputan agar rata sumbu kanan dan kirinya
- [ ] Perhitungannya tetap hitungan positif aktif

**Comment by shintadewiaw** [comment]
mas @rendiriz perhitungan jumlah positif aktifnya masih salah

![image](https://user-images.githubusercontent.com/63390998/81644350-bf3e1480-9451-11ea-9723-34270be62e57.png)

![image](https://user-images.githubusercontent.com/63390998/81644394-d4b33e80-9451-11ea-8099-508677929da5.png)

**Comment by rendiriz** [comment]
@firmanhxc @sandisunandar99

**Comment by rendiriz** [comment]
@firmanJS @sandisunandar99

**Comment by sandisunandar99** [comment]
@alifianif @shintadewiaw test nya jangan hanya login pake 1 dinkes aja ya,, kalo bisa coba sampe 3 atau 10 dinkes berbeda,, soalnya ada beberapa kondisi dimana data nya anomali jadi ke perhitungan dashboard sama di list beda

**Comment by firmanJS** [comment]
@alifianif yup ini karena datanya ada yang anomali fungsionalitas aplikasi udah berjalan normal sih
