### ISSUE TITLE
[Dashboard] Diagram Angka Harian & Kumulatif dari Kriteria/Status

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#307]
## User Story
Sebagai dinkes saya ingin melihat statistik baik itu agregat hariannya ataupun kumulatif sehingga saya chart ini bisa dijadikan salah satu untuk membuat keputusan penanganan ataupun perencanaan tentang wabah ini 

## Mockup
![Screenshot_2020-04-29 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/80515992-01c11500-89ad-11ea-877f-b24c5a33f5b6.png)

![Screenshot_2020-04-29 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/80515986-fff75180-89ac-11ea-9d87-4ed52421f884.png)

#### 1. Angka Harian OTG
- [x] OTG dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [x] Sumbu X (Tanggal) diset 14 hari
- [x] Ketentuan perhitungan OTG
  - [x] 1. Proses = Count status OTG dengan tahapan proses
  - [x] 2. Selesai = Count status OTG dengan tahapan selesai
  - [x] 3. Total = Count status OTG dengan tahapan proses + selesai
- [x] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 2. Angka Harian ODP
- [x] ODP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [x] Sumbu X (Tanggal) diset 14 hari
- [x] Ketentuan perhitungan ODP
  - [x] 1. Proses = Count status ODP dengan tahapan proses
  - [x] 2. Selesai = Count status ODP dengan tahapan selesai
  - [x] 3. Total = Count status ODP dengan tahapan proses + selesai
- [x] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 3. Angka Harian PDP
- [x] PDP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [x] Sumbu X (Tanggal) diset 14 hari
- [x] Ketentuan perhitungan PDP
  - [x] 1. Proses = Count status PDP dengan tahapan proses
  - [x] 2. Selesai = Count status PDP dengan tahapan selesai
  - [x] 3. Total = Count status PDP dengan tahapan proses + selesai
- [x] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total
 
#### 4. Angka Harian Positif
- [x] Positif dengan legenda : Aktif, Sembuh & Meninggal, yang dimana sumbu X adalah tanggal & sumbu Y adalah angka
- [x] Sumbu X (Tanggal) diset 14 hari
- [ ] Ketentuan perhitungan Positif
  - [x] 1. Aktif = Count status Positif dengan tahapan proses
  - [x] 2. Sembuh = Count status Positif yang hasilnya sembuh & tahapannya selesai
  - [x] 3. Meninggal = Count status Positif yang hasilnya meninggal & tahapannya selesai
  - [ ] 4. Total = Count status Positif dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Aktif, Total Sembuh, Meninggal, Grand Total

#### 1. Kumulatif OTG
- [x] OTG dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan OTG
  - [x] 1. Proses = Count status OTG dengan tahapan proses
  - [x] 2. Selesai = Count status OTG dengan tahapan selesai
  - [ ] 3. Total = Count status OTG dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 2. Kumulatif ODP
- [x] ODP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan ODP
  - [x] 1. Proses = Count status ODP dengan tahapan proses
  - [x] 2. Selesai = Count status ODP dengan tahapan selesai
  - [ ] 3. Total = Count status ODP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total

#### 3. Kumulatif PDP
- [x] PDP dengan legenda : Proses & Selesai, yang dimana sumbu X adalah tanggal & sumbu Y adalah  angka
- [ ] Ketentuan perhitungan PDP
  - [x] 1. Proses = Count status PDP dengan tahapan proses
  - [ ] 2. Selesai = Count status PDP dengan tahapan selesai
  - [ ] 3. Total = Count status PDP dengan tahapan proses + selesai
- [ ] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Selesai, Total Proses, Grand Total
 
#### 4. Kumulatif Positif
- [x] Positif dengan legenda : Aktif, Sembuh & Meninggal, yang dimana sumbu X adalah tanggal & sumbu Y adalah angka
- [ ] Ketentuan perhitungan Positif
  - [ ] 1. Aktif = Count status Positif dengan tahapan proses
  - [ ] 2. Sembuh = Count status Positif yang hasilnya sembuh & tahapannya selesai
  - [ ] 3. Meninggal = Count status Positif yang hasilnya meninggal & tahapannya selesai
  - [x] 4. Total = Count status Positif dengan tahapan proses + selesai
- [x] Terdapat pop up/title ketika dihover bar chartnya yang memunculkan Tanggal, Total Aktif, Total Sembuh, Meninggal, Grand Total

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
**Feedback Angka Harian**

- [ ] 1. Sumbu X (Tanggal) diset 14 hari ----> Saat ini 15 hari

- [ ] 2. Perhitungan positif aktif masih salah (positif aktif=proses)


**Feedback Angka Kumulatif**

- [ ] 1. Tidak perlu menampilkan data yang isinya 0
- [ ] 2. Kumulatif Positif
     - [ ] Perhitungan positif aktif masih salah (positif aktif=proses)
     - [ ] Perhitungan status meninggal masih salah

**Comment by sandisunandar99** [comment]
@alifianif @shintadewiaw test nya jangan hanya login pake 1 dinkes aja ya,, kalo bisa coba sampe 3 atau 10 dinkes berbeda,, soalnya ada beberapa kondisi dimana data nya anomali jadi ke perhitungan dashboard sama di list beda

**Comment by alifianif** [comment]
@sandisunandar99 oke mas, saya cek ulang di dinkes2 lain

**Comment by shintadewiaw** [comment]
mas @sandisunandar99 ,data positif aktifnya masih ada yang ga sesuai, udah di cek di 2 dinkes
Ini kasus di dinkes cirebon

1. Data kasus ada 3 (2 kasus tanggal 1 mei & 1 kasus tanggal 9 mei)
![image](https://user-images.githubusercontent.com/63390998/81902869-0b708c80-95eb-11ea-8168-182a4708581f.png)

2. Data di dashboard tanggal 9 meinya ga muncul
![dinkes cirebon](https://user-images.githubusercontent.com/63390998/81902818-fb58ad00-95ea-11ea-8cbc-9c38fc6cd5e0.png)

**Comment by alifianif** [comment]
- **Kasus Dinkes Kota Cimahi**
1. di list terdapat lebih dari satu kasus pada 7 Mei, dan terdapat beberapa kasus pada bulan Mei yang positif tapi yang tampil pada diagram hanya 1 pada tanggal 7 dan yang lainnya tidak ditampilkan.
![image](https://user-images.githubusercontent.com/17422311/81905249-aae34e80-95ee-11ea-91c8-f75f37e8d409.png)
![image](https://user-images.githubusercontent.com/17422311/81905054-62c42c00-95ee-11ea-900e-0c10752861e9.png)

2. Pada screenshot ini saya sortir berdasarkan tanggal input tapi ternyata sortirnya juga belum benar karena saya sortir dari paling baru ke paling lama, tapi di tengah-tengah bulan April nyempil juga bulan Mei
![image](https://user-images.githubusercontent.com/17422311/81905370-d0705800-95ee-11ea-93ef-e33c48293492.png)

3. Di list terdapat 1 kasus PDP yang sudah selesai pada tanggal 8 Mei, tapi di dashboard kosong
![image](https://user-images.githubusercontent.com/17422311/81905800-76bc5d80-95ef-11ea-8b05-48a86540a5e3.png)
![image](https://user-images.githubusercontent.com/17422311/81905789-715f1300-95ef-11ea-988f-6fde9f52a743.png)


- **Dinkes Kab Bandung AMAN**


- **Kasus Dinkes Kota Bekasi**
1. Filter untuk tanggal 8 Mei tetapi yang muncul sebagai hasil filter adalah inputan tanggal 9 Mei
![image](https://user-images.githubusercontent.com/17422311/81907568-2a265180-95f2-11ea-9d27-132b1ca48699.png)

2. Data dengan tanggal 9 Mei tadi muncul di dashboard sebagai data tanggal 8 Mei yang berjumlah 3 orang
![image](https://user-images.githubusercontent.com/17422311/81908006-d2d4b100-95f2-11ea-82db-62a0db1edd3a.png)

**Comment by rendiriz** [comment]
- Dinkes Kota Cimahi
1. 
![Screen Shot 2020-05-14 at 16 23 25](https://user-images.githubusercontent.com/16224915/81918280-79737e80-9600-11ea-83fc-4db331729647.png)
![Screen Shot 2020-05-14 at 16 27 14](https://user-images.githubusercontent.com/16224915/81918296-7ed0c900-9600-11ea-9db8-44f278ab20f6.png)

3. 
![Screen Shot 2020-05-14 at 16 34 40](https://user-images.githubusercontent.com/16224915/81918586-dd964280-9600-11ea-9405-707fda1bea31.png)
![Screen Shot 2020-05-14 at 16 34 54](https://user-images.githubusercontent.com/16224915/81918594-df600600-9600-11ea-933c-20c40a483f0a.png)

- Dinkes Kota Bekasi
2. 
![Screen Shot 2020-05-14 at 16 37 24](https://user-images.githubusercontent.com/16224915/81918885-4aa9d800-9601-11ea-9031-f131bc237fee.png)
![Screen Shot 2020-05-14 at 16 37 57](https://user-images.githubusercontent.com/16224915/81918890-4d0c3200-9601-11ea-8b6d-2f44d01cf755.png)

**Comment by shintadewiaw** [comment]
mas @sandisunandar99  yang dashboard kumulatif masih belum sesuai

- [ ] **Dinkes Kota Cirebon**
- Data List Kasus
![image](https://user-images.githubusercontent.com/63390998/82028028-4643f480-96bf-11ea-90e0-8105d10b46bd.png)

- Data Dashboard
![image](https://user-images.githubusercontent.com/63390998/82027913-1eed2780-96bf-11ea-8180-6b842549a66b.png)

- [ ] **Dinkes Kota Banjar**
- Data List Kasus
![image](https://user-images.githubusercontent.com/63390998/82028191-80ad9180-96bf-11ea-87ad-b21a29dd009a.png)

- Data Kumulatif
![image](https://user-images.githubusercontent.com/63390998/82028431-d3874900-96bf-11ea-93b4-29ddd93b43ea.png)

**Comment by sandisunandar99** [comment]
@shintadewiaw ini belum sesuai nya dimana ya? tolong di buat aga detil ,, biar ga jadi statment ngambang

**Comment by sandisunandar99** [comment]
untuk kota cirebon,, memag kan 1 yg tgl 9 saja yang positif dan selanjut nya kumulatif,, 
dan banjar : meninggal . sembuh, postif aktif menang semua nya 1,,,

sekedar disclaimer aja,,
karna ini sesuai kesepakatannya perhitunngan nya 14 dari tanggal hari ini sampai kebelakagn,, maka yang akan di query juga sesuai tanggal tersebut,, dan untuk pembadingnya di list coba di perhatikan lagi posisi tanggal hari ini sampai ke tanggal ke belakang nya,, soalnya ga bisa di  tentukan di 1 tanggal aja,, 
cc : @alifianif @shintadewiaw
