### ISSUE TITLE
[Laporan Harian] Tabel data agregat perkriteria setiap dinkes daerah

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#308]
## Benchmark Desain
![Screenshot_2020-05-01 Pikobar - Pusat Informasi dan Koordinasi COVID-19 Jawa Barat](https://user-images.githubusercontent.com/11548871/80810521-3a036600-8bee-11ea-8001-7537f16bfa0f.png)

![WhatsApp Image 2020-04-30 at 2 28 08 PM](https://user-images.githubusercontent.com/11548871/80810562-569f9e00-8bee-11ea-9685-4c05628f43d9.jpeg)

## Desain
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=249%3A3227

## API
api nya : /api/dashboard/tabel-aggregate-criteria?min_date=&max_date=

## Acceptance Criteria

- [x] Terdapat title header "Tabel Covid-19 Disetiap Kabupaten Kota Jawa Barat"
- [x] Data yang ditampilan didalam tabel, sbb :

1. Nama Dinkes Kab/Kota
2. Total OTG (Proses + Selesai)
3. Total ODP Proses (Proses + Selesai)
4. Total PDP Proses (Proses + Selesai)
5. Total Positif (Proses + Selesai)
6. Grand Total 

- [x] Terdapat filter range tgl penginputan
- [x] Terdapat Sorting berdasarkan kolom
- [x] Terdapat button reset
- [x] Terdapat button expor

**Comment by alifianif** [comment]
Judulnya aja sih ini yang berbeda. Di AC tulisannya "Tabel Covid-19 Disetiap Kabupaten Kota Jawa Barat" tapi di aplikasi tulisannya "Rekap Pasien Dinkes Dinkes Pemprov 27 Mei 2020 16:23 WIB" Saya kurang tau sih mana yang lebih utama @erlangganugraha @Arif9878

**Comment by Arif9878** [comment]
title udah di ubah lif @alifianif parameter 'Dinkes Pemprov' itu daru nama user lif
