### ISSUE TITLE
[List Verifikasi Kasus] Perbaikan Label Status di List Verifikasi Kasus Faskes

### ISSUE THREAD

**Issue by alifianif** [jabardigitalservice/pikobar-pelaporan-frontend#310]
![image](https://user-images.githubusercontent.com/17422311/81634463-4a5ee080-9439-11ea-9405-6bcdbf265922.png)
Label statusnya di saya bertumpuk

**Comment by shintadewiaw** [comment]
mas @naufalihsank , sekalian kotak listnya dirapihin yaa, mungkin kotaknya dibikin full kaya yang di list kasus biar ga nanggung di tengah doang mas

![image](https://user-images.githubusercontent.com/63390998/81658405-ef41e380-9462-11ea-9b5c-22910563afa4.png)
