### ISSUE TITLE
[Dashboard] Filter pada bar chart angka harian/kumulatif

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#336]
## Acceptance Criteria :
Pilihan filter :

- [x] 1. Semua waktu
- [x] 2. 1 Minggu Terakhir
- [x] 3. 2 Minggu Terakhir
- [x] 4. 1 Bulan Terakhir

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by firmanJS** [comment]
@rendiriz
