### ISSUE TITLE
[Dashboard] Filter pie chart jenis kelamin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#337]
## Desain
Desain seperti :
![Screenshot_2020-05-19 Pikobar - Pusat Informasi dan Koordinasi COVID-19 Jawa Barat](https://user-images.githubusercontent.com/11548871/82246512-06a33400-996f-11ea-89bd-6f451bf89fa5.png)

## Acceptance Criteria
Pilihan filter :

- [x] 1. Semua Status
- [x] 2. Positif Covid-19
- [x] 3. Positif - Aktif
- [x] 4. Positif - Sembuh
- [x] 5. Positif - Meninggal
- [x] 6. ODP - Proses
- [x] 7. ODP - Selesai
- [x] 8. PDP - Proses
- [x] 9. PDP - Selesai
- [x] 10. OTG - Proses
- [x] 11. OTG - Selesai

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @rendiriz @firmanJS ada beberapa issue
1. Untuk yang perhitungan **ODP - Proses** tadi coba aku hitung manual per pagenya, totalnya 128 kasus, tapi di chartnya kalau di total cuma 153

![image](https://user-images.githubusercontent.com/63390998/82879432-21753a00-9f67-11ea-93ab-37ea3483f448.png)

2. Untuk perhitungan **Positif - Aktif** (Perempuan) Tidak sesuai
![image](https://user-images.githubusercontent.com/63390998/82880880-3226af80-9f69-11ea-9c6d-1c36a1c35fe5.png)

![image](https://user-images.githubusercontent.com/63390998/82880960-45d21600-9f69-11ea-9275-db9bb5802f0f.png)


sama mau tanya kalau Positif Covid-19 itu keseluruhan atau gimana er? @erlangganugraha

**Comment by rendiriz** [comment]
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/117#issuecomment-633911683
