### ISSUE TITLE
[Dashboard] Filter bar chart jenis kelamin

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#338]
## Desain
Desain seperti :
![Screenshot_2020-05-19 Pikobar - Pusat Informasi dan Koordinasi COVID-19 Jawa Barat(1)](https://user-images.githubusercontent.com/11548871/82246725-67327100-996f-11ea-9f74-d03d1ba99bb1.png)

## Acceptance Criteria
Pilihan filter :

- [ ] 1. Semua Status
- [x] 2. Positif Covid-19
- [x] 3. Positif - Aktif
- [x] 4. Positif - Sembuh
- [x] 5. Positif - Meninggal
- [ ] 6. ODP - Proses
- [ ] 7. ODP - Selesai
- [ ] 8. PDP - Proses
- [ ] 9. PDP - Selesai
- [ ] 10. OTG - Proses
- [ ] 11. OTG - Selesai

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
Punten mau nanya, kalau filter "Positif Covid-19" itu data yang mana ya? Keseluruhan positif atau gimana? @erlangganugraha @rendiriz @firmanJS

**Comment by firmanJS** [comment]
@alifianif keseluruhan positif covid sudah di benerin ya sama rendi
