### ISSUE TITLE
[Laporan Harian] Export Laporan Harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#339]
## User Story
Sebagai dinkes kota/kab/provinsi saya ingin mengexport laporan harian sebagai laporan harian kepada dinkes provinsi

> <img width="839" alt="81374556-b8e62a80-9129-11ea-934f-ca0d97c7a366" src="https://user-images.githubusercontent.com/11548871/82247216-3868ca80-9970-11ea-894c-eaaaf2734db3.png">

## Acceptance Criteria :
* [x] Dinkes provinsi bisa export data
* [x] Dinkes kota/kab bisa export data
* [x] Export data to jpg/png/pdf
* [x] Export data to excel berformat .xlsx
* [x] Jika data yang di filter/sorting maka data yang diexport sesuai hasil filter

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by alifianif** [comment]
1. Kalau kursornya diarahkan ke baris total, barisnya menghilang... kayaknya mending jangan dibikin menghilang gitu deh, mungkin lebih ke diredupkan aja warnanya atau jangan ada perubahan warna baris sama sekali
![image](https://user-images.githubusercontent.com/17422311/82981564-863b9d80-a016-11ea-96f1-f145510f0bae.png)

2. Untuk rentang waktu sepertinya lebih enak kalau ada keterangannya di atas widget calendarnya deh, seperti misal Tanggal Awal dan Tanggal Akhir
![image](https://user-images.githubusercontent.com/17422311/82981313-ee3db400-a015-11ea-8617-b9e1665a5444.png)

@Arif9878

**Comment by Arif9878** [comment]
@alifianif udah bisa di test lagi lif

**Comment by shintadewiaw** [comment]
**1. Urutannya lebih baik konsisten (excel & kolom pada FE)**
	0DP Proses - ODP Selesai - ODP Total
	OTG Proses - OTG Selesai - OTG Total
	PDP Proses - PDP Selesai - PDP Total
	Positif Aktif - Positif
	Positif Sembuh
	Positif Meninggal
	Positif Total

**Comment by Arif9878** [comment]
@sandisunandar99 yang excel bisa nyesuain frontend mang?

**Comment by sandisunandar99** [comment]
@Arif9878 okay.. urng benerin dlu

**Comment by shintadewiaw** [comment]
ini kabupaten/kota diganti Kecamatan ya guys

![image](https://user-images.githubusercontent.com/63390998/83378641-874c4080-a403-11ea-80e1-1844e963df71.png)

@Arif9878 & @sandisunandar99

**Comment by sandisunandar99** [comment]
@shintadewiaw .. yg donlot by kecamatan nya sudah aku push staging ya
