### ISSUE TITLE
[Laporan Kasus] Export to Formulir PE (front end)

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#341]
## Form Lampiran 6
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf](https://user-images.githubusercontent.com/11548871/82249456-fc376900-9973-11ea-96bc-4e210a058e6e.png)
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf(1)](https://user-images.githubusercontent.com/11548871/82249455-fb063c00-9973-11ea-987f-6b9290bf6e8e.png)
![Screenshot_2020-05-19 REV-04_Pedoman_P2_COVID-19_ 27 Maret2020_Tanpa TTD pdf pdf(2)](https://user-images.githubusercontent.com/11548871/82249451-f9d50f00-9973-11ea-8fff-ca543b99f60f.png)

## Acceptance Criteria

- [x] Export menjadi formulir PE dalam bentuk PDF

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by naufalihsank** [comment]
Fitur ini ada di menu apa sama rolenya siapa aja ya kang ? @erlangganugraha

**Comment by naufalihsank** [comment]
Rolenya siapa aja, nama tombolnya apa, sama nama file hasil exportnya apa kang ? @erlangganugraha

**Comment by erlangganugraha** [comment]
nama tombolnya : Cetak Laporan PE
Nama File nya : Laporan PE - [kode kasus]
@naufalihsank

**Comment by shintadewiaw** [comment]
1. Tanggal Lahir Invalid Date, lebih baik jika kosong (-)

2. Umur 23 Tahun, 0 Bulan atau Umur 23 Tahun, - Bulan

![image](https://user-images.githubusercontent.com/63390998/83377671-87970c80-a400-11ea-898e-609dfe705096.png)

**Comment by naufalihsank** [comment]
@khihadysucahyo

**Comment by khihadysucahyo** [comment]
@shintadewiaw yang ceklistnya ga sesuai data yang mana ya? nanrti saya cekkan, barusan ngecek dan nyoba bikin baru udah sesuai soalnya.

**Comment by shintadewiaw** [comment]
> @shintadewiaw yang ceklistnya ga sesuai data yang mana ya? nanrti saya cekkan, barusan ngecek dan nyoba bikin baru udah sesuai soalnya.

Yang informasi klinis sama kondisi penyerta mas, saya coba di dinkescirebon

**Comment by shintadewiaw** [comment]
**Perubahan Kolom Kriteria**

- [ ] Kasus Probabel diubah menjadi Orang Tanpa Gejala

- [ ] Kasus Konfirmasi isinya yang statusnya Positif

@naufalihsank @khihadysucahyo

**Comment by shintadewiaw** [comment]
Kolom kriteria belum ada perubahan 

![image](https://user-images.githubusercontent.com/63390998/83713467-59a90680-a652-11ea-96aa-9be66d4d6555.png)

![image](https://user-images.githubusercontent.com/63390998/83713532-83fac400-a652-11ea-977c-230bb46e23d6.png)


@khihadysucahyo @naufalihsank
