### ISSUE TITLE
[Laporan Harian] Penambahan kolom baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#342]
![Screenshot_2020-05-19 4 UPDATE LAPORAN HARIAN 15-5-20(1) pdf](https://user-images.githubusercontent.com/11548871/82253435-2c363a80-997b-11ea-87eb-be160bfc3d53.png)

## Acceptance Criteria :

- [x] Total WNI
- [x] Total WNA
- [x] Total laki-laki disetiap status
- [x] Total perempuan disetiap status
- [x] Total usia disetiap status

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by ReksaMohammad** [comment]
@erlangganugraha 

![Laporan Harian](https://user-images.githubusercontent.com/42407562/83480542-e4102f80-a4c5-11ea-8649-a4234137cbe2.png)

**Comment by sandisunandar99** [comment]
@Arif9878 mang yg ini udah ,, coba cek postman yes,, :+1:

**Comment by shintadewiaw** [comment]
@Arif9878 Total data positif aktif - selesai & total gender tidak sesuai

**Comment by shintadewiaw** [comment]
positif proses belum terhitung @Arif9878 @sandisunandar99 

![image](https://user-images.githubusercontent.com/63390998/84616342-ee82ee00-aef5-11ea-8eab-3fdabfc4809c.png)

![image](https://user-images.githubusercontent.com/63390998/84616377-022e5480-aef6-11ea-9d37-549c5b0230ef.png)
