### ISSUE TITLE
[Laporan Kasus] Redesain form input kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#371]
### Step 1

> ![WhatsApp Image 2020-06-03 at 11 46 12 AM](https://user-images.githubusercontent.com/11548871/83612282-67a44c00-a5ac-11ea-8e47-3008556b8e83.jpeg)

### Step 2

> ![WhatsApp Image 2020-06-03 at 11 46 09 AM](https://user-images.githubusercontent.com/11548871/83612287-696e0f80-a5ac-11ea-85f8-198a8ad66919.jpeg)

## Acceptance Criteria :
* [ ] Dibuat responsive (Mode tablet & smartphone)
* [ ] Fungsikan tab index agar memudahkan penginputan

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @naufalihsank ini jaraknya kejauhan, coba dibuat fit sama bordernya 

![image](https://user-images.githubusercontent.com/63390998/83851651-e03a1280-a73c-11ea-86b9-1d949653976d.png)
