### ISSUE TITLE
[Laporan Kasus] Tambahan kolom Form perbaiki data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#372]
## Issue
Ada beberapa field yg kurang seperti NIK belum ada

## Acceptance Criteria :

- [x] Field Nama diganti jadi Nama Kasus
- [x] NIK
- [x] Id kasus terkait dibuat dropdown seperti input kasus baru
- [x] Dropdown Kota, Kec, Desa (alamat tempat tinggal)
- [x] Validasi No Telepon seperti input kasus baru
- [x] Jika dipilih WNA maka muncul list negara
- [x] Jika dipilih Rumah sakit maka muncul drodown List Rumah Sakit
- [x] Urutan Status setelah Tahapan
- [x] Field Masukkan riwayat lainnya jika ada
- [x] Field Sebutkan kondisi penyerta lainnya jika ada
- [x] Sebutkan gejala lainnya jika ada
- [x] Pesan alasan dibuat rapih
- [x] Form input alasan dibuat rapih

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
### **Issue & Feedback**
**1. Kolom ID Kasus Terkait panjangnya disamakan dengan ID Kasus Pusat**


**2. Saat pilih Lokasi Saat Ini kolom menjadi berantakan**
![image](https://user-images.githubusercontent.com/63390998/83847061-ccd77900-a735-11ea-90cd-241f8376ef97.png)


**3. Kolom Tempat Lainnya dibuat memanjang juga**

**4.  Data tidak bisa disimpan**
![image](https://user-images.githubusercontent.com/63390998/83848524-35bff080-a738-11ea-8bb3-1062ff1121b1.png)

**Comment by shintadewiaw** [comment]
mas @naufalihsank kolom **Alamat Lengkap Saat Ini** jangan diisi otomatis dari data sebelumnya, biarin kosong aja
![image](https://user-images.githubusercontent.com/63390998/84011313-204cff80-a9a0-11ea-9667-f8c5bc658912.png)

**Comment by shintadewiaw** [comment]
**Role Faskes**
- Lokasi saat ini tidak tersimpan saat perbaiki data kasus
- ID kasus terkait tidak tersimpan saat perbaiki data kasus
- Hasil tidak perlu ditampilkan jika status masih proses pada role Faskes
- Setelah edit data riwayat di List Vefikasi Kasus jangan redirect ke List Kasus tetapi ke List Verifikasi Kasus aja

@naufalihsank

**Comment by shintadewiaw** [comment]
mas @naufalihsank lokasi saat ini & kasus terkait masih belum tersimpan saat perbaiki kasus

**Comment by shintadewiaw** [comment]
mas @naufalihsank belum ada perubahan juga yang lokasi saat ini & kasus terkait wkwk
sekalian yang di dinkesnya ya

**Ini yang diperbaiki (role faskes)**
![image](https://user-images.githubusercontent.com/63390998/84760787-bc0aeb00-aff2-11ea-9d79-5b62e841959a.png)

**Ini tampilan di dinkesnya alamatnya ga masuk (role dinkes)**
**setelah ini kasus ditolak)**
![image](https://user-images.githubusercontent.com/63390998/84760855-d1801500-aff2-11ea-9a2b-ac1ff3d104f4.png)

**ini diperbaiki lagi ga ada kasus terkait & lokasi saat ini yang tersimpan sebelumnya(role faskes)**
![image](https://user-images.githubusercontent.com/63390998/84761246-608d2d00-aff3-11ea-8eaf-8e0473847114.png)
