### ISSUE TITLE
[Manajemen User] Penyesuaian create user

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#389]
## Acceptance Criteria
- [x] Penambahan kolom unit type

### Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @Arif9878 kalo udah pilih dropdown jangan stuck dipilihan pertama, munculin lagi daftar dropdownnya
![image](https://user-images.githubusercontent.com/63390998/84634852-9ad7cb00-af1c-11ea-9e60-e0152a93b564.png)

**Comment by Arif9878** [comment]
@shintadewiaw ya itu harus di hapus dulu sin baru ada pilihan lain

**Comment by shintadewiaw** [comment]
> @shintadewiaw ya itu harus di hapus dulu sin baru ada pilihan lain

Gabisa dihapus mas harus di refresh, bisa ga ya tambahin (x) untuk reset di dalam kolomnya?

**Comment by Arif9878** [comment]
bisa di hapus
