### ISSUE TITLE
[Hasil Test] Edit hasil test terakhir

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#398]
## Screenshoot
![Screenshot_2020-06-10 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/84248742-0f34f780-ab34-11ea-8038-6386a5500472.png)

## Acceptance Criteria
- [x] Perubahan nama button menjadi "Edit hasil test terakhir"
- [x] Edit hasil test hanya group 3 (hasil pemeriksaan) *bisa dilihar screenshoot

### Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by shintadewiaw** [comment]
mas @naufalihsank ini kolom kecamatannya jangan disabled, sama kolom kategori di hide aja ya mas

**Comment by shintadewiaw** [comment]
Mengubah data test terakhir seperti gambar dibawah:
![image](https://user-images.githubusercontent.com/63390998/84654905-2f045b00-af3a-11ea-8acd-b88a7579f7ec.png)


Pada riwayat test ga keubah
![image](https://user-images.githubusercontent.com/63390998/84654924-3af01d00-af3a-11ea-8817-8dced5a18290.png)

**Comment by naufalihsank** [comment]
kang @sandisunandar99 di api yang `/api/rdt/{id}/histories` si history terakhirnya kenapa ga keganti dari yg edit hasil test ya ?

**Comment by sandisunandar99** [comment]
@naufalihsank coba cek yg di WA waktu itu.. prasaan ga gitu url api nya.. /api/rdt/{id}

**Comment by shintadewiaw** [comment]
mas @naufalihsank ini kolom alamat required tapi malah disabled

![image](https://user-images.githubusercontent.com/63390998/84853062-89abcd00-b088-11ea-8f94-6be81da2bbad.png)

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/84870577-b15f5d00-b0a9-11ea-838f-a00cbb05a2ba.png)

@naufalihsank

**Comment by naufalihsank** [comment]
@shintadewiaw yang inimah teh kyknya pas lagi submit pas BE nya lagi gabisa diakses deh

**Comment by shintadewiaw** [comment]
mas @naufalihsank tanggal pemeriksaannya gabisa diubah
