### ISSUE TITLE
[Edit Kasus] Tambahan Tahun & Bulan pada Kolom Usia

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#403]
### Note

- [x] Penambahan Tahun dan Bulan pada Kolom Usia Edit Kasus Role Staffprov
- [x] Penambahan Tahun dan Bulan pada Kolom Usia Edit Kasus Role Dinkes
- [x] Penambahan Tahun dan Bulan pada Kolom Usia Edit Kasus Role Faskes
- [x] Penambahan Tahun dan Bulan saat Perbaiki Data Kasus Role Faskes

**Comment by shintadewiaw** [comment]
mas @naufalihsank  ini januari kok kehitungnya 5 bulan ya?
![image](https://user-images.githubusercontent.com/63390998/84252087-5cb36380-ab38-11ea-86de-3fd8f7f223e0.png)

**Comment by erlangganugraha** [comment]
1. jika tanggal lahir teriisi maka usianya bakal otomatis terisi sesuai perhitungan tgl lahir
2. jika tanggal lahir kosong maka usianya tidak otomatis terhitung

Fokus ditgl lahirnya, karena hitungannya yg paling benar
@shintadewiaw

**Comment by shintadewiaw** [comment]
mas @naufalihsank  Kalkulasi perhitungan dari tanggal lahir ke tahun dan bulan masih salah (contoh: ini input januari kehitungnya 5 bulan)
![image](https://user-images.githubusercontent.com/63390998/84252087-5cb36380-ab38-11ea-86de-3fd8f7f223e0.png)

**Comment by naufalihsank** [comment]
@shintadewiaw kan bener teh, kalo ada yg lahir tahun ini bulan januari umurnya 5 bulan kan ?

**Comment by erlangganugraha** [comment]
@shintadewiaw coba testing pake tgl lahir kamu
