### ISSUE TITLE
[Hasil Test] Penyesuaian Filter Hasil Test

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#418]
### Acceptance Criteria

- [x] Kolom Mekanisme sementara di hide

- [x] Metode yang digunakan: RDT & PCR

- [x] Kategori Sasaran sementara di hide

**Comment by shintadewiaw** [comment]
mas  @naufalihsank kolom  "metode yang digunakan" tidak berfungsi

**Comment by shintadewiaw** [comment]
mas @naufalihsank untuk filter yang RDT belum sesuai
a. Data di List Hasil Test
![image](https://user-images.githubusercontent.com/63390998/85268541-d9333400-b4a0-11ea-9a5c-a57864f31ef7.png)

b. Data setelah di Filter berdasarkan RDT
![image](https://user-images.githubusercontent.com/63390998/85268659-ff58d400-b4a0-11ea-99c8-18b5df63c676.png)

**Comment by naufalihsank** [comment]
@shintadewiaw kalo filter yg itu kayaknya maksudnya nampilin data hanya yg pake RDT deh teh mksdnya. Bukan nge sorting kolom rdt nya

**Comment by shintadewiaw** [comment]
iya mas, total yang pakai RDT kan ada 5 (yang di list), tapi waktu di filter berdasarkan RDT kok munculnya cuma 3 aja

**Comment by shintadewiaw** [comment]
kalau yang PCR di list ada 3 user nah waktu di filter berdasarkan PCR bener ada 3 user

**Comment by naufalihsank** [comment]
@sandisunandar99 gimana ni kang wkwk

**Comment by naufalihsank** [comment]
@shintadewiaw oh ituu teh, jadi ga semua yg ada data berapa x rdt nya itu berarti test terakhir nya pake rdt. sedangkan si filter itu nunjukinnya si alat test terakhirnya aja. kayak data nomer 4 yg namanya `Zaen Efendi` itu kyknya alat test terakhirnya bukan rdt. karena hasil test terakhirnya `POSITIF` , padahal rdt gaada yg hasilnya positif

**Comment by shintadewiaw** [comment]
@naufalihsank ohh berarti filter itu berdasarkan hasil test terakhir juga ya mas?

**Comment by naufalihsank** [comment]
@shintadewiaw iya teh itu dia ngefilter yang alat test terakhirnya doang
