### ISSUE TITLE
[Rujukan] Filter list rujukan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#431]
## Benchmark
![Screenshot_2020-06-18 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/84980086-54bc7a80-b15b-11ea-8cd0-a4dd584f1003.png)

## Design
![mockup](https://user-images.githubusercontent.com/42407562/84987285-0fec1000-b16a-11ea-8aaa-62bf0268023f.png)

## Acceptance Criteria

- [x] Filter data bisa berdasarkan sbb 
- [x] 1. Tempat Rujukan
- [x] 2. Status/kriteria pasien
- [x] 3. Tanggal rujuk
- [x] 4. Alamat tempat tinggal pasien (Kab/kota, kecamatan, kelurahan)
- [x] 5. Hasil
- [x] Terdapat tombol reset

### Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by ReksaMohammad** [comment]
@erlangganugraha @shintadewiaw 

![Filter List Pasien Rujukan](https://user-images.githubusercontent.com/42407562/84987285-0fec1000-b16a-11ea-8aaa-62bf0268023f.png)

**Comment by shintadewiaw** [comment]
Setiap ngefilter muncul toast
![image](https://user-images.githubusercontent.com/63390998/85373404-6936b380-b55d-11ea-8e87-49d26b78a1fe.png)

@Arif9878 @khihadysucahyo

**Comment by shintadewiaw** [comment]
Setelah memilih tanggal kemudian reset list data rujukan tidak muncul (harus di refresh)
![image](https://user-images.githubusercontent.com/63390998/85501205-17e6fc80-b60f-11ea-8bf8-177ec1c21fa6.png)
