### ISSUE TITLE
[Hasil Test] Pop up detail hasil test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#452]
### Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=308%3A3&viewport=555%2C-8676%2C0.5460377931594849&scaling=min-zoom

### Acceptance criteria

- [x] Buat seperti prototype

**Comment by shintadewiaw** [comment]
@muhammaddyzf mas ini tulisannya dibikin sama rata kaya yang dibawah ya

![image](https://user-images.githubusercontent.com/63390998/85982931-d5f3f700-ba10-11ea-9b08-48346398062b.png)

**Comment by shintadewiaw** [comment]
@muhammaddyzf 

- [ ] 1. Dirapihin ya tampilan slidenya

![image](https://user-images.githubusercontent.com/63390998/85983412-af828b80-ba11-11ea-9a1e-6eb828b61cce.png)

- [ ] 2. Tanggal Update terakhir ga update

Ini yang di update
![image](https://user-images.githubusercontent.com/63390998/85984071-cecde880-ba12-11ea-9091-042769096efd.png)

Ini tampilan di detail
![image](https://user-images.githubusercontent.com/63390998/85984112-e311e580-ba12-11ea-84f3-a9b4ef0cf7b1.png)

- [ ] 3. Saat klik update hasil test tampilan di reset aja, jangan langsung menampilkan pesan error pada kolom metode
![image](https://user-images.githubusercontent.com/63390998/85984187-076dc200-ba13-11ea-9169-c6c8e398087e.png)

**Comment by shintadewiaw** [comment]
Feedback 30/06/2020

- [ ] 1. Jika menggunakan metode PCR lebih baik Sampel diberi tanda (-)

- [ ] 2. Kode hasil test, ID Kasus, Sasaran, NIK, Nama Peserta dll dibuat menjorok ke kanan setelah Judul (ID Kasus, Kategori,Identitas)
![image](https://user-images.githubusercontent.com/63390998/86083610-fa111000-bac4-11ea-8dcc-eeb2788aa136.png)
