### ISSUE TITLE
[Hasil Test] Pop up edit hasil test terakhir

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#453]
### Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=308%3A3&viewport=555%2C-8676%2C0.5460377931594849&scaling=min-zoom

### Acceptance criteria

- [x] Buat seperti prototype

**Comment by shintadewiaw** [comment]
@muhammaddyzf mas ini tulisannya dibikin sama rata kaya yang dibawah ya

![image](https://user-images.githubusercontent.com/63390998/85982931-d5f3f700-ba10-11ea-9b08-48346398062b.png)

**Comment by muhammaddyzf** [comment]
oke siap

**Comment by shintadewiaw** [comment]
**Feedback 30/06/2020**
- [ ] Kode hasil test, ID Kasus, Sasaran, NIK, Nama Peserta dll dibuat menjorok ke kanan setelah Judul (ID Kasus, Kategori,Identitas)
![image](https://user-images.githubusercontent.com/63390998/86083610-fa111000-bac4-11ea-8dcc-eeb2788aa136.png)
