### ISSUE TITLE
Update profil user

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#474]
### Desain
WIP by kang reksa

### Benchmark
![Screenshot_2020-07-01 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/86190890-d22ab680-bb6f-11ea-9500-ab6719a2f30b.png)

### Acceptance Criteria
- [x] Title caption : "Perbaharui Profil"
- [x] Form disamakan dengan page ubah pengguna
- [x] Ketika proses update berhasil, maka direct ke page sebelumnya diakses
- [x] Terdapat validasi username : belum/sudah digunakan
- [x] Field "Hak akses" dibuat disabled

### Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

**Comment by Arif9878** [comment]
@erlangganugraha klu pas edit sebagai dinkes kota mah emang bisa ngeset hak akses user er, tapi kalau sebagai faskes gak ada pilihan hak aksesnya

**Comment by shintadewiaw** [comment]
@Arif9878 alamat jangan disabled
![image](https://user-images.githubusercontent.com/63390998/86319526-e7324300-bc5e-11ea-84fc-c5b115e81a5f.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878  ini field hak akses di disabled ya sesuai AC

**Comment by shintadewiaw** [comment]
mas @Arif9878 validasi untuk username pesan errornya dimunculin di FE aja, terus field hak akses belum di disabled

**Comment by shintadewiaw** [comment]
mas @Arif9878 validasi untuk username pesan errornya dimunculin di FE aja, terus field hak akses belum di disabled

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/87045243-de72db80-c221-11ea-8b3a-e0352c1f03c2.png)

**Comment by shintadewiaw** [comment]
@Arif9878 hak akses belum disabled
