### ISSUE TITLE
[Laporan Kasus] Revamp Input Laporan Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#489]
### Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=34%3A2503&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

### AC

- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon
- [x] Untuk field dibawah ini perlu ada didatabase kita (aplikasi pelaporan pikobar) dengan diambil automatis berdasarkan user login
![Screenshot_2020-07-03 Create New Identification Bersatu Lawan Covid-19(1)](https://user-images.githubusercontent.com/11548871/86442120-7b6fd900-bd37-11ea-9362-10f227c220d9.png)

- [x] Untuk tanggal wawancara by default terisi tanggal sekarang
- [x] Terdapat validasi NIK jika sudah digunakan
- [x] Jika tanggal lahir diisi maka usia akan automatis terhitung dari tanggal lahir
- [x] Jika lokasi saat ini dipilih Rumah, maka muncul 2 pilihan sbb :
  - [x] 1. Pilihan sesuai alamat tempat tinggal
  - [x] 2. Tidak sesuai alamat tempat tinggal, maka muncul inputan alamat

---
---

### UX
![Screenshot_2020-07-03 Figma](https://user-images.githubusercontent.com/11548871/86446256-e6bca980-bd3d-11ea-9ddb-e932a3f9794c.png)
- [x] Jika dicheklist "Dari luar negeri", maka muncul field inputan negara dikunjungi dan diset mandatory beserta inputan tgl mulai & pulang perjalanan
- [x] Jika dicheklist "Dari luar kota", maka muncul field inputan kota yang dikunjungi dan diset mandatory beserta inputan tgl mulai & pulang perjalanan
- [x] Untuk inputan pilihan "Kontak erat dengan suspek ?", jika user memilih jawaban Ya. Maka muncul inputan Nama Pasien Terkait yang dimana bisa dicari dalam proses penginputannya
- [x] Untuk inputan pilihan "Kontak erat dengan kasus konfirmasi (Positif) ?", jika user memilih jawaban Ya. Maka muncul inputan Nama Pasien Terkait yang dimana bisa dicari dalam proses penginputannya

#### Tambahan UX

- [x] Untuk field inputan pilihan Ya/Tidak by default jawabannya "Tidak"
- [x] Jika pertanyaan kunjungan tempat dipilih "Ya", maka muncul inputan **Lokasi/tempat** serta **Tanggal Kunjungan**

#### Tambahan 2 UX

- [x] Field inputan hasil tetap dimuncul jika memilih kriteria **OTG,ODP, PDP & Positif** + memilih tahapan **selesai**
- [x] Form data kontak diset semua tidak mandatory
- [x] Jika dipilih ODP, PDP, dan Positif maka inputan gejala + tanggal muncul gejala diset mandatory 

---
#### Tambahan
- [x] Penambahan Field Inputan Tanggal Kontak didalam form tambah kontak erat
- [x] Penambahan Field Inputan Tanggal Kunjungan dipertanyan kunjungi tempat
- [x] Penambahan Field Inputan List Petugas Kesehatan

## Revisi
- [ ] Ketika input baru menggunakan akun faskes seharusnya direct ke list verifikasi kasus (issue : belum direct ke list verifikasi kasus)
- [ ] Input Kasus error 422  _id 5f0d392d7ae9500012c65962 ID already exists in the database

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [x] Tablet
- [ ] Desktop

**Comment by ReksaMohammad** [comment]
![Buat Laporan Kasus](https://user-images.githubusercontent.com/42407562/86550744-6c726c00-bf6d-11ea-91ce-2e92748005d2.png)

**Comment by shintadewiaw** [comment]
mas @muhammaddyzf aku coba 2x input kenapa ID already exists in the database mulu ya, padahal udah clear cache

**Comment by shintadewiaw** [comment]
**Feedback 13 Juli 2020**

![image](https://user-images.githubusercontent.com/63390998/87272030-46197700-c4ff-11ea-82b5-9836a20848c9.png)

Validasi 'kolom harus diisi' dijadikan satu saja dibawah, tidak perlu per checkbox diberi pesan error

**Comment by shintadewiaw** [comment]
error saat menambahkan data kasus @Arif9878 @khihadysucahyo @firmanJS

![9dff1d6d-8e86-4d53-a645-cad6f13a2c8e](https://user-images.githubusercontent.com/63390998/87400020-74bc4e00-c5e2-11ea-9094-015831042057.jpg)
