### ISSUE TITLE
[List Hasil Test] Hasil Test Terbaru ditaro Paling Atas

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#497]
Deskripsi:
Saat berhasil menambahkan data baru hasil test, maka dimunculkan di list yang terbaru paling atas

**Comment by muhammaddyzf** [comment]
@shintadewiaw kalo saya coba input data baru di hasil test emg udh `descending`, jd data terbaru muncul di paling awal
