### ISSUE TITLE
[Kontak Erat] Form Identifikasi Kontak Erat

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#503]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC

- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon
- [x] By default nama pewawancara get from nama pengguna
- [x] Tanggal wawancara pelacakan kontak by default terisi tanggal sekarang
- [x] Terdapat validasi NIK jika sudah digunakan
- [x] Jika tanggal lahir diisi maka usia akan automatis terhitung dari tanggal lahir

---

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

**Comment by shintadewiaw** [comment]
**Feedback 11 Juli 2020**
1. Penempatan tambah kontak baru dibawah header 'buat kontak erat'
![image](https://user-images.githubusercontent.com/63390998/87215228-93aaae00-c35e-11ea-850a-ba7fb6002c5a.png)


2. Cari ID kasus primer tidak muncul jika klik nama pasien
3. Jika 'Dari Luar Kota' di checklist baru memunculkan tanggal mulai & kepulangan, jangan langsung dimunculkan karena ambigu
4. Riwayat Vaksinasi sebaiknnya default 'Tidak' Jika pilih 'Ya' baru memunculkan kolom Tanggal Vaksinasi
5. Pemeriksaan Penunjang sebaiknya default 'Tidak' Jika pilih 'Ya' maka baru memunculkan kolom Tanggal & Hasil
6. Input Kontak Erat Error 'updateBy is not Allowed'
![image](https://user-images.githubusercontent.com/63390998/87215221-868dbf00-c35e-11ea-8f86-a55e4893a9b1.png)

**Comment by Arif9878** [comment]
@shintadewiaw point no 1 ada perubahan design sin kmarin cek figma

**Comment by shintadewiaw** [comment]
@Arif9878 oke mas di skip ajaa

**Comment by Arif9878** [comment]
point no 8 coba cek keterangan di figma untuk yang kontak erat serumah @shintadewiaw

**Comment by shintadewiaw** [comment]
memperbaiki responsive pesan error pada kolom: jenis kontak, bulan, desa/kel

![image](https://user-images.githubusercontent.com/63390998/87268668-339a4000-c4f5-11ea-96fb-b7c5ef7f4e43.png)
