### ISSUE TITLE
[Laporan Kasus] Edit Data Pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#514]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC
- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] Dibuat pop up
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon

## Revisi:
- [x] Data usia tidak tersimpan saat edit data pasien

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

**Comment by shintadewiaw** [comment]
mas @Arif9878 ini bulannya setiap di edit selalu balik ke angka 5
