### ISSUE TITLE
[Laporan Kasus] Update Status Pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#515]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=174%3A1133&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC
- [x] Layout disamakan dengan desain yang sudah dibuat
- [x] Terdapat field2 yang mandatory dengan melabeli * merah
- [x] Dibuat pop up
- [x] NIK & No telepon dibuat mandatory, jika tidak ada NIK/No telepon maka inputkan alasan tidak ada NIK/No telepon

---
## UX
- [x] Field inputan hasil tetap dimuncul jika memilih kriteria **OTG,ODP, PDP & Positif** + memilih tahapan **selesai**
- [x] Jika dipilih ODP, PDP, dan Positif maka inputan gejala + tanggal muncul gejala diset mandatory 

## Revisi

- [x] Field inputan riwayat perjalanan otomatis terpilih (Issue : Field inputan riwayat perjalan tidak kepilih saat edit)
- [x] Jika pilih sesuai alamat tempat tinggal, maka alamat otomatis terisi sesuai alamat tempat tinggal pasien (issue : belum otomatis keisi sesuai alamat tempat tinggalnya)

## Cross-browser compatibility:
- [x] Chrome
- [ ] Firefox

## Responsiveness
- [x] Mobile
- [ ] Tablet
- [ ] Desktop

**Comment by shintadewiaw** [comment]
'Kondisi Penyerta Lainnya' hanya satu saja dibawah kolom 'Kondisi Penyerta'

![image](https://user-images.githubusercontent.com/63390998/87283636-b0daaa80-c51f-11ea-98ed-d093538af77a.png)

**Comment by shintadewiaw** [comment]
**Feedback 14 Juli 2020**
1. Ubah pasien - Riwayat perjalanan disimpan saat edit
2. Jika memilih data tempat tinggal, diisi otomatis sesuai data tempat tinggalnya

**Comment by shintadewiaw** [comment]
Jika pilih sesuai alamat tempat tinggal, maka alamat otomatis terisi sesuai alamat tempat tinggal pasien (issue : belum otomatis keisi sesuai alamat tempat tinggalnya)
catatan: RT, RW Dimasukkan ke kolom alamat juga (di detail)

![image](https://user-images.githubusercontent.com/63390998/87508407-87de2500-c699-11ea-9049-bd9b7cd481f0.png)

![image](https://user-images.githubusercontent.com/63390998/87508319-4e0d1e80-c699-11ea-9592-9a6cfb829282.png)|

@Arif9878
