### ISSUE TITLE
[Kontak Erat] Revisi List Identifikasi

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#528]
## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=2360%3A19834&viewport=699%2C-6526%2C1.035852313041687&scaling=scale-down-width

## AC
- [x] List kolom disesuaikan dengan desain
- [x] Data yang ditampilkan pada list identifikasi merupakan data yang sudah diwawancara

**Comment by shintadewiaw** [comment]
mas @Arif9878 aku tambah kontak erat baru 2x gamasuk datanya di list
![image](https://user-images.githubusercontent.com/63390998/87527449-5758b400-c6b6-11ea-8c3e-0ab315214887.png)

![image](https://user-images.githubusercontent.com/63390998/87527497-693a5700-c6b6-11ea-8003-3b00313f71fa.png)

Terus di listnya kolom kolomnya disesuain sama figma ya mas

**Comment by Arif9878** [comment]
@shintadewiaw  tag hadi juga klu gk masuk datanya

**Comment by shintadewiaw** [comment]
cc: @khihadysucahyo
