### ISSUE TITLE
[Laporan Kasus] List Kasus Rev 5

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#544]
## Background
Adanya pedoman pencegahan & pengendalian covid-19 Revisi 5 dari kemenkes, oleh karena itu perlu adanya penyesuaian app pelaporan.

## AC

- [x] Kolom tahapan dihilangkan
- [x] Kolom tgl input diganti menjadi tgl last update
- [x] Kolom Usia dibuat 2 digit angka dgn value data **usia tahun**
- [x] Kolom Status tetap ada, dgn tambahan kriteria sbb 
1. Kontak Erat
2. Suspek
3. Probabel
4. Konfirmasi
5. Discarded

---
### Filter 
- [x] Tambahan item pada kolom Kriteria sbb
1. Kontak Erat
2. Suspek
3. Probabel
4. Konfirmasi
5. Discarded

---
### Fungsi Import

- [x] Button import dihidden

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

**Comment by shintadewiaw** [comment]
mas data statusnya jadi dobel di list
![image](https://user-images.githubusercontent.com/63390998/88133228-c2047500-cc0b-11ea-9580-f7a3255ca251.png)

@Arif9878

**Comment by Arif9878** [comment]
@shintadewiaw ini di upadate riwayat baru sin?

**Comment by shintadewiaw** [comment]
@Arif9878 itu di listnya langsung begitu mas
