### ISSUE TITLE
[Laporan Harian] Format Laporan Harian Rev 5

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#550]
## Background
Adanya pedoman pencegahan & pengendalian covid-19 Revisi 5 dari kemenkes, oleh karena itu perlu adanya penyesuaian app pelaporan.

## Desain
![Aplikasi Pelaporan@2x(13) 2](https://user-images.githubusercontent.com/11548871/87882836-23bab880-ca2d-11ea-8bed-80b282f1dd38.png)

## AC
- [ ] Disamakan dengan format lampiran 4 Rev 5

**Comment by ReksaMohammad** [comment]
![Laporan Harian](https://user-images.githubusercontent.com/42407562/88248107-3aca0680-ccca-11ea-802f-10743634e419.png)

**Comment by alifianif** [comment]
mas @Arif9878 sambil nunggu API dari aku ada revisi:
1. Button "Ekspor" kalau di desain namanya "Unduh". Ini minor sih, tapi kayanya disamakan saja dengan desain. gimana @erlangganugraha ?
![ekspor-unduh](https://user-images.githubusercontent.com/17422311/88766807-e085e580-d1a2-11ea-981e-f44431e62dc9.PNG)
2. Judul kolom seharusnya ukuran fontnya lebih besar dari isi kolom di bawahnya atau minimal ukurannya sama agar lebih keliatan
![image](https://user-images.githubusercontent.com/17422311/88766905-0ad7a300-d1a3-11ea-8fe8-27b5673e0fca.png)
3. Keterangan dinkes seharusnya sejajar dengan tabel
![image](https://user-images.githubusercontent.com/17422311/88767029-3d819b80-d1a3-11ea-9f61-fdd5c16ad76b.png)
4. Baris "Jumlah Kontak Erat Dipantau" diarsir hitam. Seharusnya tidak diarsir hitam, tapi ditambahkan satu baris lagi di bawahnya dan baris tersebut yang diarsir hitam
![jmlh kontak erat dipantau hitam](https://user-images.githubusercontent.com/17422311/88767128-6144e180-d1a3-11ea-95bd-1c185640b72b.PNG)

**Comment by Arif9878** [comment]
@alifianif  aku menyesuaikan desain yang paling atas lif untuk point no.4

**Comment by alifianif** [comment]
@Arif9878 oooh aku liatnya desain yg dari mas reksa sih... oke kalo gitu
