### ISSUE TITLE
[Laporan Kasus] Bug Riwayat Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#559]
How to Reproduce Bug:
1. Update Riwayat Kasus dengan memilih "Lokasi Saat Ini=Rumah"
2. Pada Detail Riwayat Kasus data alamat tidak masuk

Catatan: di respons BE ada

![image](https://user-images.githubusercontent.com/63390998/88151837-60550280-cc2d-11ea-9a02-cca92293efa8.png)

![image](https://user-images.githubusercontent.com/63390998/88151970-8ed2dd80-cc2d-11ea-8e6d-bf200a2ccc4e.png)

**Comment by Arif9878** [comment]
@shintadewiaw di kasih keterangan kasus siapa sama user rolenya apa sin

**Comment by shintadewiaw** [comment]
@Arif9878 oh iya mas
role: dinkes, dinkeskotabandung
nama kasus yang diedit: Karis

**Comment by Arif9878** [comment]
![Screen Shot 2020-07-22 at 17 08 04](https://user-images.githubusercontent.com/20775950/88164163-f55ff780-cc3d-11ea-8042-724d30168059.png)
