### ISSUE TITLE
[Laporan Kasus] Revisi List Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#567]
## AC

- [x] Kolom status direname jadi **Kriteria**
- [x] Kolom hasil direname jadi **Status Pasien Terakhir**
- [x] Untuk usia tampilkan tahun saja

---
### Filter

- [x] Filter status direname jadi **Kriteria**
- [x] Filter hasil direname jadi **Status Pasien Terakhir**
- [x] Filter Tahapan Dihilangkan

- [x] Isi filter Kriteria :

1. OTG
2. ODP
3. PDP
4. KONFIRMASI
5. KONTAK ERAT
6. SUSPEK
7. PRROBABEL

- [x] Isi filter Status Pasien Terakhir

1. 1 = Selesai Isolasi/Sembuh
2. 2 = Meninggal
3. 3 = Discarded
4. 4 = Masih Sakit (diisolasi) 
5. 5 = Masih dikarantina

**Comment by erlangganugraha** [comment]
**Filternya masih belum sesua**i dan **data status pasien terakhirnya ada yg Negatif** @Arif9878 @firmanJS 
![list kasus 2](https://user-images.githubusercontent.com/11548871/88514359-26607380-d014-11ea-8a25-9520e20c2ccd.png)
![list kasus](https://user-images.githubusercontent.com/11548871/88514382-2eb8ae80-d014-11ea-8c9d-36d0d3ea9981.png)

**Comment by firmanJS** [comment]
@erlangganugraha no telepon emang ga ada di tabel
@Arif9878 cek ketika kirim discarded harusnya valuenya 3
