### ISSUE TITLE
[Laporan Kasus] List verifikasi kasus rev 5

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#575]
## AC

- [x] Kolom tahapan dihilangkan
- [x] Kolom hasil direname jadi **Status Pasien Terakhir**
- [ ] Untuk usia tampilkan tahun saja

---
### Filter

- [x] Isi filter Kriteria :

1. OTG
2. ODP
3. PDP
4. KONFIRMASI
5. KONTAK ERAT
6. SUSPEK
7. PROBABEL

**Comment by alifianif** [comment]
Kolom Usia tertulisnya "Tahun Th" seharusnya "Tahun"
![image](https://user-images.githubusercontent.com/17422311/88673268-9bb26e00-d112-11ea-976f-7d8df41d1c37.png)
@Arif9878

**Comment by Arif9878** [comment]
wkwkkwk lupa hapus 'th' nya @alifianif
