### ISSUE TITLE
[Laporan Kasus] Input data pemeriksaan penunjang

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#583]
> Pemeriksaan penunjang ini bertujuan untuk mencatat data pemeriksaan pasien baik itu swab atau rapid atau pemeriksaan lainnya jika ada

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC

- [x] Layout disamakan dengan desain
- [x] Dibuat Responsive
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Terdapat inputan Pengambilan Spesimen Ke ; (input type number)
- [x] Jenis Spesimen dibuat dropdown, Option Jenis Spesimen ;

1. Swab Nasofaring
2. Swab Orofaring
3. Swab Naso-Orofaring
4. Sputum
5. Bal Fluid
6. Cairan Spirasi Trakhea
7. Serum
8. Darah
9. Lainnya

## UX
- [x] Jika jenis pemeriksaanya dipilih Lab Konfirmasi maka :

> - Option hasil pemeriksaannya Positif, Negatif, Inkonklusif, Invalid, Dalam Proses

- [x] Jika jenis pemeriksaanya dipilih Pemeriksaan lain maka :

> - Option hasil pemeriksaannya Reaktif, Non Reaktif, Positif, Negatif, Inkonklusif, Invalid, Dalam Proses

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/89751819-f0cf8600-dafb-11ea-96ff-a45de3bf31ce.png)

contoh field nya nnti ketika input kasus

 ` "physical_check_temperature": "37",
  "physical_check_blood_pressure": "5",
  "physical_check_pulse": "5",
  "physical_check_respiration": "4",
  "physical_check_height": "44",
  "physical_check_weight": "44",
	"inspection_support": [
		{
			"inspection_type": "lab_cofirm",
			"specimens_type": "Darah",
			"inspection_date":  "2020-08-06",
			"inspection_location": "LAB Pajajaran",
			"get_specimens_to": 1,
			"inspection_result": "confirmation"
		},
		{
			"inspection_type": "lab_cofirm",
			"specimens_type": "Darah",
			"inspection_date":  "2020-08-07",
			"inspection_location": "LAB Pajajaran",
			"get_specimens_to": 2,
			"inspection_result": "confirmation"
		}
	],`

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/89751919-5754a400-dafc-11ea-80a9-2e6ec03da5ad.png)
masuk ke field contoh di bawah .. 

`	"is_other_diagnosisr_respiratory_disease" : true,
	"other_diagnosisr_respiratory_disease": "sering batuk2",`

**Comment by sandisunandar99** [comment]
cc : @Arif9878 @Arif9878 @erlangganugraha

**Comment by shintadewiaw** [comment]
### **Feedback 11 Agustus 2020**

**RIWAYAT PERJALANAN**
- Jika jenis perjalanan "Dari Luar Kota" maka yang tampil Nama Kota bukan Negara


**APAKAH PERNAH TINGGAL KE AREA TRANSMISI LOKAL**
- Dropdown "Provinsi" berisi jenis spesimen(?)
- Dropdown "Kota" berisi jenis spesimen(?)

**RIWAYAT BEPERGIAN**
- Dropdown "Kategori Tempat" berisi Jenis Spesimen
- Field "Nama tempat yang dikunjungi" jika diisi malah otomatis ngisi field "Alamat tempat yang dikunjungi"
- Field "Lama kunjungan/durasi" jika diisi malah otomatis ngisi field "Nama tempat yang dikunjungi" & "Alamat tempat yang dikunjungi"


**KONTAK PRIMER**
- Placeholder "Nama Kontak" seharusnya "Masukkan Nama Kontak Primer"\
- Field alamat seharusnya lengkap sesuai design (ada kota/kab,kecamatan,kelurahan,dll)
- Field "Nama Kontak" jika diisi malah otomatis ngisi field "Alamat"
- 

**APAKAH PASIEN TERMASUK CLUSTER ISPA BERAT**
- Tambahkan keterangan sesuai dengan design (Demam dan pneumonia yang membutuhkan perawatan di Rumah Sakit, dan tidak diketahui penyebabnya) 

**APAKAH PASIEN MEMILIKI HEWAN PELIHARAAN**
- Jika milih salah satu diantara "Ya/Tidak" otomatis ngisi field "Apakah pasien merupakan petugas kesehatan?" dan field "Apakah melakukan prosedur yang menimbulkan erosol?"

**APAKAH PASIEN MERUPAKAN PETUGAS KESEHATAN**
- Jika milih salah satu diantara "Ya/Tidak" otomatis ngisi field "Apakah pasien memiliki hewan peliharaan?" dan field "Apakah melakukan prosedur yang menimbulkan erosol?"

**APAKAH MELAKUKAN PROSEDUR YANG MENIMBULKAN EROSOL**
- Jika memilih salah satu diantara "Ya/Tidak" otomatis ngisi field "Apakah pasien merupakan petugas kesehatan?" dan field "Apakah pasien memiliki hewan peliharaan?"

**Comment by Arif9878** [comment]
@shintadewiaw ini kan card nya memang untuk pemeriksaan penunjang, kalau multiple form yang lain udah ada card masing"

**Comment by shintadewiaw** [comment]
@Arif9878 oh iya maapin

**Comment by sandisunandar99** [comment]
@shintadewiaw udah jangan banyak di pikirin ,, yang semalam lupakan aja ,, 🤔 😸

**Comment by shintadewiaw** [comment]
pada browser mozilla "Pengambilan Spesimen Ke-" tidak bertipe number
![image](https://user-images.githubusercontent.com/63390998/89972178-57cd7600-dc87-11ea-8a5b-3bfd7d4af3c3.png)

@Arif9878

**Comment by Arif9878** [comment]
@shintadewiaw coba di refresh sin
![Screen Shot 2020-08-12 at 10 45 29](https://user-images.githubusercontent.com/20775950/89972812-fdcdb000-dc88-11ea-9e67-136df0b57b4d.png)

**Comment by shintadewiaw** [comment]
@Arif9878 masih mas wkwk kenapa ya, udah di clear cache juga
![image](https://user-images.githubusercontent.com/63390998/89972984-674dbe80-dc89-11ea-8f3c-d9c87b957852.png)

**Comment by shintadewiaw** [comment]
@Arif9878 pake mozilla firefox mas bukan chrome

**Comment by Arif9878** [comment]
@shintadewiaw ngobrol dong hhhhh

**Comment by shintadewiaw** [comment]
@Arif9878 
pada browser mozilla "Pengambilan Spesimen Ke-" tidak bertipe number
Baca atuh mas :(
