### ISSUE TITLE
[Laporan Kasus] Input data faktor riwayat perjalanan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#584]
> faktor riwayat perjalanan ini bertujuan menncatat data riwayat perjalanan pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Ref
![Screenshot_2020-08-04 REV-05_Pedoman_P2_COVID-19_13_Juli_2020 pdf](https://user-images.githubusercontent.com/11548871/89317271-56a8b180-d6a7-11ea-951c-3d618fa9e92b.png)

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC

- [x] Layout disamakan dengan desain
- [x] Dibuat Responsive
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah memiliki riwayat perjalanan ?" diset mandatory 
- [x] Input negara dibuat dropdown
- [x] Input provinsi dibuat dropdown
- [x] Input kota dibuat dropdown

## UX

- [x] Jika Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ? dipilih **Ya** maka :

> - Jenis Perjalanan, Negara, Provinsi, kota diset mandatory

- [x] Jika Dalam 14 hari sebelum sakit, apakah memiliki riwayat dari luar negeri/luar kota ? dipilih **Tidak** maka :
> - Reset form riwayat perjalanan
> - Jenis Perjalanan, Negara, Provinsi, kota unset mandatory

- [x] Jika jenis perjalanannya dipilih dari luar negeri maka :

> Inputan tempat perjalanan adalah ; Negara & kota

- [x] Jika jenis perjalanannya dipilih dari luar Kota maka :

> Inputan tempat perjalanan adalah ; Provinsi & kota

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by Arif9878** [comment]
@erlangganugraha ini tanya dulu ke BE untuk provinsi sama kota klu mau di buat dropdown udah ada apinya belum

**Comment by erlangganugraha** [comment]
@Arif9878 aman cok, sturktur datanya udah ada. Tinggal dibuat APInya. Udah gw tambahin diAC jg dicard BEnya

**Comment by erlangganugraha** [comment]
Tinggal strukut data negara & kota blm ada cc @sandisunandar99

**Comment by sandisunandar99** [comment]
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/411#issuecomment-671259900

**Comment by shintadewiaw** [comment]
Saat memilih dropdown Kota pada "Riwayat Perjalanan 2" maka dropdown Kota pada "Riwayat Perjalanan 1" otomatis pilihan dari Provinsi "Riwayat Perjalanan 2"

![s](https://user-images.githubusercontent.com/63390998/90098134-be26c700-dd61-11ea-9698-8fa507f8202b.png)

@Arif9878

**Comment by shintadewiaw** [comment]
mas yang ini belum di set mandatory
![image](https://user-images.githubusercontent.com/63390998/90216940-188b5a80-de2a-11ea-9d8e-f4cc2f4a36a4.png)
@Arif9878

**Comment by shintadewiaw** [comment]
mas waktu disimpan ada error
![image](https://user-images.githubusercontent.com/63390998/90217145-ae26ea00-de2a-11ea-84df-46fd02db8963.png)

@Arif9878 @sandisunandar99

**Comment by sandisunandar99** [comment]
> mas waktu disimpan ada error
> ![image](https://user-images.githubusercontent.com/63390998/90217145-ae26ea00-de2a-11ea-84df-46fd02db8963.png)
> 
> @Arif9878 @sandisunandar99 

Itu ga boleh kosong sin.. di mandatory di BE nya @shintadewiaw

**Comment by shintadewiaw** [comment]
nah berarti validasiin di depan mas arip @Arif9878

**Comment by Arif9878** [comment]
sin yang kontak primer atau kontak paparan cardnya aja belum aku pindah di E2E karna ada tambahan api, ini card faktor riwayat perjalanan @shintadewiaw

**Comment by shintadewiaw** [comment]
oh ini error validasi untuk kontak paparan ya, aku gatau kalo formnya dibuka ikut ke validasi mas

**Comment by shintadewiaw** [comment]
@Arif9878 yaudah tambahin validasi yang di AC tadi ya mas

**Comment by Arif9878** [comment]
yoi shin
