### ISSUE TITLE
[Laporan Kasus] Input data faktor riwayat bepergian ke tempat publik

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#585]
> faktor riwayat bepergian ke tempat publik ini bertujuan mencatat data riwayat pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC

- [x] Layout disamakan dengan desain
- [x] Dibuat Responsive
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ?" diset mandatory 
- [x] Option Kategori Tempat ; Pasar Modern/Tradisional, Pasar Hewan, Fasilitas Kesehatan, Tempat Wisata, Tempat Ibadah, Restoran, Tempat Publik Lainnya
- [x] Input Nama tempat yang dikunjungi terdapat placeholder
- [x] Type Input date time untuk Tanggal & waktu berkunjung 
- [x] Type Input number untuk Lama kunjungan/durasi

## UX

- [x] Jika Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ? dipilih **Ya** maka :

> Kategori tempat diset mandatory

- [x] Jika Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ? dipilih **Ya** maka :
> - Nama tempat diset mandatory
> - Kategori tempat diset mandatory

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by sandisunandar99** [comment]
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/412#issuecomment-671178894

**Comment by sandisunandar99** [comment]
cc: @Arif9878

**Comment by Arif9878** [comment]
@erlangganugraha ini untuk apa di reset?  Jika Dalam 14 hari sebelum sakit, apakah pernah mengunjungi RS/ Pasar/tempat publik lainnya ? dipilih Ya maka :
Reset form riwayat bepergian

**Comment by erlangganugraha** [comment]
Lah baru ngeh gw juga cok @Arif9878 , harusnya nama tempat diset mandatory

**Comment by shintadewiaw** [comment]
guys ini jadinya nama tempat di set mandatory? @erlangganugraha @Arif9878

**Comment by shintadewiaw** [comment]
mas @Arif9878 kalau habis simpan terus input baru lagi, form riwayat bepergian di reset ya, sekalian yang faktor riwayat perjalanan juga di reset
