### ISSUE TITLE
[Laporan Kasus] Perubahan badge pada list kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#588]
## Desain
![List Kasus](https://user-images.githubusercontent.com/42407562/89602916-10637600-d892-11ea-9c71-f45e74273f73.png)

## AC

- [x] Layout disamakan dengan desain
- [x] Dibuat Responsive
- [x] Jumlah angka perstatus bisa berubah sesuai data yg difilter

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by erlangganugraha** [comment]
@Arif9878 udah ada desainnya cok

**Comment by Arif9878** [comment]
@erlangganugraha jumlah angka perstatus bisa berubah saat pencarian keperluanya apa ya?

**Comment by erlangganugraha** [comment]
@Arif9878 keperluanya untuk melihat jumlah angka yg difilter, jd ga cuman show data listnya aja ketika difilter. User bisa melihat jumlah angkanya jg

**Comment by Arif9878** [comment]
gw tanya pencarian bukan filternya

**Comment by erlangganugraha** [comment]
Sama aja, memang kenapa cok ? Ada kendala atau masukkan dr lu baiknya gimana ?

**Comment by Arif9878** [comment]
mirip tapi beda filter bisa spesifik jenisnya kalau pencarian itu bisa berupa nik, nama, no kasus.
nah kalau dia pencarian NIK nih hasilnya 1 masa Jumlah angka perstatus juga berubah?

**Comment by erlangganugraha** [comment]
noted cok @Arif9878 nanti urg sampein ke BE

**Comment by shintadewiaw** [comment]
@Arif9878 mas arip button exportnya yang mobile nempel, kebawahin lagi ya
![image](https://user-images.githubusercontent.com/63390998/89978122-f90ff880-dc96-11ea-9a83-44b690471350.png)

**Comment by erlangganugraha** [comment]
![Screenshot_2020-08-18 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/90475092-fad33380-e150-11ea-8e8b-3f60ad09a458.png)
warna bordernya blm sesuai dgn desain @Arif9878

**Comment by erlangganugraha** [comment]
![Screenshot_2020-08-18 pelaporan-covid19(2)](https://user-images.githubusercontent.com/11548871/90475676-1ab72700-e152-11ea-92c5-6e17ff5a6512.png)
Output jumlah angka seharusnya terkonfirmasi = 0, suspek = 0, kontak erat = 0 karena yg difilter hanya probable doang 
@Arif9878

**Comment by Arif9878** [comment]
tanya sama si hadi @khihadysucahyo

**Comment by khihadysucahyo** [comment]
@erlangganugraha @Arif9878 badge itu bukannya ga ada kaitannya dengan filter ya? Apalagi badge ini fungsinya sebenarnya sudah memfilter per kriteria dari awal yg gunanya sbg ringkasan.. 

Tapi kalau memang output badgenya mau berubah sesuai kriteria yg di filter, dari BE sudah disediakan kok tinggal dikirim aja param "status" nya @Arif9878

**Comment by erlangganugraha** [comment]
output badgenya berubah sesuai kriteria yg di filter. @khihadysucahyo @Arif9878

**Comment by khihadysucahyo** [comment]
@erlangganugraha okok,
Tinggal kirim param query status aja mas @Arif9878, di postmannya ada

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/90603530-a1890400-e225-11ea-9b95-9840ab738e38.png)

Setelah memfilter berdasarkan kriteria, kemudian klik reset, perhitungan total data pada dashboard tidak kembali seperti semula

@Arif9878 @khihadysucahyo
