### ISSUE TITLE
[Laporan Kasus] Generate Latitude & longtitude

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#589]
## Desain
![Screenshot_2020-08-06 Figma](https://user-images.githubusercontent.com/11548871/89489453-c10b4000-d7d4-11ea-8abd-ed92e0f56006.png)

## AC
- [x] Detail Alamat diset mandatory
- [x] Generate Latitude & longtitude berdasarkan alamat tempat tinggal sampe ke detail alamat (Jalannya)
- [x] Inputan lat & long dibuat disabled

## Responsiveness
- [ ] Mobile
- [ ] Tablet
- [ ] Desktop

## Browser
- [ ] Mozilla Firefox

**Comment by shintadewiaw** [comment]
mas tambahin pesan error di alamat lengkap kalau ga di isi yaa

**Comment by Arif9878** [comment]
ini kalau detail alamat di mandatory kayaknya bakal rame sin @shintadewiaw  @erlangganugraha

**Comment by shintadewiaw** [comment]
wkwk iyasi bener, gimana ni kaka @erlangganugraha
