### ISSUE TITLE
[Laporan Kasus] Multiple Input Faktor Kontak Paparan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#590]
> faktor Kontak Paparan ini bertujuan mencatat data riwayat pasien selama 14 hari kebelakang, guna sebagai salah satu acuan faktor resiko.

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A3168&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

## AC

- [x] Layout disamakan dengan desain
- [x] Dibuat Responsive
- [x] Bisa > 1 data input
- [x] Bisa menghapus data
- [x] Pertanyaan ; "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya?" diset mandatory 
- [x] Hubungan seharusnya dibuat select option, isinya ;

- Keluarga serumah
- Teman Kerja
- Jamaah ditempat ibadah
- Lainnya

## UX

- [x] Jika Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya? dipilih **Ya** maka :

> - Nama Kontak diset mandatory
> - Kriteria Kontak diset mandatory

- [x] Hubungan, jika dipilih "Lainnya", maka ;

> - Show inputan lainnya dibawah 

## Responsiveness
- [x] Mobile
- [x] Tablet
- [x] Desktop

## Browser
- [x] Mozilla Firefox

**Comment by sandisunandar99** [comment]
kalo boleh saran mending hubugn ini di buat text aja,,, soalnya banyak jenis ga harus di batasi dan jadi enak bisa ketahuan
misal hubungan nya: pembokat, mantan, pacar, pembantu, dst,, wkwkwk
@erlangganugraha 
cc : @Arif9878 @shintadewiaw

**Comment by sandisunandar99** [comment]
![image](https://user-images.githubusercontent.com/6767399/90097291-c67e0280-dd5f-11ea-8cfa-fbc1714da704.png)

untuk yang gamba di atas mang @Arif9878 nnti masuk kesni y

"close_contacted_before_sick_14_days": true,
"close_contact_premier" : [
	 {
		"close_contact_name": "Dadang",
		"close_contact_criteria": "Suspect",
		"close_contact_address": "bandung",
		"close_contact_relation": "ipan",
		"close_contact_relation_id": "Objectid()",
		"close_contact_first_date": "2020-08-01",
		"close_contact_last_date": "2020-08-23"
	},
	{
		"close_contact_name": "Pupung",
		"close_contact_criteria": "Suspect",
		"close_contact_address": "bandung",
		"close_contact_relation": "ipan",
		"close_contact_relation_id": "Objectid()",
		"close_contact_first_date": "2020-08-01",
		"close_contact_last_date": "2020-08-23"
	}
],
"close_contact_heavy_ispa_group" : true,
"close_contact_have_pets": true,
"close_contact_pets": "Macan",
"close_contact_health_worker": true,
"apd_use": ["GOWN", "PPP3"],
"close_contact_performing_aerosol_procedures": true,
"close_contact_performing_aerosol": "bakar kandang ayam",


================ =======================
dan untuk sementara mungkin field2 ini saya coment dlu karena ga di pake ,, trus biar ga berat juga saat proses POST data
jadi di payload filed2 dibawah ga papa ga usah di masukan

"travel": "",
"visited": "china",
"travel_is_went_abroad":"",
"start_travel": "",
"end_travel": "",
"close_contact": 1,
"id_close_contact": "objectid()",
"name_close_contact": "",
"close_contact_confirm": 1,
"id_close_contact_confirm": "objectid()",
"name_close_contact_confirm": "",
"close_contact_animal_market": 1,
"animal_market_date": "",
"animal_market_other": "",
"close_contact_public_place": 2,
"public_place_date": "",
"close_contact_medical_facility": 3,
"medical_facility_date": "",
"medical_facility_other": "",
"close_contact_heavy_ispa_group": 2,
"close_contact_health_worker": 1,
"health_workers": "",

**Comment by sandisunandar99** [comment]
sama field yang ini boleh di takeout aja soalnya uda ga kepake,, dan itu masuk ke jenis spesimen di pemeriksaan penunjang 

coreksi aja bisi  saya salah 
@erlangganugraha  @Arif9878

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/90608798-4f4be100-e22d-11ea-8cd4-7bcacfdfc365.png)

mas sesuai UX, kalau pilih "Tidak" seharusnya ga mandatory

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/90609417-309a1a00-e22e-11ea-96e9-f3a162406e8f.png)

mas ini kalau pilih "Tidak" form yang kontak primer harusnya ga mandatory

**Comment by Arif9878** [comment]
cc BE sin

**Comment by shintadewiaw** [comment]
okaay mas

**Comment by sandisunandar99** [comment]
Oke @shintadewiaw yang kontak paparan lagi di bnerin dlu supaya bisa edit.. wait ya
