### ISSUE TITLE
[Verifikasi Kasus] Revisi Proses Verifikasi

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#598]
## Design

- Hide
![Detail Kasus Verifikasi](https://user-images.githubusercontent.com/42407562/90463760-ef264380-e135-11ea-8ca4-ff0b6c79ee50.png)

- Show
![Detail Kasus Verifikasi - Full](https://user-images.githubusercontent.com/42407562/90463780-f9e0d880-e135-11ea-9c0b-fde5759f5b2d.png)

## Issue
Data yang ditampilkan untuk memverifikasi tidak semua data yg dishow

## Revisi

- [ ] Data yang ditampilkan = seperti buat laporan kasus

**Comment by ReksaMohammad** [comment]
Ini untuk yg hide

![Detail Kasus Verifikasi](https://user-images.githubusercontent.com/42407562/89998986-6d0ec880-dcb8-11ea-9ed2-87904e9d5e36.png)

Ini yg full

![Detail Kasus Verifikasi - Full](https://user-images.githubusercontent.com/42407562/89999020-7861f400-dcb8-11ea-96ef-eca00c3956fc.png)

**Comment by shintadewiaw** [comment]
### Feedback Proses Verifikasi (25 Agustus 2020)
1. Pemeriksaan Penunjang, Jika Pemeriksaan Fisik kosong sebaiknya diberi tanda (-)

2.  Verifikasi Kasus - Memilih Gejala "Ya" tetapi pada detail munculnya "Tidak"
![image](https://user-images.githubusercontent.com/63390998/91165495-ed8ee980-e6fa-11ea-9ccf-119f0fa68a01.png)

![image](https://user-images.githubusercontent.com/63390998/91165468-e071fa80-e6fa-11ea-8188-2f3ad32bfd9a.png)

3. Jika status terakhir "Meninggal" jangan ditulis (-)
![UMUR](https://user-images.githubusercontent.com/63390998/91165590-1adb9780-e6fb-11ea-98f7-c6848dff20af.png)

4. 
- Riwayat Sosial Ekonomi, Aktivitas Fisik memilih "Sendimenter" tetapi munculnya "0"
- Riwayat Sosial Ekonomi, memilih merokok "Ya" tetapi munculnya "Tidak"
- Riwayat Sosial Ekonomi, memilih konsumsi berarkohol "Ya" tetapi munculnya "Tidak"
- Riwayat Sosial Ekonomi, memilih penghasilan "Tidak berpenghasilan" munculnya "0" sebaiknya ditampilkan Tidak Berpenghasilan

![image](https://user-images.githubusercontent.com/63390998/91167397-1664ae00-e6fe-11ea-9cc1-3f6276f4d627.png)

![image](https://user-images.githubusercontent.com/63390998/91167380-106ecd00-e6fe-11ea-95e6-e4b7f96e1c72.png)

**Comment by shintadewiaw** [comment]
mas arip nomor 1,3,4 belum ada perubahan :(

**Comment by Arif9878** [comment]
@shintadewiaw ini nyobainnya data baru apa data lama?

**Comment by shintadewiaw** [comment]
> @shintadewiaw ini nyobainnya data baru apa data lama?
> 
> 

Baru mas

**Comment by Arif9878** [comment]
![Screen Shot 2020-08-27 at 14 30 34](https://user-images.githubusercontent.com/20775950/91410985-e9390c80-e871-11ea-964e-ffc3a7bcc252.png)
udah sin check lagi

**Comment by shintadewiaw** [comment]
mas arip @Arif9878 setelah di cek cek lagi banyak form yang ga masuk valuenya, ni aku list-in yaa:
1. Gejala, Kondisi Penyerta, Diagnosis ARDS (Acute Respiratory Distress Syndrome), Diagnosis COVID-19, Diagnosis Pneumonia
![image](https://user-images.githubusercontent.com/63390998/91452878-5025e800-e8a9-11ea-8ab3-70da3279d836.png)
![image](https://user-images.githubusercontent.com/63390998/91452838-42706280-e8a9-11ea-8b03-f19947a54f2d.png)


2. Semua form di faktor riwayat perjalanan kalau pilih "Ya" datanya masuknya "Tidak"
![image](https://user-images.githubusercontent.com/63390998/91452054-5798c180-e8a8-11ea-81e1-17ea31840868.png)
![image](https://user-images.githubusercontent.com/63390998/91452084-62535680-e8a8-11ea-84ec-da1c48b71268.png)

3. Semua form di faktor riwayat perjalanan
![image](https://user-images.githubusercontent.com/63390998/91453032-79df0f00-e8a9-11ea-8f0d-6d04631cb058.png)
![image](https://user-images.githubusercontent.com/63390998/91453231-b01c8e80-e8a9-11ea-9777-3e674808009a.png)



4. Semua Form di faktor kontak paparan
![image](https://user-images.githubusercontent.com/63390998/91453121-8feccf80-e8a9-11ea-9ccf-b8481d35f837.png)
![image](https://user-images.githubusercontent.com/63390998/91453198-a6932680-e8a9-11ea-97cc-473c56bcfd07.png)

5. Merokok, Konsumsi Minuman Beralkohol,  kalau pilih "Ya" datanya masuknya "Tidak"

6. Ini tambahin (-) kalo datanya kosong ya mas
![image](https://user-images.githubusercontent.com/63390998/91453339-caef0300-e8a9-11ea-9682-8d7e1359570c.png)


SEMANGAAAAAT 🥇

**Comment by shintadewiaw** [comment]
1. Kondisi penyerta belum masuk 
![Tampilan](https://user-images.githubusercontent.com/63390998/91681920-27884180-eb7a-11ea-8ad7-1b84cfba14b5.png)
![Tampilan](https://user-images.githubusercontent.com/63390998/91682050-7b932600-eb7a-11ea-8715-f503e035ba70.png)

2. Alat Pelindung yang Digunakan valuenya belum masuk
