### ISSUE TITLE
[Laporan Harian] Implement API laporan harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#615]
## Rumus
![Aplikasi Pelaporan@2x(33)](https://user-images.githubusercontent.com/11548871/89815559-337e7600-db6f-11ea-95d2-7156071e3821.png)

## AC
- [ ] Value untuk Kolom Dinas Kesehatan Provinsi ; Jawa Barat
- [ ] Value untuk kolom dinas kesehatan kota/kab berdasarkan user login
- [ ] Value untuk kolom Nama Petugas berdasarkan Nama Lengkap user login & No Hp, dgn format (Nama Lengkap - No Hp). Contoh isian ; Dinas Kesehatan Kota Cimahi - 089682632631

Count data sbb ;

- [ ] Total yg dihitung adalah kotak yg berwarna orange (*lihat pada rumus)
- [ ] Total yg dihitung perhari ini
- [ ] Total yg dihitung dalam 1 minggu terakhir
- [ ] Total yg dihitung dalam 1 bulan terakhir
- [ ] Terdapat filter berdasarkan tgl update riwayat
- [ ] Bisa diexport ke excel
- [ ] Bisa diexport to image

## Browser
- [ ] Mozilla Firefox

**Comment by erlangganugraha** [comment]
![Screenshot_2020-08-26 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/91256713-4198dd00-e792-11ea-9623-7941bebbfd8f.png)

Saat difilter tanggal, kolom tanggal tidak berubah
Plus Nama Petugas diisi sbb ; Value untuk kolom Nama Petugas berdasarkan Nama Lengkap user login & No Hp, dgn format (Nama Lengkap - No Hp). Contoh isian ; Dinas Kesehatan Kota Cimahi - 089682632631

@Arif9878

**Comment by shintadewiaw** [comment]
mas @Arif9878 biar rapi yang Jawa barat,Dinkes kota bandung dll jaraknya jangan jauh jauh ya, terus yang total angka itu dibuat center semua aja mas
![DB](https://user-images.githubusercontent.com/63390998/91388257-247f0f80-e861-11ea-930a-deb50c00a27c.png)

**Comment by shintadewiaw** [comment]
mas arip naha ga ada perubahan
![image](https://user-images.githubusercontent.com/63390998/91451125-4c916180-e8a7-11ea-89e6-2ebbe160dd69.png)
