### ISSUE TITLE
[Laporan Kasus] Autofocus on required event submit

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#622]
## UX

- [x] Jika user submit dan ada input field required belum terisi, maka arahkan kedalam field input tersebut

## Browser
- [x] Mozilla Firefox

**Comment by shintadewiaw** [comment]
mas @Arif9878 error waktu mau di submit

![image](https://user-images.githubusercontent.com/63390998/91168279-92abc100-e6ff-11ea-9fe8-94da194648b3.png)

**Comment by Arif9878** [comment]
udah di refresh belum shin ini pagenya?
