### ISSUE TITLE
[Laporan Harian] Penambahan Filter

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#624]
## User Story
Sebagai dinkes prov saya ingin melihat laporan harian secara spesifik pada dinkes kota/kab tertentu.

## UI
![Laporan Harian](https://user-images.githubusercontent.com/42407562/91450234-4bac0000-e8a6-11ea-9a43-a1e6262ec640.png)

## AC

- [ ] Penambahan filter author dinkes kota/kab
- [ ] Filter hanya bisa digunakan oleh dinkes prov/superadmin

## UX

- [ ] Disabled filter ketika login sbg level dinkes kota/kab maupun faskes

**Comment by shintadewiaw** [comment]
mas tanggal yang di tulisan rekap, disamain sama tanggal pas di filter ya
![Tampilan](https://user-images.githubusercontent.com/63390998/91680651-1b9a8080-eb76-11ea-8d4a-5639c56875ed.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 jamnya jadi 00.00 semua
![image](https://user-images.githubusercontent.com/63390998/91691150-5bbb2c80-eb91-11ea-9b36-fd02ffdab52a.png)

**Comment by Arif9878** [comment]
mending jamnya di hilangin aja ya karna pas filter tanggal ga ada jam maka jamnya ga ada @shintadewiaw

**Comment by shintadewiaw** [comment]
yaudah sok mas
