### ISSUE TITLE
[Edit Kasus] Ketika memasukkan pilihan "Ya" value yang masuk ketika edit kembali "Tidak"

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#633]
mas, ini di semua form kontak paparan, kalau pilih "Ya" ketika edit kembali munculnya "Tidak"
![image](https://user-images.githubusercontent.com/63390998/91687833-f5331000-eb8a-11ea-85d4-b2f5049b1af6.png)

**Comment by Arif9878** [comment]
@shintadewiaw  ya emang belum sin, dulu kan pernah ku tanya kan ini ada card revamp create case tapi ga ada card revamp edit case.

**Comment by shintadewiaw** [comment]
oh iyaya hahaha lupa mas, er bikinin card revamp edit kasus dong @erlangganugraha
