### ISSUE TITLE
[Laporan Kasus] Improvement Buat Laporan Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#639]
## Goal
Improvisasi page buat laporan kasus

## UI
<img width="1440" alt="Suspek" src="https://user-images.githubusercontent.com/11548871/92346625-80665580-f0f7-11ea-86d6-7964730f3a16.png">

link prototype; https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=4596%3A319&scaling=scale-down-width&viewport=679%2C245%2C0.07371740788221359

### General

- [x] Semua inputan tanggal lahir, sebaiknya dengan format; Tanggal, bulan, tahun
- [x] Utk mupltiple input, semua pertanyaan jika pilih tidak, opsi "+ tambah" bisa disembunyikan
- [ ] Ketika opsi "+ tambah" diklik, fokus kepada content inputan & opsi "+ tambah" turun kebawah

### Informasi Klinis
- [x] Input Diagnosis Covid-19 ambigu, sebaiknya dihilangkan

- [x] Kondisional gejala:
Jika **ya**, muncul pilihan gejala yang dirasakan dan tanggal muncul gejala
Jika **tidak**, pilihan gejala tidak muncul

### Pemeriksaan Penunjang
- [x] Title group sebaiknya diganti menjadi "Pemeriksaan Penunjang/Hasil Test"

### Faktor Kontak/Paparan
- [x] Hewan peliharaan, kalo tidak ada, opsi "sebutkan" bisa disembunyikan
- [x] “Apakah pasien petugas kesehatan” kalo **tidak**, pilihan APD & prosedur erosol disembunyikan
---
- Jika "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probable/konfirmasi COVID-19 lainnya ?" dipilih 
  

- [x] **tidak**, opsi +tambah bisa disembunyikan

  

- [ ] **Ya** muncul button +tambah & nama kasus dibuat jadi pencarian. Detail sbb;

  Input nama kasus dibuat pencarian
  Autofill dibagian Kriteria Kontak, Rumah sama dengan pasien

**Comment by erlangganugraha** [comment]
@ReksaMohammad @Arif9878 kayanya link mockupnya salah deh itu wkwk. Yang diimprove soalnya bagian page form inputnya cc @ReksaMohammad

**Comment by Arif9878** [comment]
@shintadewiaw sin ini yang form berkaitan dengan kontak erat di pass dulu ya karna masih di bahas yang kontak eratnya

**Comment by shintadewiaw** [comment]
**Feedback 8 September 2020**
1. Ketika pilih "Ya" pada Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya ?
maka, redirect ke form 
Pemeriksaan Penunjang/Hasil Test 1

2.  **Belum sesuai AC** (Jika "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probable/konfirmasi COVID-19 lainnya ?" 
dipilih "Ya" seharusnya muncul button +tambah & nama kasus dibuat jadi pencarian. Detail sbb;
Input nama kasus dibuat pencarian

**Comment by Arif9878** [comment]
@shintadewiaw point no 2 Belum sesuai AC (Jika "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probable/konfirmasi COVID-19 lainnya ?"
nunggu api fixnya gimana ya
