### ISSUE TITLE
[List Kasus] CRUD Dari luar kota/negeri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#643]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data dari luar kota/negeri yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD dari luar kota/negeri.**

## UI
![Luar Kota](https://user-images.githubusercontent.com/42407562/92105120-8fee5180-ee0c-11ea-8b48-70682e679286.png)

link prototype : https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=-5144%2C-12956%2C0.4254467487335205&scaling=min-zoom

## AC
- [x] Responsive

#### 1. Page List Dari Luar Kota/Negeri

- [x] Menampilkan data dari luar kota/negeri, layout disamakan dengan desain
- [x] Order by tgl update desc
- [x] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [x] Terdapat buttom Tambah data dari luar kota/negeri, **jika diklik** direct ke form input data dari luar kota/negeri 

#### 2. Page Form Input Data dari luar kota/negeri
- [x] Field inputan disamakan dengan desain
- [x] Bisa input data
- [x] Direct ke list dari luar kota/negeri, jika proses input berhasil

#### Page Form Edit Data dari luar kota/negeri
- [x] Field inputan disamakan dengan desain
- [x] Bisa edit data
- [x] Direct ke list dari luar kota/negeri, jika proses edit berhasil

## Browser
- [x] Mozilla

**Comment by shintadewiaw** [comment]
1. Rapikan tulisan List Riwayat Area Transmisi
![image](https://user-images.githubusercontent.com/63390998/93189489-64ecf180-f76c-11ea-86f2-60321a5e45d9.png)

2. Rapikan tombol Batal & Simpan
![image](https://user-images.githubusercontent.com/63390998/93189434-54d51200-f76c-11ea-987f-c8de0ecd71ed.png)
