### ISSUE TITLE
[List Kasus] CRUD Ke transmisi lokal

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#644]
## User Story
Sebagai user faskes/dinkes. Saya ingin melihat, menambah, mengubah ataupun menghapus data Ke transmisi lokal yang sudah saya input saat buat laporan kasus baru. **Maka dari itu perlu ada fitur CRUD Ke transmisi lokal.**

## UI

![List Kasus - Riwayat Area Transmisi Lokal](https://user-images.githubusercontent.com/42407562/92105391-f96e6000-ee0c-11ea-9138-c4da04790ac9.png)

link prototype : https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=-5144%2C-12956%2C0.4254467487335205&scaling=min-zoom

## AC
- [x] Responsive

#### 1. Page List Ke transmisi lokal

- [x] Menampilkan data Ke transmisi lokal, layout disamakan dengan desain
- [x] Order by tgl update desc
- [x] Terdapat pilih aksi (CTA); Edit Data & Hapus Data
- [x] Terdapat buttom Tambah data Ke transmisi lokal, **jika diklik** direct ke form input data Ke transmisi lokal 

#### 2. Page Form Input Data Ke transmisi lokal
- [x] Field inputan disamakan dengan desain
- [x] Bisa input data
- [x] Direct ke list Ke transmisi lokal, jika proses input berhasil

#### Page Form Edit Data Ke transmisi lokal
- [x] Field inputan disamakan dengan desain
- [x] Bisa edit data
- [x] Direct ke list Ke transmisi lokal, jika proses edit berhasil

## Browser
- [x] Mozilla

**Comment by firmanJS** [comment]
@Arif9878 api/areas/district-city?kemendagri_provinsi_nama=JAWA BARAT&status=local

**Comment by shintadewiaw** [comment]
1. Sebaiknya auto refresh setelah hapus data transmisi lokal
![image](https://user-images.githubusercontent.com/63390998/92863008-9e002b80-f425-11ea-840d-99238e707db7.png)

2. Formnya kepanjangan mas, diraphin ya wkwk
![TL](https://user-images.githubusercontent.com/63390998/92863512-37c7d880-f426-11ea-800f-dc6f68cb837e.png)

**Comment by shintadewiaw** [comment]
@Arif9878 mas rapihin responsive yang mobile yaa
![image](https://user-images.githubusercontent.com/63390998/93046126-42cb7480-f683-11ea-9147-527fca89227d.png)

**Comment by Arif9878** [comment]
![Screen Shot 2020-09-14 at 13 52 51](https://user-images.githubusercontent.com/20775950/93053175-a78dcb80-f691-11ea-959c-6723f1664be3.png)
@shintadewiaw gini sin?

**Comment by shintadewiaw** [comment]
@Arif9878 lebarin dikit dong mas

**Comment by shintadewiaw** [comment]
lebarin ke kanan mas

**Comment by Arif9878** [comment]
![Screen Shot 2020-09-14 at 14 51 21](https://user-images.githubusercontent.com/20775950/93058586-cabc7900-f699-11ea-8ec4-ae6e2022bc42.png)
@shintadewiaw segini

**Comment by shintadewiaw** [comment]
@Arif9878 okaay mas
