### ISSUE TITLE
[Verifikasi Kasus] Auto Refresh List Verifikasi Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#658]
Deskripsi: Ketika membuka pertama kali verifikasi kasus, tombol aksi tidak muncul, harus di refresh dahulu agar muncul tombol aksinya
![image](https://user-images.githubusercontent.com/63390998/92862318-c3d90080-f424-11ea-8eb3-ecbca1b9a660.png)

**Comment by Arif9878** [comment]
@shintadewiaw ini aku coba buka tombol aksi langsung muncul sin

**Comment by shintadewiaw** [comment]
@Arif9878 bikin dulu dari faskes mas, habis itu baru masuk ke verifikasi kasus

**Comment by Arif9878** [comment]
iya abis bikin faskescipa trus logout trus login ke dinkeskota banjar kan @shintadewiaw

**Comment by shintadewiaw** [comment]
@Arif9878 mas masih belum bisa, besok aja deh kukasih liat di kantor

**Comment by Arif9878** [comment]
oke
