### ISSUE TITLE
Membuat format excel untuk import data

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#689]
## Feedback
1. Untuk negara asal, sebaiknya dibuat dropdown, bisa minta datanya ke mas hady
---
2. Untuk pemeriksaan penunjang, riwayat perjalanan karena sifatynya optional. Sebaiknya diberikan deskripsi pada kolomnya 
contoh : 
![image](https://user-images.githubusercontent.com/11548871/98323845-6aa0de00-201d-11eb-93a9-18f8e33bd038.png)

---
2. Bagian riwayat perjalanan, sebaiknya ada kolom untuk mendeskripsikan 3 kategori riwayat perjalanan. Diantaranya : 1. Perjalanan Dr Luar Kota/Negeri, 2. Perjalanan Ke Transmisi Lokal, dan 3. Perjalanan ke tempat publik
![image](https://user-images.githubusercontent.com/11548871/98323086-991db980-201b-11eb-8b7c-99d9c033854b.png)
---
3. Bagian pemeriksaan penunjang bersifat optional. Tetapi jika ada datanya, maka field Jenis Pemeriksaan, Jenis Spesimen, Tanggal Pemeriksaan, Tempat Pemeriksaan, dan Hasil Pemeriksaan **wajib diisi**
---
cc @nisrinaraisy @shintadewiaw @khihadysucahyo

**Comment by erlangganugraha** [comment]
12 Oktober, Selasa jam 9

https://docs.google.com/spreadsheets/d/1MJYZOAvwE_V4fpl-VjN4DXiml2fAXjmrDSmzrMf01Bg/edit?usp=sharing

**Comment by erlangganugraha** [comment]
jangan dulu diclose @shintadewiaw wkwkwk

**Comment by erlangganugraha** [comment]
1. Untuk negara asal, sebaiknya dibuat dropdown, bisa minta datanya ke mas hady
---
2. Untuk pemeriksaan penunjang, riwayat perjalanan karena sifatynya optional. Sebaiknya diberikan deskripsi pada kolomnya 
contoh : 
![image](https://user-images.githubusercontent.com/11548871/98323845-6aa0de00-201d-11eb-93a9-18f8e33bd038.png)

---
2. Bagian riwayat perjalanan, sebaiknya ada kolom untuk mendeskripsikan 3 kategori riwayat perjalanan. Diantaranya : 1. Perjalanan Dr Luar Kota/Negeri, 2. Perjalanan Ke Transmisi Lokal, dan 3. Perjalanan ke tempat publik
![image](https://user-images.githubusercontent.com/11548871/98323086-991db980-201b-11eb-8b7c-99d9c033854b.png)
---
3. Bagian pemeriksaan penunjang bersifat optional. Tetapi jika ada datanya, maka field Jenis Pemeriksaan, Jenis Spesimen, Tanggal Pemeriksaan, Tempat Pemeriksaan, dan Hasil Pemeriksaan **wajib diisi**
---
cc @nisrinaraisy @shintadewiaw @khihadysucahyo

**Comment by shintadewiaw** [comment]
@erlangganugraha @nisrinaraisy jenis perjalanan di aplikasi ga mandatory loh guys, mandatory kalau emang si usernya mau ngisi riwayat perjalanan

**Comment by nisrinaraisy** [comment]
Perlu ditambahin keterangan kah @shintadewiaw ?

***"Riwayat Perjalanan (Mandatory apabila pasien ada riwayat perjalanan)"***

**Comment by shintadewiaw** [comment]
boleh boleh nis @nisrinaraisy 

cc: @khihadysucahyo
