### ISSUE TITLE
[Revamp Kontak Erat] Buat laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#691]
## UI
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A0

### Page Data Pasien

- [ ] Dibuat responsive

### Page Kasus Keterkaitan

- [ ] Dibuat responsive
- [ ] Asal daerah by deault Jawa Barat
- [ ] Terdapat pencarian Nama / NIK / Telp
- [ ] NIK, Nama, Kriteria dibuat mandatory
- [ ] Bisa mendata > 1 kontak keterkaitan
- [ ] Bisa hapus data

### UX

- [ ] 1. Jika asal daerah Jawa Barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat

- [ ] 2. Jika asal daerah jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria hanya bisa memilih kontak erat

- [ ] 3. Jika asal daerah diluar jawa barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat

- [ ] 4. Jika asal daerah luar jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria bebas pilih

## Notes
https://docs.google.com/document/d/1ytjCfC0P6f08IAk50cevvLnJc6zDjGe5PhLjPmHLUps/edit?usp=sharing

**Comment by rafidrbbn** [comment]
> ## UI
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5136%3A27714&viewport=473%2C-1940%2C0.1321866661310196&scaling=min-zoom
> ## AC
> ### Page Data Pasien
> * [ ]  Dibuat responsive
> 
> ### Page Kasus Keterkaitan
> * [ ]  Dibuat responsive
> * [ ]  Asal daerah by deault Jawa Barat
> * [ ]  Terdapat pencarian Nama / NIK / Telp
> * [ ]  NIK, Nama, Kriteria dibuat mandatory
> * [ ]  Bisa mendata > 1 kontak keterkaitan
> * [ ]  Bisa hapus data
> 
> ### UX
> * [ ]  1. Jika asal daerah Jawa Barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
>   NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat
> * [ ]  2. Jika asal daerah jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria hanya bisa memilih kontak erat
> * [ ]  3. Jika asal daerah diluar jawa barat & hasil pencarian ditemukan, maka; Autofill & Disabled Edit utk identitas pasien, sbb;
>   NIK, Nama, Kriteria, No Telepon, Tanggal Lahir, Jenis Kelamin, Pekerjaan, Alamat
> * [ ]  4. Jika asal daerah luar jawa barat & hasil tidak ditemukan, maka; Tidak auto fill & input manual dengan kriteria bebas pilih
