### ISSUE TITLE
[Revamp Kontak Erat] Page awal buat laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#692]
## AC
- [ ] Dibuat responsive
- [ ] Terdapat button Tambah Kasus Baru, direct ke page buat laporan kasus baru
- [ ] Terdapat pencarian by nama pasien
- [ ] Terdapat list data kontak erat yang belum diwawancara
- [ ] Terdapat button buat laporan disetiap list data pasien
- [ ] List data order by tgl updated DESC
- [ ] List data by default 100 rows

## Browser

- [ ] Mozilla Firefox

**Comment by shintadewiaw** [comment]
Feedback:
Page dibuat reset ketika membuka form input kembali
