### ISSUE TITLE
Improvement Buat Laporan Kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#699]
### Group Form Identitas Pasien
Wireframe : https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu@VsSo8s35WxyR2ZyJx1dWbJ
- [x] Penghasilan pindah ke identitas pasien

### Group Form Informasi Klinis
Wireframe : https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu@7YNFXnKbZAXKrrryrb1NU
- [x] Suhu tubuh >=38C rename jadi Demam
- [x] Hapus item suhu tubuh <38C
- [ ] Tgl Muncul Gejala dipisah per item
- [x] Lokasi saat ini perlu dirubah, menjadi dirawat dirumah sakit (Ya/Tidak)
- [x] Pemeriksaan Fisik pindah ke group informasi klinis
- [x] Status Pasien terakhir + tanggal update status pasien terakhir diposisi terakhir
- [x] Aktivitas Fisik dipindah ke informasi klinis
- [x] Merokok dipindah ke informasi klinis
- [x] Alkohol dipindah ke informasi klinis

### Group Form Pemeriksaan Penunjang
Wireframe : https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu@7YNFXnKbZAXJCCdaXzxGx
- [x] Pilihan jenis pemeriksaan diganti jadi PCR, Rapid, Radiologi, CT-Scan, TCM-SARS COV-2
----
UX

- [x] Kondisional jenis pemeriksaan PCR, maka pilihan jenis spesimennya : Dahak, Swab Nasofaring, Swab Orofaring, Swab Naso-Orofaring
- [x] Kondisional jenis pemeriksaan Rapid, maka pilihan jenis spesimennya : Darah
- [x] Kondisional jenis pemeriksaan Radiologi tidak ada pilihan jenis spesimen (hide jenis spesimen)
- [x] Kondisional jenis pemeriksaan CT-Scan tidak ada pilihan jenis spesimen (hide jenis spesimen)
- [x] Kondisional jenis pemeriksaan TCM-SARS COV-2, maka pilihan jenis spesimennya : Dahak, Swab Nasofaring, Swab Orofaring, Swab Naso-Orofaring

### Group Form Kontak Paparan
Wireframe : https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu@VsSo8s35Wy2Yrmiqy8NjwV
- [x] Tambah pilihan profesi nakes, jika pertanyaan apakah pasien nakes dipilih **Ya** *yang diproduction sudah, tp distaging sekarang jadi hilang

### Add Group Form Pola Transmisi
wireframe : https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu@VsSo8s35Wy1yQXJFkMJpkD
- [x] Terdapatan inputan Jenis Transmisi : Kasus Impor, kasus yang berelasi dgn kasus impor, kasus lokal yg berkaitan secara Epidemiologi, Kasus lokal yg tidak diketahui sumber penularannya.

- [x] Terdapat inputan Jenis Klaster : Nakes, Perkantoran, Rumah Tangga, Pabrik, Tempat Ibadah, Pasar/Pusat Perbelanjaan/Toko, Tempat Wisata, Rumah Makan, Masukkan lainnya jika ada.

## Note
https://docs.google.com/document/d/1ytjCfC0P6f08IAk50cevvLnJc6zDjGe5PhLjPmHLUps/edit

## Browser

- [x] Mozilla

**Comment by erlangganugraha** [comment]
Pilihan profesi nakes udah ada diproduction;
![image](https://user-images.githubusercontent.com/11548871/94423746-4e568980-01b3-11eb-887b-8afd1c0dff28.png)
cc @khihadysucahyo @Arif9878

**Comment by erlangganugraha** [comment]
![WhatsApp Image 2020-09-29 at 12 52 05 PM](https://user-images.githubusercontent.com/11548871/94551763-11a49400-0280-11eb-8490-aa9e446eb3b3.jpeg)
@Arif9878 @khihadysucahyo

**Comment by erlangganugraha** [comment]
> 
> 
> > ![WhatsApp Image 2020-09-29 at 12 52 05 PM](https://user-images.githubusercontent.com/11548871/94551763-11a49400-0280-11eb-8490-aa9e446eb3b3.jpeg)
> > @Arif9878 @khihadysucahyo
> 
> ![image](https://user-images.githubusercontent.com/15098768/94572214-f5fab700-029a-11eb-8ca9-9df398e1e56f.png)

buttonnya diganti jadi "Update Kondisi Pasien" aja, lebih friendly

**Comment by rafidrbbn** [comment]
UI : https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5336%3A2573&viewport=-116%2C-3710%2C0.14466789364814758&scaling=scale-down-width

**Comment by rafidrbbn** [comment]
UI Pola Transmisi :
![image](https://user-images.githubusercontent.com/15098768/94654812-ce056500-0327-11eb-8eb3-d98910ba042b.png)
@khihadysucahyo @Arif9878

**Comment by erlangganugraha** [comment]
> 
> 
> UI Pola Transmisi :
> ![image](https://user-images.githubusercontent.com/15098768/94654812-ce056500-0327-11eb-8eb3-d98910ba042b.png)
> @khihadysucahyo @Arif9878

kang @rafidrbbn untuk penginputan jenis transmisi hanya bisa memilih satu aja, ga bisa >1 pilihan. Jadi opsi tipe inputnya antara dropdon atau radio button

cc @khihadysucahyo , @Arif9878

**Comment by rafidrbbn** [comment]
> > UI Pola Transmisi :
> > ![image](https://user-images.githubusercontent.com/15098768/94654812-ce056500-0327-11eb-8eb3-d98910ba042b.png)
> > @khihadysucahyo @Arif9878
> 
> kang @rafidrbbn untuk penginputan jenis transmisi hanya bisa memilih satu aja, ga bisa >1 pilihan. Jadi opsi tipe inputnya antara dropdon atau radio button
> 
> cc @khihadysucahyo , @Arif9878

Saya bikin gini ya kang?
![image](https://user-images.githubusercontent.com/15098768/94763495-90124a80-03d4-11eb-8224-eed8a37cfb25.png)
