### ISSUE TITLE
Improvement Buat Laporan Kasus - 2

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#718]
### Form Identitas Pasien

- [x] Asal Daerah dihapus aja, biarkan by default Jawa Barat
- [ ] Penginputan kriteria pasien & status pasien sebaiknya diinput diform informasi klinis
- [x]  Lattitude, Longtitude sebaiknya di hide. Digenerate saat klik simpan

### Form Info Klinis

- [x] Set mandatory Tanggal Update Status Pasien Terakhir
- [x] Menambahkan label "Tanggal Update Status Pasien Terakhir"
- [x] Tombol "Tambah Histori" diubah "Update Kondisi Pasien"
- [x] Tombol "Ubah Riwayat" diubah menjadi tombol "Hapus"

### Form Pemeriksaan Penunjang
- [x] Kondisional jenis pemeriksaan PCR, maka hasil pemeriksaanya ; Positif,  Negatif, Invalid, Dalam Proses
- [x] Kondisional jenis pemeriksaan Rapid, maka hasil pemeriksaanya ; Reaktif, Non Reaktif, Invalid
- [x] Kondisional jenis pemeriksaan Radiologi, maka hasil pemeriksaanya ; Free Text
- [x] Kondisional jenis pemeriksaan CT-Scan, maka hasil pemeriksaanya ; Free Text
- [x] Kondisional jenis pemeriksaan TCM-SARS COV-2, maka hasil pemeriksaanya ; Positif,  Negatif, Invalid, Dalam Proses

### Form Kontak Paparan
- [x] Input "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya ?" sebaiknya dihilangkan, karena sudah tercover **diform kontak terkait**

### Form Pola Transmisi
- [x] Saat menginputkan "Pola Transmisi" flagging tidak terupdate menjadi "Lengkap"

### List Kasus
![Screenshot_2020-10-02 pelaporan-covid19(3)](https://user-images.githubusercontent.com/11548871/94901571-07bda380-04c1-11eb-9875-9590a6f0514a.png)

- [x] untuk CTA dilist kasus, sebaiknya hanya Lihat Detail, Cetak Laporan PE, Hapus Kasus
- [x] Ketika klik lihat detail direct ke detail case (yg kotak2)

**Comment by erlangganugraha** [comment]
@khihadysucahyo @Arif9878 minta tolong untuk diprioritaskan AC ini dulu, seperti flagging, dll bisa dikerjakan setelah AC ini dulu aja. Karena lebih fungsional yang paling penting. Mohon kerja samanya bro

**Comment by shintadewiaw** [comment]
### Feedback 05/10/2020
1. Pemeriksaan Penunjang - Pilih Jenis Pemeriksaan Radiologi dan hasil Kurang Sehat pada List pemeriksaan penunjang Value Hasil tidak masuk
![image](https://user-images.githubusercontent.com/63390998/95071740-57f06c00-0734-11eb-8eaa-d4203b879e3b.png)
![image](https://user-images.githubusercontent.com/63390998/95071781-663e8800-0734-11eb-91fd-08cdfae195bc.png)

2. Pemeriksaan Penunjang - Pilih Jenis Pemeriksaan CT SCAN dan hasil Batuk pada List pemeriksaan penunjang Value Hasil tidak masuk
![image](https://user-images.githubusercontent.com/63390998/95071941-a3a31580-0734-11eb-9901-8af0422ed67c.png)
![image](https://user-images.githubusercontent.com/63390998/95071960-adc51400-0734-11eb-8d9b-77000f224fa9.png)

3. Form Kontak Paparan - Input "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya ?" sebaiknya dihilangkan, karena sudah tercover diform kontak terkait **BELUM  DI HIDE**

4. Form Kontak Paparan -  Saat memilih "Apakah pasien merupakan petugas kesehatan?" Ya kemudian pilih Tidak, Kolom Free Text pada "Apakah melakukan prosedur yang menimbulkan erosol?" tidak ke hide **Belum Ada Perubahan**

5. Form Kontak Paparan - Saat mengisikan seluruh kontak paparan dan klik simpan, flagging tidak berubah menjadi Lengkap

6. Form Pola Transmisi - Saat menginputkan Pola Transmisi flagging tidak berubah menjadi Lengkap

7. Kasus Keterkaitan - Ketika nama kontak sudah dipakai sebagai kontak, sebaiknya di hilangkan dari daftar pencarian saat input  (ini kalau possible aja)

**Comment by shintadewiaw** [comment]
@Arif9878 @khihadysucahyo
