### ISSUE TITLE
[Laporan Kasus] Penyesuaian proses verifikasi kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#736]
## User Story
Role dari dinkes sendiri salah satunya yaitu memvalidasi data yang diinputkan oleh faskes (surveilans), maka dari itu pada sistem pelaporan perlu mengakomodir fungsi untuk memverifikator data. Proses verifikator ini terbagi menjadi 2, yaitu diverifikasi (disetujui) dan data ditolak. Sebetulnya fungsi ini sudah ada dalam sistem, tetapi kita harus menyesuaikan dengan versi sistem pelaporan terbaru. Maka dari itu perlu kita sesuaikan fungsi proses verifikasi data tsb.

## Flow
Flow hampir sama dengan proses sebelum diupdate ke versi baru. Hanya saja perlu kita sesuaikan segi tampilannya

## AC

- [ ] 1. Pada menu verifikasi kasus, terdapat CTA (pilih aksi) yang dimana terdapat dropdown pilihan **proses verifikasi**
- [ ] 2. Ketika tombol **proses verifikasi** ini ditekan, maka sistem akan muncul summary data yang fungsi untuk mengecek data apakah sudah valid (lengkap) atau belum
- [ ] 3. Jika sudah sesuai atau sudah valid, maka untuk memverifikasi data tsb terdapat verifikasi data (data disetujui) dengan membuat fungsi tombol "Verifikasi" 
- [ ] 4. Jika sudah disubmit proses verifikasi, maka data yang diinputkan akan pindah ke page list kasus

> NB : Untuk lebih kebayang flow & AC bisa mengikuti prototype yang telah dibuat

## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3563%3A8719&viewport=364%2C-2160%2C0.15992286801338196&scaling=scale-down-width

Desain : https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3563%3A8719

**Comment by rafidrbbn** [comment]
UI Verifikasi Laporan Kasus

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3563%3A8719&viewport=526%2C-1112%2C0.0777023583650589&scaling=scale-down-width

**Comment by shintadewiaw** [comment]
### How to Reproduce Bug
Login sebagai faskesbogor & dinkeskotabogor
**Actual Result:**
1. Menginputkan data pada input kasus (faskes)
2. Melakukan verifikasi kasus (dinkes)
3. Detail data kurang lengkap seperti yang sudah di inputkan dari faskes

**Expected Result:**
1. Menginputkan data pada input kasus (faskes)
2. Melakukan verifikasi kasus (dinkes)
3. Detail data lengkap seperti yang sudah di inputkan dari faskes

**Feedback**

- [ ] Value pada pemeriksaan penunjang tidak masuk
- [ ]  Pemeriksaan Penunjang - Hide Pemeriksaan fisik karena tidak ada form untuk input itu
![image](https://user-images.githubusercontent.com/63390998/96971582-85645480-153f-11eb-998a-acfc3719a516.png)
![image](https://user-images.githubusercontent.com/63390998/96971621-91501680-153f-11eb-998f-fb62eb180c61.png)


- [ ]  Value pada Faktor Riwayat Perjalanan tidak masuk (Riwayat Perjalanan, Area Transmisi, Riwayat Bepergian)
![image](https://user-images.githubusercontent.com/63390998/96971719-b6448980-153f-11eb-9e42-c12458b8f6a3.png)
![image](https://user-images.githubusercontent.com/63390998/96971673-a88f0400-153f-11eb-916c-c576dfd4a288.png)

- [ ] Value pada Kontak/Paparan tidak masuk
- [ ] Kontak Paparan - Hide "Dalam 14 hari sebelum sakit, apakah memiliki kontak erat dengan kasus suspek/probabel/konfirmasi COVID-19 lainnya ?"
- [ ] Kontak Paparan - Hide Kontak Primer
![image](https://user-images.githubusercontent.com/63390998/96971828-df651a00-153f-11eb-9a00-197cdd5c5d20.png)
![image](https://user-images.githubusercontent.com/63390998/96971794-d2482b00-153f-11eb-80e8-a70921937d71.png)

- [ ]  Riwayat Sosial Ekonomi - Value Aktivitas Fisik tidak masuk
- [ ]  Riwayat Sosial Ekonomi - Value pada Merokok tidak masuk
- [ ]  Riwayat Sosial Ekonomi - Value pada Konsumsi Alkohol tidak masuk
![image](https://user-images.githubusercontent.com/63390998/96971867-ef7cf980-153f-11eb-8254-53a507948bf9.png)
![image](https://user-images.githubusercontent.com/63390998/96971914-00c60600-1540-11eb-8967-356137a09068.png)


- [ ]  Data Kontak Erat - Value Hubungan Dengan Kasus Primer tidak masuk

SEMANGAAAAAT!
@Arif9878

**Comment by shintadewiaw** [comment]
btw kalau verifikasi kasus, dinkes boleh edit datanya? kalau dulu kan flownya cuma lihat detail terus bisa tolak/terima, nanti kalau di tolak si faskes yang perbaiki
@erlangganugraha @rafidrbbn

**Comment by zidneeey** [comment]
https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu
[
![Uploading Aplikasi Pelaporan Rev 5@2x (6).png…]()
](url)

**Comment by rafidrbbn** [comment]
Link UI Input Faskes

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5826%3A21313&viewport=364%2C-2160%2C0.15992286801338196&scaling=scale-down-width

**Comment by shintadewiaw** [comment]
mas @Arif9878 ada yang ketinggalan:

1. Ini kayanya ke hide
- [ ]  Riwayat Sosial Ekonomi - Value Aktivitas Fisik tidak masuk
- [ ]  Riwayat Sosial Ekonomi - Value pada Merokok tidak masuk
- [ ]  Riwayat Sosial Ekonomi - Value pada Konsumsi Alkohol tidak masuk
![image](https://user-images.githubusercontent.com/63390998/96971867-ef7cf980-153f-11eb-8254-53a507948bf9.png)
![image](https://user-images.githubusercontent.com/63390998/96971914-00c60600-1540-11eb-8967-356137a09068.png) 

2. Ini yang kosong jangan invalid ya mas, kosongin aja atau (-), disini yang invalid, cek cek yang lain juga ya hehe
- [ ] Tanggal Mulai Perjalanan
- [ ] Tanggal Pulang Perjalanan
- [ ] Hasil Pemeriksaan
![image](https://user-images.githubusercontent.com/63390998/98205886-83e95200-1f6b-11eb-97d7-e1086cffbcfa.png)

3. Value Jenis Spesimen dibuat bahasa indonesia ya biar seragam

4. Hubungan Dengan Kasus Primer, value ini gamasuk

**Comment by Arif9878** [comment]
@shintadewiaw minta tolong check lagi sin

**Comment by shintadewiaw** [comment]
mas @Arif9878 data verifikasi di dinkes kok jadi ilang ya?
![image](https://user-images.githubusercontent.com/63390998/98214677-615e3580-1f79-11eb-9363-26b958e42dd4.png)

**Comment by Arif9878** [comment]
dinkes mana ini sin

**Comment by shintadewiaw** [comment]
wkwkwk gajadi mas salah login @Arif9878

**Comment by shintadewiaw** [comment]
- [ ]  Aktivitas Fisik value belum masuk

- [ ]  Kontak Terkait -  Hubungan Dengan Kasus Primer value belum masuk

- [ ]  Kontak Terkait - Tanggal Kontak Pertama

- [ ]  Kontak Terkait - Tanggal Kontak Terakhir

- [ ] Tanggal Lahir dibuat bahasa indonesia

- [ ] Batas Verifikasi Otomatis dibuat bahasa indonesia
![image](https://user-images.githubusercontent.com/63390998/98216359-8a7fc580-1f7b-11eb-9edb-43b8c40679b8.png)

@Arif9878

**Comment by Arif9878** [comment]
![Screen Shot 2020-11-05 at 17 20 41](https://user-images.githubusercontent.com/20775950/98228734-91163900-1f8b-11eb-9f34-c51486ff5514.png)
![Screen Shot 2020-11-05 at 17 20 56](https://user-images.githubusercontent.com/20775950/98228742-94112980-1f8b-11eb-9a0e-00ae42407674.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878  aktivitas fisik gamasuk kalo pilihnya sedenter
![image](https://user-images.githubusercontent.com/63390998/98326587-29f89300-2024-11eb-8e6c-20e55675db68.png)

![image](https://user-images.githubusercontent.com/63390998/98326617-35e45500-2024-11eb-9dda-7e8f85d8b954.png)

**Comment by Arif9878** [comment]
![Uploading Screen Shot 2020-11-06 at 14.36.47.png…]()
 done
