### ISSUE TITLE
[Dashboard] Implement dashboard V2

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#737]
## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=418%2C-386%2C0.16316170990467072&scaling=scale-down-width

**Comment by shintadewiaw** [comment]
mas @Arif9878 ini dirapihin ya
![image](https://user-images.githubusercontent.com/63390998/96696092-946acb80-13b4-11eb-8811-bd2423a5ff15.png)

**Comment by shintadewiaw** [comment]
tambahan @Arif9878 

Redaksinya seharusnya ini ya "Rekap Kontak Erat, Suspek, Probable, & Terkonfirmasi"
![image](https://user-images.githubusercontent.com/63390998/96698095-eb71a000-13b6-11eb-80ac-8e89f886d612.png)
