### ISSUE TITLE
[Laporan Kasus] Export history kasus (informasi klinis)

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#739]

**Comment by rafidrbbn** [comment]
> _No description provided._
UI Pilihan Export
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=526%2C-1112%2C0.0777023583650589&scaling=scale-down-width

**Comment by shintadewiaw** [comment]
mas @Arif9878 bagian FE cuma nyiapin bagian tombolnya aja kan? isinya dari BE ya?
