### ISSUE TITLE
Hide ringkasan jumlah list kasus diproduction

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#742]

**Comment by erlangganugraha** [comment]
![Screenshot_2020-10-15 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/96075770-f23f7500-0ed5-11eb-9969-ef62c3bea93b.png)

---
Sebaiknya dihilangkan saja untuk yang ditandai kotak merah @Arif9878

**Comment by shintadewiaw** [comment]
@Arif9878
