### ISSUE TITLE
Desain Fitur Import

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#759]
Untuk deskripsi detail dilink : https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/issues/766

**Comment by rafidrbbn** [comment]
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=453%2C-3385%2C0.11025934666395187&scaling=scale-down-width
