### ISSUE TITLE
[Laporan Kasus] Input kasus dari faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#761]
## User story
Faskes khususnya surveilans memiliki tugas untuk investigasi pasien terkait covid-19, jadi sebagai faskes perlu input data ke pelaporan, oleh karena itu maka sistem pelaporan harus mengakomoir form input kasus dari faskes. Berhubung fiturnya sudah ada, maka hanya perlu sesuaikan dengan versi terbaru sistem pelaporan.

## Flow
Flow akan disamakan dengan input dari dinkes, hanya saja perlu CTA yang berfungsi bahwa proses penginputan sudah lengkap & selesai dilakukan. Yang selanjutnya proses input tersebut akan diverifikasi oleh dinkes wilayahnya masing2

## AC

- [x] 1. Form input awal dengan mengisi Biodata pewawancara, ID pasien, dan informasi klinis
- [x] 2. Setelah input awal selesai, maka perlu ada redaksi (berupa alert) ke user untuk mengisi input data selanjutnya (tahap 2)
- [x] 3. Tersedia form input tahap 2 (Group form pemeriksaan penunjang, dll)
- [x] 4. Terdapat fungsi Selesai jika sudah input data sudah selesai & lengkap
- [x] 5. Fungsi Selesai berfungsi jika sudah ID Pasien & Informasi Klinis sudah lengkap
- [x] 5. Ketika proses input data selesai dan tombol Simpan & Selesai ditekan maka sistem akan direct ke page list verifikasi kasus

> NB : Untuk lebih kebayang flow & AC bisa mengikuti prototype yang telah dibuat

## Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5826%3A21313&viewport=877%2C-4240%2C0.3099302053451538&scaling=scale-down-width

Desain : 
https://www.figma.com/file/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5826%3A21313

**Comment by zidneeey** [comment]
https://whimsical.com/AewqvCuWqQpg2wVNc5pjiu

![Aplikasi Pelaporan Rev 5@2x (6)](https://user-images.githubusercontent.com/62755122/97824376-4fb52d80-1cee-11eb-8b86-b77cbd5e5968.png)

**Comment by rafidrbbn** [comment]
Link UI Input Faskes

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5826%3A21313&viewport=364%2C-2160%2C0.15992286801338196&scaling=scale-down-width

**Comment by zidneeey** [comment]
<img width="1440" alt="Screen Shot 2020-11-02 at 15 52 49" src="https://user-images.githubusercontent.com/62755122/97848409-9e30ef00-1d23-11eb-8fac-cf5b6f781af9.png">
<img width="1440" alt="Screen Shot 2020-11-02 at 15 53 03" src="https://user-images.githubusercontent.com/62755122/97848423-a426d000-1d23-11eb-9ca8-90bfa3c19dc7.png">
<img width="1440" alt="Screen Shot 2020-11-02 at 15 53 16" src="https://user-images.githubusercontent.com/62755122/97848428-a4bf6680-1d23-11eb-90ae-cba7e0e79a10.png">
<img width="1440" alt="Screen Shot 2020-11-02 at 15 53 27" src="https://user-images.githubusercontent.com/62755122/97848430-a5f09380-1d23-11eb-8727-81476e8b06b8.png">

**Comment by shintadewiaw** [comment]
Tidak ada tombol untuk simpan draft/kirim ke dinkes
![image](https://user-images.githubusercontent.com/63390998/98082996-41ad0b80-1eac-11eb-96aa-e9a5238c95ec.png)

@Arif9878
