### ISSUE TITLE
Improvement fitur import data kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#766]
## Bakground
Jumlah keterisian data semakin hari terus menurun, untuk meningkatkan keterisian data selain penambahan jumlah resource penginput data. Diperlukan juga fitur input data dalam jumlah banyak dalam 1x proses. Maka dari itu perlu dibuatkan fitur import.

Fitur import sudah ada disistem pelaporan, tetapi perlu kita sesuaikan dengan form input revisi 5

## Syarat Ketentuan Menggunakan Fitur Import

1. NIK wajib mandatory
2. Pola transmisi wajib diisi jika pasien berkriteria konfirmasi
3. Max jumlah data <200
4. Import diperuntukan untuk data baru, data yang sudah terinput sebaiknya diupdate melalui aplikasi sesuai dgn kondisi sekarang
5. Ideal import dilakukan jam 07:00 - 08:00 (pagi) & jam 15:00 - 19:00 (senja menuju malam)
6. Fitur import diperuntukkan role dinkes kota/kab
7. Untuk proses pelacakan kontak sebaiknya tidak menggunakan fitur import

## Template import
link :

## Desain
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=453%2C-3385%2C0.11025934666395187&scaling=scale-down-width

## AC

- [x] Terdapat pesan error, jika proses import dijalankan mengalami error
- [x] Maximal rows <200, jika melebihi terdapat alert (pesan)
- [x] Pada form import, terdapat content Syarat & Ketentuan
- [x] Pada form import, terdapat tata cara penggunaan import
- [x] Pada form import, terdapat template import yang bisa didownload
- [x] Jika NIK ada yang kosong, maka data tidak masuk + terdapat pesan, contoh "NIK dirows 99 kosong, harap diisi terlebih dahulu"
- [x] Ketika data mandatory kosong, maka data tidak masuk + terdapat pesan error wajib diisi
- [x] Pada kolom gejala, jika diisi = " ", "-", "Tidak". Maka untuk field terdapat gejala terisi "Tidak"
- [x] Pada kolom kondisi penyerta, jika diisi = " ", "-", "Tidak". Maka untuk field terdapat gejala terisi "Tidak"
- [x] Pada kolom etiologi lainnya terisi, maka jawaban yang menimbulkan etiologi "Ya"
- [x] Data Pola transmisi wajib diisi jika pasien berkriteria konfirmasi
- [x] Jika proses import berhasil, maka data ditampilkan pada list kasus

> NB ; Untuk testing fitur import sebaiknya dilakukan full skenario

**Comment by shintadewiaw** [comment]
FE

- [ ] Pesan error sebaiknya dibuat (-) kebawah satu satu

- [ ] Area Transmisi - Value di FE tidak perlu menampilkan kode kotanya

*sementara ini dulu nanti kutambah kalau ada lagi

**Comment by shintadewiaw** [comment]
mau upload screenshot gagal mulu, nanti kalau udah bisa ku lampirin

**Comment by Arif9878** [comment]
> FE
> 
> * [ ]  Pesan error sebaiknya dibuat (-) kebawah satu satu
> * [ ]  Area Transmisi - Value di FE tidak perlu menampilkan kode kotanya
> 
> *sementara ini dulu nanti kutambah kalau ada lagi

@shintadewiaw  yang area transmisi menampilkan kode kotanya coba tanya ke hadi cc @khihadysucahyo
