### ISSUE TITLE
Tambaha button reset disetiap filter pada dashboard kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#767]
## User story
Sebagai user saya ingin mereset hasil filter yang dilakukan

## AC

- [x] Terdapat button reset disetiap filter rekapan/visualisasi

**Comment by rafidrbbn** [comment]
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=728%2C-783%2C0.30655398964881897&scaling=scale-down-width

**Comment by erlangganugraha** [comment]
> 
> 
> https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=728%2C-783%2C0.30655398964881897&scaling=scale-down-width

saat saya klik link prototypenya mengarah ke page buat laporan kasus, jadi saya belum bisa review kang @rafidrbbn

**Comment by rafidrbbn** [comment]
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom

Coba ini kang, kayaknya ke replace kemarin

**Comment by erlangganugraha** [comment]
![image](https://user-images.githubusercontent.com/11548871/99757786-b0cc6600-2b22-11eb-9421-84e82f3512f1.png)
belum ada button resetnya kang @rafidrbbn

**Comment by rafidrbbn** [comment]
![image](https://user-images.githubusercontent.com/15098768/99765284-52f34a80-2b31-11eb-848d-46ca6f11c83e.png)
Maapin kang, udah di update resetnya
