### ISSUE TITLE
Penambahan improvement desain form input laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#770]
## AC

- [x] Menambahkan redaksi di atas halaman yang menginfokan bahwa masih ada isian yg perlu dilengkapi. Pilihan redaksi

Bagian 1 dari 2
(deskripsi bagian 1)
Langkah 1 dari 2
(deskripsi langkah 1)

- [x] Mengubah urutan:

Nama
NIK
No. Telp
Nama Ortu

- [x] Redaksi Pekerjaan diubah menjadi “Bidang Pekerjaan”

- [x] Kondisional pekerjaan ;

Jika pekerjaan Pegawai Negeri, Pegawai Swasta, TNI/Polisi, Petani, Peternak, Nelayan, Tukang Bangunan, Wiraswasta, Pengobatan, Hukum, Tokoh Agama, Pemerintahan, Pendidikan, Kesehatan, Keuangan, Mesin, Lainnya
Maka muncul Alamat Kantor

- [x] Checkbox tidak ada NIK dan No. Telp di pindah ke samping kolom isian

- [x] Tambahkan icon/cta edit pada tiap kotak2

- [x] Kotak tulisan RT RW di pindah ke samping

**Comment by rafidrbbn** [comment]
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5136%3A27714&viewport=578%2C-871%2C0.08419085294008255&scaling=scale-down-width

**Comment by erlangganugraha** [comment]
> 
> 
> https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5136%3A27714&viewport=578%2C-871%2C0.08419085294008255&scaling=scale-down-width

saat saya klik link protypenya tidak mengarah kepage buat laporan kasus step 1 kang @rafidrbbn

**Comment by erlangganugraha** [comment]
Hasil review :
Bagian yang belum terchecklist AC tandanya belum terpenuhi, harap didipenuhi ACnya
Untuk step 2 tombol verifikasi masih dibawah, sebaiknya disesuaikan dengan desain existing yang tombolnya ada diatas

Lalu ada tambahan improvement lagi kang, cardnya saya buat terpisah yah. Sbb ;
https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/issues/790

**Comment by rafidrbbn** [comment]
Update Link
