### ISSUE TITLE
Revisi Proses Input dari faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#781]
## List Revisi

- [x] 1. Copy writer pada intruksi kalimatnya "Lengkapi data riwayat dan informasi pasien di bawah ini Lengkapi data riwayat dan informasi pasien di bawah ini". Sebaiknya diperbaiki kalimatnya agar tidak mengulang2

![Screenshot_2020-11-10 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/98623638-bc5ba800-233e-11eb-9f0d-a794a85638c9.png)

- [ ] 2. Sebaiknya Title group form pada pop up lihat detail disesuaikan penamaanya  

![Screenshot_2020-11-10 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/98623825-0d6b9c00-233f-11eb-8f08-5f13e9263708.png)

- [ ] 3. Sebaiknya saat proses verifikasi kasus sudah berhasil, direct ke page list kasus

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/98764341-28f1a800-240e-11eb-9b49-8d6ddf1c6d7c.png)


1. Kolom ke 2 - Petugas Medis/Paramedis diubah menjadi Identitas Pasien
2. Kolom ke 3 Petugas Medis/Paramedis diubah menjadi Informasi Klinis
3. Setelah berhasil verifikasi kasus belum redirect ke list kasus

@Arif9878
