### ISSUE TITLE
Desain filter & export png dinetwork graph

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#789]
- [x] Terdapat filter wilayah berdasarkan kota, kec, sampe kelurahan
- [x] Terdapat button reset untuk mereset filter
- [x] Terdapat export to png untuk mengenerate kedalam gambar

**Comment by erlangganugraha** [comment]
belum ada link prototypenya kang @rafidrbbn

**Comment by rafidrbbn** [comment]
Maap kang, kayaknya kemarin ini kelewat

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6312%3A22458&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom

ini UI nya
