### ISSUE TITLE
Desain Rename tab riwayat perjalanan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#790]
![Screenshot_2020-11-18 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/99540472-1d8c1700-29e2-11eb-8792-a735be6603cc.png)
Untuk tab sebaiknya direname karena tidak mendefinisikan form input didalamnya, jadi direname sbb :

- [x] Tab riwayat perjalan direname menjadi "Dari Luar Negeri/Luar Kota"
- [x] Tab area transmisi direname menjadi "Ke Transmisi Lokal"
- [x] Tab Riwayat perjalanan direname menjadi "Ke Tempat Publik"

**Comment by rafidrbbn** [comment]
Update Perjalanan
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom
