### ISSUE TITLE
Penambahan improvement desain form input laporan kasus - 2

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#791]
Yang perlu direvisi ;
![Screenshot_2020-11-18 pelaporan-covid19(1)](https://user-images.githubusercontent.com/11548871/99542155-47ded400-29e4-11eb-9768-f0209ba6bdc9.png)

- [x] 1. Tanggal Update Status Terakhir direname menjadi "Tanggal Update Status Pasien Terakhir"

---
![Screenshot_2020-11-18 pelaporan-covid19(2)](https://user-images.githubusercontent.com/11548871/99542574-d05d7480-29e4-11eb-9334-e0d338a74310.png)

- [x] 2. Title informasi penunjang direname menjadi "Pemeriksaan Penunjang"
--- 
![Screenshot_2020-11-18 pelaporan-covid19(3)](https://user-images.githubusercontent.com/11548871/99542828-0c90d500-29e5-11eb-93cf-6362907d5556.png)

- [x] 3. Tempat pemeriksaan dibuat dropdown, (isinya list RS & Lab)

**Comment by rafidrbbn** [comment]
Update

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom
