### ISSUE TITLE
Improvement form buat laporan kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#796]
## UI & Prototype

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom

---
### General

- [x] Menambahkan redaksi di atas halaman yang menginfokan bahwa masih ada isian yg perlu dilengkapi. Pilihan redaksi : Bagian 1 dari 2 (deskripsi bagian 1), Bagian 2 dari 2 (deskripsi bagian 2)

- [x] Title informasi penunjang direname menjadi "Pemeriksaan Penunjang"
- [x] Tambahkan icon/cta edit disetiap card group form

### Identitas Pasien

- [x] Sebaiknya urutan pertama kali input adalah Nama pasien lalu diikuti NIK, No. Telp, Nama Ortu, dst
- [x] Redaksi Pekerjaan diubah menjadi “Bidang Pekerjaan”
- [x] Checkbox tidak ada NIK dan No. Telp di pindah ke samping kanan kolom isian

### Informasi klinis

- [x] Tanggal Update Status Terakhir direname menjadi "Tanggal Update Status Pasien Terakhir"

### Pemeriksaan Penunjang (saat ini Informasi Penunjang)

- [x] Tempat pemeriksaan dibuat dropdown, (isinya list RS & Lab)

**Comment by erlangganugraha** [comment]
kang @rafidrbbn boleh dilampirkan link prototypenya dideskripsi

**Comment by rafidrbbn** [comment]
Link UI

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom
