### ISSUE TITLE
Peta sebaran kasus dengan kriteria baru (rev 5)

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#799]
## User story
Sebagai semua level user, saya ingin melihat kasus sebaran dalam bentuk peta wilayah dengan kriteria baru sesuai dengan rev 5 agar saya bisa melihat titik wilayah kasus disekitar wilayah yang saya tangani

## Desain
![WhatsApp Image 2020-11-27 at 7 38 26 PM](https://user-images.githubusercontent.com/11548871/100453426-75ff9a80-30ed-11eb-97ed-69921fffc7c2.jpeg)

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3873%3A8&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom

## Acceptance Criteria

- [x] Terdapat titik penyebaran dipeta dalam kriteria baru
- [x] Peta sebaran kasus bisa diunduh sebagai gambar

**Comment by erlangganugraha** [comment]
drop link desain disini yah kang @rafidrbbn

**Comment by rafidrbbn** [comment]
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3873%3A8&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom
