### ISSUE TITLE
Perubahan label riwayat perjalanan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#803]
## User Story
Sebagai semua user, saya ingin mengetahui setiap pasien summary riwayat perjalanannya

## Desain/Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5648%3A20757&viewport=734%2C197%2C0.057318221777677536&scaling=scale-down-width

## Acceptance Criteria

- [x] Terdapat jumlah riwayat perjalanan dari luar negeri
- [x] Terdapat jumlah riwayat perjalanan dari luar kota
- [x] Terdapat jumlah riwayat ke transmisi lokal
- [x] Terdapat jumlah riwayat ke tempat publik

**Comment by shintadewiaw** [comment]
@Arif9878 Ketika menambahkan data riwayat perjalanan total riwayat tidak terupdate (issue: tidak auto refresh ketika menambahkan data)

**Comment by shintadewiaw** [comment]
@erlangganugraha er ini totalnya mau sama luar negeri atau luar kota aja? soalnya di design luar kota doang sedangkan di AC luar kota dan luar negeri
![image](https://user-images.githubusercontent.com/63390998/100207421-22991b00-2f3a-11eb-81b6-6bb3e2bda173.png)

**Comment by erlangganugraha** [comment]
> 
> 
> @erlangganugraha er ini totalnya mau sama luar negeri atau luar kota aja? soalnya di design luar kota doang sedangkan di AC luar kota dan luar negeri
> ![image](https://user-images.githubusercontent.com/63390998/100207421-22991b00-2f3a-11eb-81b6-6bb3e2bda173.png)

dipisah shin sesuai AC, desainnya hanya contoh @shintadewiaw
