### ISSUE TITLE
Fitur peta sebaran kasus untuk level faskes

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#805]
## User story
Sebagai puskemas dan rumah sakit, saya ingin melihat kasus sebaran dalam bentuk peta wilayah dengan kriteria baru sesuai dengan rev 5 agar saya bisa melihat titik wilayah kasus disekitar wilayah yang saya tangani

## Desain dan Prototype
![Screenshot_2020-12-01 Figma(1)](https://user-images.githubusercontent.com/11548871/100696348-ed6f4b80-33c5-11eb-8931-feab83703d08.png)
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6470%3A24719&viewport=-1710%2C-1902%2C0.33246105909347534&scaling=scale-down-width

## Acceptance Criteria

- [x] Terdapat jumlah sebaran kasus berdasarkan alamat tempat tinggal pasiennya
- [x] Bisa difilter kecamatan dan kelurahan
- [x] Terdapat fungsi reset
- [x] Peta sebaran kasus bisa diunduh sebagai gambar

**Comment by rafidrbbn** [comment]
UI Peta sebaran kasus Faskes:

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6470%3A24719&viewport=-1710%2C-1902%2C0.33246105909347534&scaling=min-zoom
