### ISSUE TITLE
Improvement rekap demografis pada dashboard kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#807]
## User story
Sebagai dinkes kota/kab, saya ingin melihat rekap demografis berdasarkan sebaran umur

## Kebutuhan Rekap Demografis
![Screenshot_2020-11-22 (61) WhatsApp](https://user-images.githubusercontent.com/11548871/99906959-a1107580-2d0c-11eb-9378-b6d2f7cfec24.png)

## Acceptance Criteria
Tambahan sebaran umur sbb ; 

- [x] 40-49					
- [x] 50-59					
- [x] 60-69					
- [x] 70-79					
- [x] ≥ 80

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/100702613-945ae400-33d4-11eb-9d3c-a694f4cc5ad4.png)

![image](https://user-images.githubusercontent.com/63390998/100702804-ed2a7c80-33d4-11eb-955b-ac81261f3a15.png)


![image](https://user-images.githubusercontent.com/63390998/100702633-a0df3c80-33d4-11eb-904a-d1bead4996d2.png)

- [ ] Rekap Kontak Erat,Suspek,Probabel & Konfirmasi -  Penamanaan kolom Kota/Kab seharusnya adalah Kecamatan

- [ ] Rekap Kontak Erat,Suspek,Probabel & Konfirmasi - Seharusnya penamanaan kolom Kecamatan hanya memfilter Kecamatan saja tidak perlu menampilkan kelurahan


- [ ] Rekap Demografis - Penamanaan kolom Kota/Kab seharusnya adalah Kecamatan

- [ ] Rekap Demografis - Seharusnya penamanaan kolom Kecamatan hanya memfilter Kecamatan saja tidak perlu menampilkan kelurahan

**Comment by shintadewiaw** [comment]
mas @Arif9878  punten diubah lagi dari kecamatan jadi Kecamatan/Kelurahan karna teryata yang muncul itu kelurahan diluar wilayahnya
