### ISSUE TITLE
Perubahan kolom pada table informasi klinis

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#809]
## Acceptance Criteria

- [x] Perubahan kolom menjadi ;

1. No
2. Kriteria
3. Status Pasien Terakhir
4. Lokasi => Rumah Sakit (jika dirawat diRS) / Alamat (jika tidak dirawat) *sesuai field inputan "Apakah pasien dirawat dirumah sakit Ya/Tidak"
5. Tanggal Muncul Gejala
6. Gejala
7. Kondisi Penyerta
8. Tanggal Update Status Pasien Terakhir
9. Aksi

**Comment by Arif9878** [comment]
cc @erlangganugraha @rafidrbbn jangan campur bahasa asing sama bahasa indonesia di redaksi ```Tanggal Update Status Pasien Terakhir```
