### ISSUE TITLE
Input Hasil Test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#81]
## User Story
Sebagai dinkes kota/kab saya ingin mendata hasil test yang sudah dilakukan sebagai pendataan & penggunaan alat test (RDT/PCR)

## Wireframe
<img width="1440" alt="Input Hasil Test" src="https://user-images.githubusercontent.com/11548871/77891143-bd9e0000-729a-11ea-91fb-9f0c571bcba2.png">

## Acceptance Criteria :
* [x] Terdapat pilihan kategori (A,B,C)
* [x] Terdapat beberapa tipe sasaran
* [x] Terdapat data profil peserta
* [x] Terdapat hasil pengetesan
* [x] Ada 2 button simpan, sbb :
  * [x] Button "Simpan" itu fungsinya menyimpan untuk hasil test yang negatif
  * [x] Button "simpan & Tambahkan ke pelaporan" itu fungsinya menyimpan dan otomatis menambahkan ke laporan kasus untuk hasil test yang positif

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by aliyaqara** [comment]
List Bug :

1. Perubahan status ODP menjadi PDP tidak terecord pada riwayat kasus jika dari Input hasil test dengan status ODP dan ternyata hasil testnya positif (status menjadi PDP). [Enchancment]
2. Alamat tempat tinggal pada halaman Input hasil test dan tambah kasus di sort ascending [Enchancment]
3. Jika input selain ODP tidak otomatis tambah di data pelaporan kasus
4. Alamat peserta tidak sesuai dengan wilayahnya tidak muncul di list RDT
5. Saat input Tempat pengetesan dipilih Lainnya (selain RS) kemudian klik button Simpan & Tambahkan ke Pelaporan/button Simpan tidak ada aksi apapun
6. Saran list Lainnya di field tempat pengetesan di paling atas agar mudah mengisi jika tempat pengetesan bukan di RS
7. Jika data yang di inputkan sudah ada dalam list, saat menyimpan data muncul "_id 5e7dddb6d7fa1f001250aeea ID already exists in the database."
8. Jika data yang di inputkan sudah ada dalam list sebaiknya pada dropdown cari kasus datanya tidak muncul
9. Kode kasus (covid-1001200011) pada field cari kode kasus huruf kecil seharusnya huruf besar
10. Field NIK seharusnya dapat di isi angka saja

cc : @maruf12 @erlangganugraha

**Comment by maruf12** [comment]
@aliyaqara @erlangganugraha Input test sudah bisa ditest ulang ya guys

**Comment by aliyaqara** [comment]
1. [UNDONE] Perubahan status ODP menjadi PDP tidak terecord pada riwayat kasus jika dari Input hasil test dengan status ODP dan ternyata hasil testnya positif (status menjadi PDP). [Enchancment]
2. Tanggal pengetesan tidak di isi sedangkan field tersebut mandatory, sudah muncul pesan error tetapi otomatis berhasil tersimpan
3. Tanggal pengetesan dapat di input setelah hari ini dan seterusnya(contoh: hari ini tgl 1 april 2020, namun dapat input tanggal 5 juni 2020)

@maruf12

**Comment by maruf12** [comment]
> 1. [UNDONE] Perubahan status ODP menjadi PDP tidak terecord pada riwayat kasus jika dari Input hasil test dengan status ODP dan ternyata hasil testnya positif (status menjadi PDP). [Enchancment]
> 2. Tanggal pengetesan tidak di isi sedangkan field tersebut mandatory, sudah muncul pesan error tetapi otomatis berhasil tersimpan
> 3. Tanggal pengetesan dapat di input setelah hari ini dan seterusnya(contoh: hari ini tgl 1 april 2020, namun dapat input tanggal 5 juni 2020)
> 
> @maruf12

update input hasil test udah di stagging ya @aliyaqara

**Comment by aliyaqara** [comment]
kalo aku input hasil test trus di list id kasusnya di lis hasil test sama list kasus pelaporan brbeda itu knp yaa?kesalah di input apa di list?

@maruf12 @erlangganugraha

**Comment by aliyaqara** [comment]
Saat input ODP yg otomatis ditambahkan ke kasus pelaporan tetapi `id kasus` pada list hasil input dan list kasus pelaporan berbeda

@maruf12 @sandisunandar99

**Comment by sandisunandar99** [comment]
Itu harus di clearance dlu datanya kalo yg d staging.. soalnya ada bberapa data yng anomali jdi ga ke count,, dan jadi ga sinkron id case yg list kasus dan list input.. soalnua sya coba di lokal saya mah lancar jaya.. @Alya

**Comment by aliyaqara** [comment]
> Itu harus di clearance dlu datanya kalo yg d staging.. soalnya ada bberapa data yng anomali jdi ga ke count,, dan jadi ga sinkron id case yg list kasus dan list input.. soalnua sya coba di lokal saya mah lancar jaya.. @alya

oh gtuuu coba di clearance dulu aja biar rapih data di stagingnya jd testing nya lanacar ehhehe
