### ISSUE TITLE
Hapus tab semua pada verifikasi kasus

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#815]
### Sub Menu List Verifikasi Kasus - Role Faskes
- [x] Delete Tab Semua
- [x] Tab Menunggu Diverifikasi
- [x] Tab Data Kasus Ditolak
- [x] Tab Data Kasus Draft

### Sub Menu Verifikasi Kasus Baru - Role Dinkes Kota/Kab
- [x] Delete Tab Semua
- [x] Tab Menunggu Diverifikasi
- [x] Tab Data Kasus Ditolak

**Comment by erlangganugraha** [comment]
udah detailkan yah @Arif9878

**Comment by shintadewiaw** [comment]
mas @Arif9878 yang di dinkes kok tab menunggu diverifikasi sama ditolak hilang?
![image](https://user-images.githubusercontent.com/63390998/100564716-5edec980-32f4-11eb-80b7-e8ac3bc60c0c.png)

**Comment by Arif9878** [comment]
@shintadewiaw emang di hilangkan sin tab nya

**Comment by shintadewiaw** [comment]
yang dihilangkan tab "semua" doang mas, yang lain tidak

@Arif9878
