### ISSUE TITLE
Improvement template import rev 5

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#816]
- [x] Penambahan master data "Lab RSUD. dr. Slamet Garut" dilist lab

- [x] Perubahan redaksi kolom "Kewarganegaraan (wajib diisi)" karena membingungkan user, sebaiknya diganti menjadi "Kewarganegaraan (wajib diisi jika WNA)"

Revisi tambahan ;
- [x] Menambah tempat rumah sakit darurat baru sbb ;
1. Hotel Aruni Purwakarta
Alamat: Jl. Veteran No.13, Mulyamekar, Kec. Babakancikao, Kabupaten Purwakarta, Jawa Barat 41151
Telepon: 0812-9369-2222

2. Prime Plaza Hotel Purwakarta
Alamat: Jalan Kota Bukit Indah Raya No.Blok L, Cinangka, Kec. Bungursari, Kabupaten Purwakarta, Jawa Barat 41181
Telepon: (0264) 351888

3. Rumah Sakit Darurat Penanganan COVID19 Wisma Atlet Kemayoran
Alamat: Jl. Rd.H. Keneng Mudatsir No.13, RT.13/RW.6, Sunter Agung, Kec. Pademangan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14360
Provinsi: Jakarta

4. Wisma Mahkota Sehat
Alamat: Jl. Industri No.184, Maracang, Kec. Babakancikao, Kabupaten Purwakarta, Jawa Barat 41151
Telepon: 0817-7947-8001
Provinsi: Jawa Barat

relate dengan card ; https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/677

**Comment by nisrinaraisy** [comment]
[Template Data Pelaporan Kasus (UPDATE 23 November).xlsx](https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/files/5586834/Template.Data.Pelaporan.Kasus.UPDATE.23.November.xlsx)

**Comment by nisrinaraisy** [comment]
[Template Data Pelaporan Kasus (UPDATE 26 November).xlsx](https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/files/5601596/Template.Data.Pelaporan.Kasus.UPDATE.26.November.xlsx)
