### ISSUE TITLE
Revisi fungsi export data pasien

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#817]
## Acceptance Criteria
- [x] Menambahkan kolom kode kasus dibagian kolom paling pertama

**Comment by firmanJS** [comment]
@erlangganugraha langsung push ke production kah ? jika udah aman testing

**Comment by erlangganugraha** [comment]
yaps better kang @firmanJS

**Comment by firmanJS** [comment]
up @shintadewiaw testing di stagging ya mau segera up production
