### ISSUE TITLE
Fixing update kondisi pasien pada informasi klinis

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#818]
## User Story
Fungsi pada group form Informasi Klinis, tidak hanya mengupdate kondisi pasien pada statusnya, tetapi berfungsi sebagai mengupdate pemantauan harian pasien selama isolasi/karantina. Jadi sebagai dinkes, puskesmas, dan rumah sakit, saya ingin mengupdate kondisi pasien setiap hari

## Technical debt
Ketika saya mengupdate kondisi pasien dengan gejala yang sama, riwayat data informasi klinis tidak bertambah pada table informasi klinis

## Ekspektasi
Ketika saya mengupdate kondisi pasien dengan gejala yang sama, dengan tanggal update kondisi pasien yang berbeda. Maka data akan bertambah pada table informasi klinis

## Acceptance kriteria

- [x] Data riwayat informasi klinis bertambah ketika user mengupdate kondisi pasien dengan syarat tanggal update kondisi pasien berbeda atau sudah terinput pada table informasi klinis

- [x] Redaksi "Tanggal Diperbaharui Terakhir" diubah menjadi "Tanggal Update Status Pasien Terakhir"

- [x] Kolom "Tanggal Update Status Pasien Terakhir" berisi Update Status Terakhir **bukan** Tanggal dibuat

**Comment by erlangganugraha** [comment]
untuk AC 2 & 3 related dengan card ini :
https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/issues/809
cc @shintadewiaw @Arif9878

**Comment by shintadewiaw** [comment]
Feedback Tanggal 25 November 2020
- [ ] Ketika mengupdate informasi klinis dengan gejala yang berbeda dan tanggal yang sama, data tidak bertambah
- [ ] Ketika menghapus data informasi klinis, data tidak terhapus
