### ISSUE TITLE
List Hasil Test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#82]
## User Story
Sebagai dinkes kota/kab saya ingin melihat list hasil test yang sudah dilakukan agar saya bisa lihat data2 yang sudah masuk dan hasil testnya

## Wireframe
<img width="798" alt="Screen Shot 2020-03-30 at 16 20 36" src="https://user-images.githubusercontent.com/11548871/77899764-3b680880-72a7-11ea-8281-80477918db11.png">

## Acceptance Criteria :
* [x] Terdapat section total data yg diinputkan
* [x] Terdapat pencarian berdasarkan nama, id peserta
* [x] Terdapat list hasil test by default 30 row, sort berdasarkan id peserta & tgl pengetesan
* [x] Terdapat "Pilih Aksi" sbb :
  * [x] Aksi Edit Hasil Test
  * [x] Aksi Detail Hasil Test
  * [x] Aksi Hapus Hasil Test
* [x] Terdapat pagination

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by aliyaqara** [comment]
1. Jika input selain ODP, id kasus tidak tampil (tetapi jika di list pelaporan kasus id sudah ada dan tampil)
2. Saat input dengan sasaran ODP hasil Negative pada list tampil tidak berada paling atas (mengikuti id kasus)
3. Tidak ada tombol reset untuk serching?
4. Pencarian berdasarkan status (negativ/postif/invalid) belum berfungsi
5. Pilih Aksi masih: Lihat detail, Update profile peserta, Update hasil dan Hapus peserta

@Arif9878

**Comment by alifianif** [comment]
1. Default row tidak berfungsi. Tulisannya 30 tapi yang muncul di list hanya 10
2. Pagination belum berfungsi

@Arif9878

**Comment by Arif9878** [comment]
@alifianif kemarin sudah di perbaiki sih lif bisa di cek kembali
