### ISSUE TITLE
Desain peta sebaran kasus dengan kriteria baru (rev 5)

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#824]
## Desain Exsisting
![WhatsApp Image 2020-11-26 at 12 37 56 PM](https://user-images.githubusercontent.com/11548871/100312970-3437fc80-2fe6-11eb-93c4-96ecef328d40.jpeg)

## Acceptance Criteria

- [x] Sebaiknya pada prototype, untuk button **Tampilkan Keterangan** bisa diklik, lalu menampilkan konten.
**Kontennya bisa diambil pada gambar dibawah ini**

![WhatsApp Image 2020-11-26 at 12 43 34 PM](https://user-images.githubusercontent.com/11548871/100313062-63e70480-2fe6-11eb-8213-3f5087a709b0.jpeg)

----
- [x] Hidden pop up disclaimer

**Comment by rafidrbbn** [comment]
Update UI Peta Sebaran

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3873%3A1590&viewport=734%2C197%2C0.057318221777677536&scaling=min-zoom

**Comment by erlangganugraha** [comment]
kang saat saya klik **Tampilkan Keterangannya** belum contentnya @rafidrbbn

**Comment by rafidrbbn** [comment]
![image](https://user-images.githubusercontent.com/15098768/100411746-344b0180-30a5-11eb-8069-799cb1351854.png)

ini bukan kang? gk bisa di klik?
