### ISSUE TITLE
Hapus data hasil test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#83]
### Functional :
**Halaman List Hasil Test:**
* [x] Muncul pop-up validasi "Anda yakin ingin menghapus data ini?"

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by aliyaqara** [comment]
Jika menghapus dengan status positif dmna yang positif otomatis tambah ke pelaporan kasus. Di list hasil test terhapus tetapi di list kasus pelaporan tidak terhapus. ini gmna ya flownya? 

cc : @Arif9878 @erlangganugraha

**Comment by erlangganugraha** [comment]
harusnya ikut terhapus juga @aliyaqara
