### ISSUE TITLE
Notifikasi laporan kasus baru

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#840]
## User Story
Sebagai dinkes kota/kab, saya ingin diberikan notifikasi laporan kasus baru dari faskes agar saya bisa tahu bahwa ada laporan baru dari faskes

## Desain/Prototype
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6534%3A24604&viewport=591%2C-31722%2C0.5571706891059875&scaling=scale-down-width

## Acceptance Criteria

- [x] 1. Notifikasi diterima oleh dinkes kota/kab ketika puskesmas mengajukan laporan baru
- [x] 2. List notifikasi limit 10 berdasarkan yang terbaru baik yang sudah dibaca atau belum dibaca
- [x] 3. Terdapat waktu/data notifikasi pada setiap list notifikasi
- [x] 4. Terdapat fixed button untuk melihat semua notifikasi
- [ ] 5. Terdapat kategori label notifikasi setiap list notifikasi
- [x] 6. Terdapat jumlah notifikasi pada icon lonceng berdasarkan paramater yang belum diklik/dibaca
- [x] 7. Terdapat dot label untuk menandakan notifikasi belum dibaca

## UX
**Notifikasi kasus laporan kasus baru ;**
1. Jika diklik item notifikasi laporan baru, maka sbb : 

- [x] 1.1 Tandai notifikasi bahwa sudah dibaca/dibuka
- [x] 1.2 Muncul pop up detail summary proses verifikasi

- [x] 2. Jika data sudah diverifikasi, maka muncul alert "Data Sudah Diverifikasi"

- [x] 3. Jika data sudah ditolak, maka muncul alert "Data Sudah Ditolak"

----
**Notifikasi penolakan data kasus**
- [x] Ketika diklik item pesan notifikasi, maka direct ke detail data ditolak

----
**Notifikasi Kontak Erat Selesai Masa Karantina**

- [ ] Ketika diklik item pesan notifikasi, maka direct ke detail data pasien

**Comment by erlangganugraha** [comment]
cok gw update AC sesuai yang tadi di diskusikan yah @Arif9878

**Comment by shintadewiaw** [comment]
mas @Arif9878 tampilannya sesuaikan design yaa, datanya kalau lebih dari 10 ga fit kebawah mas kaya kepotong, lebarin juga ke kiri

Penamaan Kasusnya gausah dibuat capslock mas

![image](https://user-images.githubusercontent.com/63390998/103614340-f28e6000-4f5a-11eb-9622-a1713e7713a0.png)
![image](https://user-images.githubusercontent.com/63390998/103614425-236e9500-4f5b-11eb-9514-60c0f4166ba0.png)

**Comment by shintadewiaw** [comment]
tambahan mas @Arif9878 waktunya disesuaikan ya

**Comment by shintadewiaw** [comment]
nambahin catatan feedback tadi di japri:

belum ada perubahan
![image](https://user-images.githubusercontent.com/63390998/103763538-8db33280-504c-11eb-987b-bbc074259363.png)
