### ISSUE TITLE
Fitur Multiple Update Status Kontak Erat

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#843]
## User Story
Ketika ada penumuan kasus konfirmasi baru, maka dilakukan proses pelacakan kontak. Ketika proses pelacakan kontak, maka terdapat list kontak erat dengan pasien konfirmasi. Yang dimana kontak erat ini akan dipantau selama 14 Hari, biasanya orang-orang yang dipantau akan dimulai pemantauannya secara bersamaan, **otomatis ketika perubahan selesai masa karantinanya **(Discarded)** akan sama.** Oleh karena itu user ingin bisa mengupdate status menjadi discarded secara bersamaan, maka ;

Sebagai dinkes kota/kab dan faskes, saya ingin melakukan multiple update status kontak erat agar saya mudah untuk mengupdate statusnya dalam satu kali aksi.

## Desain/Prototype
![List Kasus - Checked](https://user-images.githubusercontent.com/42407562/101867118-0093cf80-3bad-11eb-91fc-1fef152ff03f.png)

https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=3085%3A10741&viewport=229%2C-10997%2C0.3699679970741272&scaling=min-zoom

## Acceptance Criteria
- [x] Terdapat tombol untuk mengaktifkan multiple update
- [x] Terdapat filter untuk memilah data
- [x] Terdapat checklist untuk memilih data yang akan diupdate statusnya
- [x] Ketika list data kontak erat sudah terpilih, maka muncul pop up form multiple update status pasien
- [x] User bisa memilih status pasien terakhir dan tanggal update status pasien terakhir
- [x] Ketika proses multiple update status pasien berhasil, maka direct ke  menu list kasus

**Comment by firmanJS** [comment]
api update multiple {{host}}/api/cases/multiple-update

dokumentasi ada di postman jika ada yang kurang kasih tau aja nanti cc @Arif9878

**Comment by firmanJS** [comment]
masukin desain nya disini juga mang @ReksaMohammad

**Comment by ReksaMohammad** [comment]
owalah oqe oqe mang siap

> masukin desain nya disini juga mang @ReksaMohammad

**Comment by erlangganugraha** [comment]
jigana salah masukkin desain @ReksaMohammad

**Comment by shintadewiaw** [comment]
mas @firmanJS ketika sudah update status nanti ditambahkan di informasi klinis ya riwayat barunya

**Comment by shintadewiaw** [comment]
mas @Arif9878 tambahkan penanda (kursor) ketika update status multiple
