### ISSUE TITLE
Menambah pilihan lab pada field tempat pemeriksaan di pemeriksaan penunjang

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#849]
![Screenshot_2020-12-08 pelaporan-covid19](https://user-images.githubusercontent.com/11548871/101438530-2ae35400-3945-11eb-9153-208d9483f942.png)

## Acceptance Criteria

- [ ] Menambah pilihan lab pada field tempat pemeriksaan dibagian form input pemeriksaan penunjang
- [x] Unset required field tempat pemeriksaan

**Comment by firmanJS** [comment]
@Arif9878 api pake yang existing di list nya sudah ada lab jika ada tambahan kasih tau aja ya

**Comment by Arif9878** [comment]
@firmanJS ini api/areas/list-unit-lab filter rs_jabar=true/false ga bisa kang

**Comment by firmanJS** [comment]
@Arif9878 sip sudah di perbaiki nunggu approve dulu

**Comment by shintadewiaw** [comment]
![image](https://user-images.githubusercontent.com/63390998/102442323-bdc37300-4056-11eb-9a88-cf40802125b5.png)

belum ada yang lab ya guys @Arif9878 @firmanJS

**Comment by firmanJS** [comment]
> ![image](https://user-images.githubusercontent.com/63390998/102442323-bdc37300-4056-11eb-9a88-cf40802125b5.png)
> 
> belum ada yang lab ya guys @Arif9878 @firmanJS

Ada juga ah coba pakai kotabandung tadi aku bisa @shintadewiaw

**Comment by shintadewiaw** [comment]
udah dibenerin mas arip @firmanJS
