### ISSUE TITLE
Improvement dashboard hasil test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#855]
## User Story
Sebagai dinkes kota/kab dan faskes, saya ingin memonitoring jumlah hasil test yang saya input. Selain itu agar saya tahu jumlah pasien yang dilakukan test berdasarkan sebaran kecamatan, sasaran, dan demografis

## Desain/Prototype
![Screenshot_2020-12-15 Figma(2)](https://user-images.githubusercontent.com/11548871/102185915-68675480-3ee4-11eb-8c8b-5b68cf8bdc31.png)
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=6678%3A1107&viewport=229%2C-10997%2C0.3699679970741272&scaling=min-zoom

## Acceptance Criteria
- [ ] Terdapat Perkembangan Jumlah Hasil Tes dalam bentuk chart
- [ ] Chart Perkembangan Jumlah Hasil Tes bisa difilter berdasarkan metode pemeriksaan
---
- [ ] Terdapat Jumlah Hasil Tes berdasarkan Wilayah per kecamatan dalam bentuk chart
- [ ] Jika login sebagai dinkes prov/superadmin, maka chart Jumlah Hasil Tes berdasarkan Wilayah per kota/kab
---
- [ ] Terdapat Jumlah Hasil Tes berdasarkan Sasaran  dalam bentuk chart
---
- [ ] Terdapat Perbandingan Jenis Kelamin dalam bentuk pie chart
- [ ] Pie chart Perbandingan Jenis Kelamin bisa difilter berdasarkan hasil pemeriksaan
---
- [ ] Terdapat Perbandingan Usia dan Jenis Kelamin  dalam bentuk chart
- [ ] chart Perbandingan Jenis Kelamin bisa difilter berdasarkan hasil pemeriksaan

**Comment by shintadewiaw** [comment]
1. Ketika filter data yang di input pada tahun 2020 tidak ada data yang muncul
![image](https://user-images.githubusercontent.com/63390998/104686031-fb3b1f00-572e-11eb-9383-4d9ffb90a3ba.png)
![image](https://user-images.githubusercontent.com/63390998/104686412-bc599900-572f-11eb-95f8-5972e33e3d29.png)

2. Dikarenakan tanggal hanya 1 (tidak ada tanggal awal/akhir) sebaiknya di validasi bisa memilih tanggal awal terlebih dahulu kemudian akhir, jangan bisa mundur (contoh klik tanggal 5 kemudian tanggal 1)
![image](https://user-images.githubusercontent.com/63390998/104686795-85d04e00-5730-11eb-95eb-3556a8215a0c.png)


3. Penamaan Status pada kolom "Jumlah hasil tes berdasarkan sasaran" sebaiknya berbahasa indonesia
![image](https://user-images.githubusercontent.com/63390998/104686911-c203ae80-5730-11eb-934c-16d619e7452f.png)

4. Jumlah Hasil Tes berdasarkan Wilayah value seharusnya adalah kota/kab
![image](https://user-images.githubusercontent.com/63390998/104687063-0abb6780-5731-11eb-9cda-502841ee228a.png)

5. Perhitungan total Laki - Laki dan Perempuan masih salah
![image](https://user-images.githubusercontent.com/63390998/104687267-7ac9ed80-5731-11eb-8346-dbc6fa02f043.png)
![image](https://user-images.githubusercontent.com/63390998/104687219-5e2db580-5731-11eb-8609-b88f201f1d93.png)

6. Perhitungan umur 0 belum masuk pada dashboard
![image](https://user-images.githubusercontent.com/63390998/104687402-b4025d80-5731-11eb-9e74-c67368b4351d.png)
![image](https://user-images.githubusercontent.com/63390998/104687377-a947c880-5731-11eb-9618-899feb1268de.png)

mas arip @Arif9878 baca dulu, kalo ada yang BE kasih tau nanti ku pindah ke card mas @firmanJS

**Comment by shintadewiaw** [comment]
eh maap nomor 4 betul by kecamatan tapi yang filter by kecamatan kota/kabnya ya mas @Arif9878

**Comment by firmanJS** [comment]
ada yang dari BE juga shin kayanya

**Comment by firmanJS** [comment]
@shintadewiaw 

point 3. sepertinya bisa di handle di fe
point 4. itu udah betul datanya ngaco hampir sama kaya yang dashboar kasus dulu pernah kaya gitu kan
point 5. udah betul deh kayanya
point 6. sepertinya ini perlu diskusi akrena kolom umur di schema input test tipenya string bukan number

CMIIW :running_man:

**Comment by shintadewiaw** [comment]
oh nomor 5 tuh harusnya laki lakinya muncul totalnya mas, ini engga muncul @firmanJS

**Comment by firmanJS** [comment]
@shintadewiaw testing pake dinkes apa ?

**Comment by shintadewiaw** [comment]
kotabogor @firmanJS

**Comment by firmanJS** [comment]
@shintadewiaw ok sip result api udah ok kayanya di fe nya itu mah untuk no.5

**Comment by Arif9878** [comment]
Poin 3 di dinkes kab purwakarta 
![Screen Shot 2021-01-15 at 14 46 28](https://user-images.githubusercontent.com/20775950/104696240-883aa400-5740-11eb-8b8e-af4d65c61c03.png)

**Comment by shintadewiaw** [comment]
jadi itu dari responsnya ya mas? @Arif9878

**Comment by Arif9878** [comment]
iya sih @shintadewiaw

**Comment by shintadewiaw** [comment]
cc: @firmanJS

**Comment by firmanJS** [comment]
@shintadewiaw point 3 udah dibenerin ya tinggal nunggu approve, jika menemukan data sama seperti kontak erat, itu karena data nya kecampur sama yang lama :rocket:

**Comment by Arif9878** [comment]
@shintadewiaw yang tanggal aku pindah ke E2E ya??
