### ISSUE TITLE
Bug Tampilan Update Riwayat Kasus

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#880]
### How to Reproduce Bug
Login sebagai faskeskotabogor (minta tolong sekalian cek yang dinkes takut ada issue yang sama hehe)

**Lampiran**
![image](https://user-images.githubusercontent.com/63390998/103843371-4a97a480-50ca-11eb-9cc0-dac2360a9fa9.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 kok jadi gini?
![image](https://user-images.githubusercontent.com/63390998/103883441-cbc55a80-510f-11eb-9378-a19de28c54d2.png)

![image](https://user-images.githubusercontent.com/63390998/103883507-e1d31b00-510f-11eb-93b5-940027602bd1.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 balik kek gini lagi wkwk
![image](https://user-images.githubusercontent.com/63390998/104269598-4522cb80-54c9-11eb-91cc-cfe8724a7516.png)

**Comment by shintadewiaw** [comment]
masih masarip @Arif9878 
![image](https://user-images.githubusercontent.com/63390998/104276192-f4b26a80-54d6-11eb-8680-03f75a5bf474.png)

**Comment by Arif9878** [comment]
wadau kemarin tuh kayak udah kan yak @shintadewiaw
