### ISSUE TITLE
Bug Edit Hasil Test - Tempat Pemeriksaan Lab

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#891]
Deskripsi:
Ketika memilih dropdown pada Tempat Pemeriksaan Lab pilihan Lab valuenya error
![image](https://user-images.githubusercontent.com/63390998/104684367-769ad180-572b-11eb-9777-07bb115a37b1.png)

**Comment by Arif9878** [comment]
@shintadewiaw  udah sin 
![Screen Shot 2021-01-20 at 16 32 21](https://user-images.githubusercontent.com/20775950/105155450-3083aa80-5b3d-11eb-8c94-e43cdd1388bf.png)

**Comment by shintadewiaw** [comment]
@Arif9878 yang edit gan

**Comment by Arif9878** [comment]
@shintadewiaw ngobrol dong
