### ISSUE TITLE
Dashboard - Penambahan Redaksi Pengumuman

### ISSUE THREAD

**Issue by shintadewiaw** [jabardigitalservice/pikobar-pelaporan-frontend#934]
### Deskripsi
Menambahkan Redaksi Pengumuman (seperti gambar) pada halaman dashboard

#### Lampiran
![image](https://user-images.githubusercontent.com/63390998/114649965-a138fe00-9d0b-11eb-88c0-1e57091efd64.png)

#### Figma
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?node-id=5188%3A18866&viewport=430%2C58%2C0.021072477102279663&scaling=scale-down-width&page-id=3085%3A0

**Comment by Arif9878** [comment]
@shintadewiaw versi tanggal itu gimana maksudnya?

**Comment by shintadewiaw** [comment]
@erlangganugraha

**Comment by erlangganugraha** [comment]
> 
> 
> @shintadewiaw versi tanggal itu gimana maksudnya?

tanggal ketika data terakhir diperbaharui

**Comment by Arif9878** [comment]
sudah di kasih tau belum ke kang @firmanhxc klu ada tanggal terakhir di update di response nya

**Comment by shintadewiaw** [comment]
@firmanJS

**Comment by firmanJS** [comment]
> @firmanJS

@shintadewiaw

**Comment by firmanJS** [comment]
done di response backend di tambah `date_version` @Arif9878 @shintadewiaw

**Comment by firmanJS** [comment]
api pake exisitng @Arif9878 yang di dashboard kasus

**Comment by Arif9878** [comment]
> api pake existing @Arif9878 yang di dashboard kasus
okey kang aku check dulu

**Comment by shintadewiaw** [comment]
belum ada perubahan kaka @Arif9878 

![image](https://user-images.githubusercontent.com/63390998/115355049-7d325c80-a1e4-11eb-8a23-e502a8e03682.png)
