### ISSUE TITLE
Disclaimer caching pada menu dashboard lokasi sebaran

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#967]
## Design
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?page-id=3085%3A0&node-id=3873%3A8&viewport=1769%2C-2328%2C0.8097455501556396&scaling=scale-down-width

## Acceptance Criteria
- [x] Terdapat pop up disclaimer ketika membuka page lokasi sebaran
- [x] Pada disclaimer, terdapat info tanggal update berdasarkan data terbaru diperbaharui
- [x] Pada disclaimer, terdapat intruksi refresh/reload page pada disclaimer

**Comment by shintadewiaw** [comment]
Feedback 09/07 @Arif9878 

- [ ] penyesuaian respons BE 

{
  "status": 200,
  "message": "Success",
  "data": {
    "map": [
        {},
        {},
        {},
    ],
    "date_version": "2021-07-09T02:17:48.234Z"
  }
}

- [ ] Auto scroll kebawah ketika membuka "Tampilkan Keterangan"
