### ISSUE TITLE
Disclaimer caching pada menu laporan harian

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#968]
## Design
https://www.figma.com/proto/qktoBq5MM3HlLNlwrvRgAf/Pelaporan?page-id=3085%3A0&node-id=3244%3A3&viewport=1769%2C-2328%2C0.8097455501556396&scaling=scale-down-width

## Acceptance Criteria
- [x] Pada disclaimer, terdapat info tanggal update berdasarkan data terbaru diperbaharui
- [x] Pada disclaimer, terdapat intruksi refresh/reload page pada disclaimer

**Comment by shintadewiaw** [comment]
belum ada perubahan mas @Arif9878 ,nanti geser lagi ya misal udah dicek
![image](https://user-images.githubusercontent.com/63390998/124864234-c4114080-dfe2-11eb-9341-6e0f56bad16f.png)

**Comment by shintadewiaw** [comment]
mas @Arif9878 ini tanggal sama jamnya masih belum sesuai
![Uploading image.png…]()
