### ISSUE TITLE
Filter & Sorting List Hasil Test

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#99]
## User Story
Sebagai dinkes kota/kab saya ingin memfilter & mengurutkan list hasil test sehingga saya bisa untuk memilih data sesuai data yang disaring & disorting yang diinginkan

## Mockup
![Screen Shot 2020-04-07 at 15 16 05](https://user-images.githubusercontent.com/20775950/78646116-c4ec8b80-78e2-11ea-9935-1138c3f7a334.png)

link figma 

https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=3334%3A1218

## Acceptance Criteria :
* [x] Terdapat dilfilter berdasarkan :
  * [x] Hasil Test
  * [x] Range Tgl Pengetesan
  * [x] Tempat Tes per dinkes kota/kab
  * [x] Kategori
  * [x] Mekanisme
  * [x] Metode Yang Digunakan
* [x] Terdapat sorting berdasarkan :
  * [x] Tanggal tes
  * [x] Nama
  * [x] Usia
  * [x] Jenis Kelamin
* [x] Terdapat reset filter/sorting

## Responsiveness:
- [x] Laptop with HiDPI
- [x] Laptop with MDPI
- [x] Mobile version

## Cross-browser compatibility:
- [x] Chrome
- [x] Firefox

**Comment by Arif9878** [comment]
@firmanJS ini udah belum kang BE nya? trus parameter filternya apa?

**Comment by firmanJS** [comment]
masih in progres mang @Arif9878

**Comment by Arif9878** [comment]
kabar" kang klu udah selesai ya kang @Arif9878

**Comment by firmanJS** [comment]
@Arif9878 filter udah bisa tinggal sort nya ya

param filter

search=code_test atau name atau final_result atau category

**Comment by Arif9878** [comment]
okey

**Comment by firmanJS** [comment]
@Arif9878 sort juga udah beres

contoh

api/rdt?sort={"_id":"desc"}

parameter id bisa di ganti tanggal atau apapun

**Comment by Arif9878** [comment]
filter berdasarkan tanggal test belum?

**Comment by Arif9878** [comment]
> @Arif9878 filter udah bisa tinggal sort nya ya
> 
> param filter
> 
> search=code_test atau name atau final_result atau category

ini categorynya di search gitu jadi search=Kategori A gitu?

**Comment by firmanJS** [comment]
@Arif9878 oh iya bener mang bakal bentrok ya nanti sip nuhun masukan nya nanti di benerin

**Comment by firmanJS** [comment]
@Arif9878 filter api/rdt?category=a&search=test

untuk range tanggal api/rdt?start_date=2020-04-01&end_date=2020-04-02

**Comment by Arif9878** [comment]
ok kang

**Comment by Arif9878** [comment]
yang filter hasil gimana kang parameternya @firmanJS ?

**Comment by firmanJS** [comment]
@Arif9878 pake search=hasil test/nama  mang kalo liat sesuai design

**Comment by Arif9878** [comment]
@firmanJS desainya belum jadi mang wkwkkwkww, sesuain `Acceptance Criteria ` aja dulu hehehe

**Comment by firmanJS** [comment]
Haha siap mang otw dibenerin @Arif9878

**Comment by firmanJS** [comment]
@Arif9878 sudah di benerin ya dan ada perubahan supaya dinamis

contoh api/rdt?search={"category":"A","code_test":"PTS-10262000001"} <-- ini jiga multiple param search

jika single api/rdt?search={"category":"A"}

**Comment by Arif9878** [comment]
mang searching itu bisa nama bisa code test trus pas di input search gimana aku deteksi itu nama atau code test ? @firmanJS

**Comment by firmanJS** [comment]
@Arif9878 :laughing: sepertinya aku salah tangkap wkwkw
sip udah dibenerin api/rdt?search= <--- ini udah sesuai ac

**Comment by alifianif** [comment]
Data yang sudah dihapus dari list masih muncul jika difilter dan disearch

@Arif9878 @firmanJS

**Comment by Arif9878** [comment]
@alifianif filter tempat test pengetesan memang hanya di dinkes prov lif, karna yang dinkes kota kan sudah otomatid di filter berdasarkan dinkes kab/kota

**Comment by saktiperdana** [comment]
Sip , asumsi user kab/kota sudah menampilkan list data sesuai kab/kotanya ya, jadi mmg filter tempat tes hanya ada di user prov

@alifianif @Arif9878
