### ISSUE TITLE
Improvement Fitur Import Registrasi Rujukan

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#992]
## Desain/Prototype
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?page-id=363%3A0&node-id=1810%3A47&viewport=313%2C48%2C0.48&scaling=min-zoom&starting-point-node-id=1810%3A47&show-proto-sidebar=1

### Interface Form import 
- [x] Terdapat contoh template yang bisa didownload
- [x] Terdapat content Syarat Penggunaan

### Validasi/Ketentuan
- [x] Maximal rows yang diimport <=200
- [x] Error ditampilkan dalam bentuk table ketika tahap review
- [x] Apabila ada kolom mandatory isiannya kosong, maka data yang diimportkan error

### Template Import
https://drive.google.com/drive/folders/1isw-TM20k2xcVfQ9ehLrwHgVeu8bg2DR?usp=sharing

### Syarat & Ketentuan
Setiap data wajib memiliki NIK
Jumlah maksimum data dalam sekali import adalah 200 baris

**Comment by erlangganugraha** [comment]
@maruf12 desain prototype udah jadi, udah dilampirin didesc cardnya mang

**Comment by maruf12** [comment]
@erlangganugraha btw di design tidak ada cara penggunaan, adanya syarat ketentuan doang. Nah jadi cara penggunaan disimpen dimana?

![image](https://user-images.githubusercontent.com/9880869/143167494-c4b86240-fb2a-42db-9e18-140920118ca3.png)

**Comment by maruf12** [comment]
@shintadewiaw ready to test sin
