### ISSUE TITLE
Improvement Fitur Import Registrasi Mandiri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#996]
## Desain/Prototype
https://www.figma.com/proto/u6N5eYCP8OS0Fb1LbjSHcf/Management-Lab-Covid-19?page-id=363%3A0&node-id=2483%3A5762&viewport=313%2C48%2C0.48&scaling=scale-down-width&starting-point-node-id=2483%3A5762&show-proto-sidebar=1

### Interface Form import 
- [x] Form import tidak buat pop up, samakan dengan desain prototype
- [x] Proses import yang diawali pilih file sampai import berhasil, flownya disamakan dengan import di **Registrasi Rujukan**
- [x] Terdapat contoh template yang bisa didownload
- [x] Terdapat tab cara penggunaan
- [x] Terdapat tab Syarat & Ketentuan

### Validasi/Ketentuan
- [x] Maximal rows yang diimport <=200
- [x] Error ditampilkan dalam bentuk table ketika tahap review
- [x] Apabila ada kolom mandatory isiannya kosong, maka data yang diimportkan error

### Template Import
https://drive.google.com/drive/folders/1isw-TM20k2xcVfQ9ehLrwHgVeu8bg2DR?usp=sharing

### Syarat & Ketentuan
Setiap data wajib memiliki NIK
Jumlah maksimum data dalam sekali import adalah 200 baris

**Comment by erlangganugraha** [comment]
@maruf12  desain prototype udah jadi, udah dilampirin didesc cardnya mang

**Comment by maruf12** [comment]
@shintadewiaw testing disini sin https://deploy-preview-767--staging-pikobar-lab.netlify.app/registrasi/mandiri/import-excel
